'use strict';
/* Native service navigation and two-owner custody. Authored fixtures never enter the public release. */
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),cp=require('node:child_process'),http=require('node:http');
const {chromium}=require('playwright');
const ROOT=path.resolve(__dirname,'..'),C=require('../core.cjs'),U=require('../cli.cjs');
const OUT=path.resolve(process.env.COMMUNITY_QA_DIR||'community-browser-qa');fs.mkdirSync(OUT,{recursive:true});
const checks=[],external=[],errors=[],servers=[];let browser,work;
function check(name,value){console.log((value?'PASS ':'FAIL ')+name);checks.push({name,pass:!!value});if(!value)throw Error(name);}
function command(...args){return cp.execFileSync(process.execPath,[path.join(ROOT,'cli.cjs'),...args],{encoding:'utf8',timeout:30000,windowsHide:true});}
async function staticServer(root){const server=http.createServer((req,res)=>{let rel;try{rel=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(rel==='/')rel='/index.html';const p=path.resolve(root,'.'+rel);if(!p.startsWith(root+path.sep))throw Error('path');const b=fs.readFileSync(p);res.setHeader('Content-Type',p.endsWith('.html')?'text/html; charset=utf-8':p.endsWith('.json')?'application/json':'text/plain');res.end(b);}catch{res.statusCode=404;res.end('Not found');}});await new Promise(r=>server.listen(0,'127.0.0.1',r));servers.push(server);return 'http://127.0.0.1:'+server.address().port;}
async function close(server){server.closeAllConnections();await new Promise(r=>server.close(r));servers.splice(servers.indexOf(server),1);}
async function downloaded(page,selector,name){const wait=page.waitForEvent('download');await page.locator(selector).click();const d=await wait,p=path.join(OUT,name);await d.saveAs(p);return p;}
(async()=>{work=fs.mkdtempSync(path.join(os.tmpdir(),'sr-community-native-'));const source=path.join(work,'incoming.json'),hub=path.join(work,'first'),second=path.join(work,'second');
 const meta={title:'Fixture path <img src=x onerror=globalThis.pwned=1>',provider:'Authored software qualification fixture',hardware:'No real GPU',workload:'Fixture task',variant:'fixture',observed_at:'2026-09-24',contributor:'Test author',funding:'Authored fixture, no cloud cost',relationship:'Test author',limitations:['Authored test data; never a public benchmark result.'],sources:[{label:'Authored fixture',url:'',sha256:'b'.repeat(64),revision:null}],relation:null};
 const body={model:'test-model',support:'fixture',task:'fixture-work',measure:'fixture accepted count',value:1,maximum:2,cost_usd:null,cost_basis:'unknown',source_sha256:'b'.repeat(64),source_excerpt:'Authored software fixture.',study_status:'software-only'};
 const packet=C.make('historical-finding',body,meta);fs.writeFileSync(source,JSON.stringify(packet));command('init',hub,'--name','First independent test hub','--empty');command('stage',source,'--hub',hub);command('review',packet.sha256,'--hub',hub,'--decision','accept','--reviewer','Qualification test','--reason','Authored isolation fixture');command('build',hub);
 const service=await U.serve(hub,0);servers.push(service.server);
 browser=await chromium.launch({headless:true,...(process.env.SECOND_RUN_BROWSER?{executablePath:process.env.SECOND_RUN_BROWSER}:{} )});
 const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
 await context.route('**/*',route=>{if(/^(http:\/\/127\.0\.0\.1:|file:|blob:|data:)/.test(route.request().url()))return route.continue();external.push(route.request().url());return route.abort();});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.goto(service.origin,{waitUntil:'networkidle'});check('native first visit shows source rows',await page.locator('[data-open]').count()===1);check('HTML-shaped labels stay text',!await page.evaluate(()=>globalThis.pwned));
 await page.locator('[data-open]').click();await page.waitForSelector('#detail-check');check('source-bound inspection opens',await page.locator('#detail').isVisible());
 const exported=await downloaded(page,'#detail-download','exported-evidence.json');check('export preserves packet identity',JSON.parse(fs.readFileSync(exported)).sha256===packet.sha256);command('verify',exported);check('separate process recomputes exported evidence',true);
 await page.locator('#detail-check').click();await page.selectOption('#metric','ratio');await page.selectOption('#operator','at_least');await page.fill('#threshold','0.5');await page.fill('#wording','The fixture record reaches 50%');await page.locator('#check').click();await page.waitForSelector('#save-check');check('claim interpretation returns the observed result',(await page.locator('#check-output').innerText()).includes('Supported by these observations'));
 await page.locator('#save-check').click();await page.reload({waitUntil:'networkidle'});await page.locator('[data-tab="saved"]').click();check('saved decision survives reload',await page.locator('.saved-card').count()===1);
 const decision=await downloaded(page,'[data-export]','decision.json');command('verify-decision',decision);check('downloaded decision recomputes in another process',true);
 await page.locator('[data-tab="contribute"]').click();await page.locator('#import').setInputFiles(exported);await page.waitForSelector('#draft-form');await page.locator('#preview').click();check('public export requires separate approval',await page.locator('#export-packet').isDisabled());await page.locator('#consent').check();check('reviewed packet can be exported',await page.locator('#export-packet').isEnabled());await page.fill('#draft-title','Changed after review');check('editing public label revokes approval',await page.locator('#export-packet').isDisabled());
 await page.locator('[data-tab="results"]').click();for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:900});check('independent hub no overflow '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
 await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:path.join(OUT,'independent-hub.png'),fullPage:true});
 cp.execFileSync(process.execPath,[path.join(hub,'app/cli.cjs'),'init',second,'--name','Second generation hub'],{encoding:'utf8',timeout:30000,windowsHide:true});await close(service.server);
 const service2=await U.serve(second,0);servers.push(service2.server);await page.goto(service2.origin,{waitUntil:'networkidle'});check('second-generation board works after origin loss',await page.locator('[data-open]').count()===1);await page.locator('[data-open]').click();await page.waitForSelector('#detail-check');check('second-generation record verifies without origin',await page.locator('#detail').isVisible());await page.locator('#detail-close').click();
 const fileURL=require('node:url').pathToFileURL(path.join(second,'site/r',packet.sha256+'.html')).href;await page.goto(fileURL,{waitUntil:'load'});check('standalone result recomputes on file origin',(await page.locator('#verified').innerText()).includes('CALCULATION RECOMPUTED'));
 const publicOrigin=await staticServer(path.resolve(ROOT,'..'));await page.goto(publicOrigin+'/results.html',{waitUntil:'networkidle'});check('release board native navigation',await page.locator('[data-open]').count()>0);
 await page.locator('[data-tab="claims"]').click();
 for(const [example,expected] of [['cost','SUPPORTED IN SELECTED RECORDS'],['tail','CONTRADICTED IN SELECTED RECORDS'],['method','SUPPORTED IN SELECTED RECORDS']]){await page.locator('[data-example="'+example+'"]').click();await page.locator('#check').click();await page.waitForSelector('#save-check');check('example '+example+' returns '+expected,(await page.locator('#check-output').innerText()).includes(expected));if(example==='cost')check('small currency values remain nonzero',(await page.locator('#check-output').innerText()).includes('$0.000'));}
 await page.locator('[data-tab="results"]').click();await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:path.join(OUT,'results-desktop.png'),fullPage:true});await page.locator('#theme').click();await page.screenshot({path:path.join(OUT,'results-light.png'),fullPage:true});
 for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:900});check('release no document overflow '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}await page.screenshot({path:path.join(OUT,'results-phone.png'),fullPage:true});
 await page.fill('#search','MI300X');check('search limits displayed paths',await page.locator('[data-open]').count()===2);await page.locator('#reset').click();check('reset restores broader board',await page.locator('[data-open]').count()>2);
 check('no page JavaScript errors',errors.length===0);check('zero external requests',external.length===0);
})().catch(e=>{checks.push({name:'native journey failure',pass:false,error:e.stack});process.exitCode=1;console.error(e.stack);}).finally(async()=>{if(browser)await browser.close();for(const server of [...servers])await close(server);if(work)fs.rmSync(work,{recursive:true,force:true});const receipt={native_navigation:true,set_content_used:false,checks,passed:checks.filter(x=>x.pass).length,failed:checks.filter(x=>!x.pass).length,external_requests:external,page_errors:errors,scope:'Real native navigation on local services; two isolated test owners and source-loss are controlled software tests, not outside contributor adoption or hardware replication.'};fs.writeFileSync(path.join(OUT,'community-browser.json'),JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify({passed:receipt.passed,failed:receipt.failed,output:OUT}));});
