'use strict';
const test=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const C=require('../core.cjs'),H=require('../workload-engine.cjs'),U=require('../cli.cjs');
const copy=x=>JSON.parse(JSON.stringify(x));
function meta(){return {title:'Test deployment',provider:'Test provider',hardware:'Test GPU',workload:'Six test requests',variant:'default',observed_at:'2026-09-24T00:00:00Z',contributor:'Fixture author',funding:'No money; authored software fixture',relationship:'Author',limitations:['Synthetic software test only.'],sources:[{label:'Fixture source',url:'',sha256:'a'.repeat(64),revision:null}],relation:null};}
function report(synthetic=true){const raw={duration:6,num_prompts:6,completed:5,errors:['','','','','','error'],ttfts:[.1,.2,.3,.4,2,0],latencies:[1,1,2,2,3,0],queue_times:[0,0,0,0,0,0],model_id:'fixture-model',model_revision:'rev',precision:'FP8',tokenizer_revision:'tok',workload_id:'fixture-work',cache_policy:'off',runtime_digest:'runtime',load_profile:'fixture-load',synthetic},bytes=Buffer.from(JSON.stringify(raw));let r=H.normalize(raw,{sha256:H.sha256(bytes),bytes:bytes.length,record_index:0});r=H.attachQuality(r,{schema:'hot-aisle/request-evaluation@1',source_sha256:r.source.sha256,record_index:0,evaluator:'fixture checks',criterion_id:'fixture-v1',passed:[true,true,false,true,true,false]});const settings={identity:{},quality:true,ttft:1000,e2e:60000,queue:true},aggregate=H.aggregate([r],settings),price={provider:'Test',rate:3,gpus:1,total:.05};const payload={schema:'hot-aisle/workload-report@2',version:H.VERSION,synthetic,sides:[{label:'A',normalized:[r],settings,price,aggregate,cost:H.costing(aggregate,price)}],comparison:null};return {schema:'hot-aisle/sealed-report@1',payload,sha256:C.hash(payload)};}
function native(synthetic=true){return C.fromReport(report(synthetic),meta(),'modeled');}
function historical(){return C.make('tierbench-trials',{task:'task-a',model:'old-model',effort:'observed',support:'harness',cost_basis:'shadow-estimated',unit:'passed task attempts',verifier:'Source-reported validator',source_sha256:'c'.repeat(64),claim_basis:'Reported historical ledger',trials:[{line:1,sha256:'d'.repeat(64),outcome:'pass',cost_usd:.2,latency_ms:10,input_tokens:100,output_tokens:20},{line:2,sha256:'e'.repeat(64),outcome:'error',cost_usd:.1,latency_ms:null,input_tokens:null,output_tokens:null}]},meta());}
function tmp(){return fs.mkdtempSync(path.join(os.tmpdir(),'community-test-'));}
function makeHub(){const d=path.join(tmp(),'hub');U.init(d,'Fixture hub',false);return d;}
test('native counts and arithmetic come from the original engine',()=>{const p=native(),r=C.summarize(p);a.equal(r.accepted,3);a.equal(r.completed,5);a.equal(r.attempted,6);a.equal(r.synthetic,true);a.ok(Math.abs(r.cost_per_unit-.05/3)<1e-14);});
test('tampering breaks the sealed packet',()=>{const p=native();p.payload.metadata.title='changed';a.throws(()=>C.verify(p),/checksum/);});
test('resealing an incorrect measured number still fails inner engine',()=>{const p=native();p.payload.body.report.payload.sides[0].aggregate.accepted=4;p.payload.body.report.sha256=C.hash(p.payload.body.report.payload);p.sha256=C.hash(p.payload);a.throws(()=>C.verify(p),/Derived results/);});
test('source synthetic status survives metadata changes',()=>{const p=native();p.payload.metadata.limitations=[];p.sha256=C.hash(p.payload);a.equal(C.summarize(p).synthetic,true);});
test('unsupported evidence cannot be relabelled as a native result',()=>a.throws(()=>C.make('hardware-win',{value:90},meta())));
test('prototype-bearing JSON refuses at ingress',()=>a.throws(()=>C.parse('{"__proto__":{"polluted":true}}'),/Unsafe/));
test('negative latency rejected in historical summaries',()=>{const p=historical();p.payload.body.trials[0].latency_ms=-1;p.sha256=C.hash(p.payload);a.throws(()=>C.verify(p));});
test('all attempts including errors contribute to historical cost',()=>{const r=C.summarize(historical());a.equal(r.accepted,1);a.equal(r.attempted,2);a.ok(Math.abs(r.cost_per_unit-.3)<1e-14);a.equal(r.evidence,'historical trial summary');});
test('partial cost coverage stays unknown rather than zero',()=>{const p=historical();p.payload.body.trials[1].cost_usd=null;p.sha256=C.hash(p.payload);a.equal(C.summarize(p).cost_per_unit,null);});
test('different historical task rows do not become a controlled comparison',()=>a.equal(C.compare(historical(),native()).status,'DESCRIPTIVE_ONLY'));
test('duplicate evidence fingerprints are metadata independent',()=>{const p=native(),q=C.make(p.payload.kind,p.payload.body,{...meta(),title:'Same run renamed'});a.equal(C.summarize(p).fingerprint,C.summarize(q).fingerprint);a.match(C.compare(p,q).issues.join(' '),/same underlying evidence/);});
test('unknown numeric sorts remain last in both directions',()=>{for(const direction of ['asc','desc']){const rs=C.sort([{id:'a',cost:null},{id:'b',cost:2},{id:'c',cost:1}],'cost',direction);a.equal(rs.at(-1).id,'a');}});
test('HTML-shaped plain text is data, not executable markup',()=>{const p=C.make('tierbench-trials',historical().payload.body,{...meta(),title:'<img src=x onerror=alert(1)>'});a.equal(C.summarize(p).title,'<img src=x onerror=alert(1)>');});
test('javascript source URLs refuse',()=>{const m=meta();m.sources[0].url='javascript:alert(1)';a.throws(()=>C.make('tierbench-trials',historical().payload.body,m));});
test('credential source URL refuses',()=>{const m=meta();m.sources[0].url='https://secret:password@example.com/a';a.throws(()=>C.make('tierbench-trials',historical().payload.body,m));});
test('privacy preview catches recognizable credentials',()=>{const p=historical();p.payload.metadata.funding='ghp_'+ 'a'.repeat(25);a.ok(C.privacy(p).includes('credential'));});
test('claim on synthetic evidence stays a gap',()=>{const p=native(),c={left:p.sha256,right:null,metric:'accepted',operator:'greater',threshold:0,scope:'observed',wording:'The sample passes'};a.equal(C.checkClaim([p],c).status,'EVIDENCE_GAP');});
test('universal claim is held at observed scope',()=>{const p=historical(),c={left:p.sha256,right:null,metric:'ratio',operator:'at_least',threshold:.5,scope:'general',wording:'This model always works'};a.equal(C.checkClaim([p],c).status,'SCOPE_LIMIT');});
test('a false observed threshold is a contradiction',()=>{const p=historical(),c={left:p.sha256,right:null,metric:'ratio',operator:'greater',threshold:.9,scope:'observed',wording:'The recorded rate exceeds 90%'};a.equal(C.checkClaim([p],c).status,'CONTRADICTED_IN_SELECTED_RECORDS');});
test('decision keeps its evidence and independently recomputes',()=>{const p=historical(),c={left:p.sha256,right:null,metric:'ratio',operator:'at_least',threshold:.5,scope:'observed',wording:'The recorded rate reaches 50%'};const d=C.decision([p],c,'2026-09-24T00:00:00Z');a.equal(C.verifyDecision(d).sha256,d.sha256);d.payload.result.left_value=.9;d.sha256=C.hash(d.payload);a.throws(()=>C.verifyDecision(d));});
test('hub refuses existing directory without changes',()=>{const d=tmp(),f=path.join(d,'owned');fs.writeFileSync(f,'keep');a.throws(()=>U.init(d));a.equal(fs.readFileSync(f,'utf8'),'keep');fs.rmSync(d,{recursive:true,force:true});});
test('stage does not admit, and review requires a reason',()=>{const h=makeHub(),p=historical(),f=path.join(h,'input.json');fs.writeFileSync(f,JSON.stringify(p));a.equal(U.stage(f,h).status,'STAGED_FOR_REVIEW');a.equal(U.buildHub(h).records,0);a.throws(()=>U.review(p.sha256,h,'accept','Me',''));a.equal(U.review(p.sha256,h,'accept','Me','Read the sources').status,'ADMITTED');a.equal(U.buildHub(h).records,1);fs.rmSync(path.dirname(h),{recursive:true,force:true});});
test('synthetic public admission refuses',()=>{const h=makeHub(),p=native(),f=path.join(h,'sample.json');fs.writeFileSync(f,JSON.stringify(p));U.stage(f,h);a.throws(()=>U.review(p.sha256,h,'accept','Me','Test'),/Synthetic/);fs.rmSync(path.dirname(h),{recursive:true,force:true});});
test('second contributor name cannot launder duplicate trials',()=>{const h=makeHub(),p=historical(),q=C.make(p.payload.kind,p.payload.body,{...meta(),contributor:'Different name'});for(const [i,x] of [p,q].entries()){const f=path.join(h,i+'.json');fs.writeFileSync(f,JSON.stringify(x));U.stage(f,h);}U.review(p.sha256,h,'accept','Me','First');a.throws(()=>U.review(q.sha256,h,'accept','Me','Second'),/reuses existing evidence/);fs.rmSync(path.dirname(h),{recursive:true,force:true});});
test('withdrawal keeps the object and adds a later event',()=>{const h=makeHub(),p=historical(),f=path.join(h,'x.json');fs.writeFileSync(f,JSON.stringify(p));U.stage(f,h);U.review(p.sha256,h,'accept','Me','First');U.review(p.sha256,h,'reject','Me','Later correction');a.equal(U.buildHub(h).records,0);a.equal(U.events(h).length,2);a.ok(fs.existsSync(path.join(h,'objects',p.sha256+'.json')));fs.rmSync(path.dirname(h),{recursive:true,force:true});});
test('feed import does not inherit approval',()=>{const h=makeHub(),f=path.join(h,'incoming.json'),p=historical();fs.writeFileSync(f,JSON.stringify(U.feed({name:'Other',created_at:'2026-09-24'},[p])));a.equal(U.ingest(f,h).records.length,1);a.equal(U.buildHub(h).records,0);fs.rmSync(path.dirname(h),{recursive:true,force:true});});
test('review history tampering holds a rebuild',()=>{const h=makeHub(),p=historical(),f=path.join(h,'x.json');fs.writeFileSync(f,JSON.stringify(p));U.stage(f,h);U.review(p.sha256,h,'accept','Me','First');const log=path.join(h,'reviews',fs.readdirSync(path.join(h,'reviews'))[0]);const e=JSON.parse(fs.readFileSync(log));e.payload.reason='changed';fs.writeFileSync(log,JSON.stringify(e));a.throws(()=>U.buildHub(h),/chain/);fs.rmSync(path.dirname(h),{recursive:true,force:true});});
test('submission requires exact explicit approval before any network effect',()=>{const d=tmp(),p=historical(),f=path.join(d,'x.json');fs.writeFileSync(f,JSON.stringify(p));let calls=0;a.throws(()=>U.submit(f,'owner/repo','wrong',()=>calls++));a.equal(calls,0);fs.rmSync(d,{recursive:true,force:true});});
test('approved submission retains a gist if issue creation fails',()=>{const d=tmp(),p=historical(),f=path.join(d,'x.json');fs.writeFileSync(f,JSON.stringify(p));let calls=0;const r=U.submit(f,'owner/repo',p.sha256,()=>{if(++calls===1)return {html_url:'https://gist.github.com/fixture/abc'};throw Error('No issue permission');});a.equal(r.status,'GIST_PUBLISHED_ISSUE_FAILED');a.equal(calls,2);a.equal(r.gist,'https://gist.github.com/fixture/abc');fs.rmSync(d,{recursive:true,force:true});});
test('generated standalone result escapes submitted labels',()=>{const p=C.make('tierbench-trials',historical().payload.body,{...meta(),title:'<img src=x onerror=alert(1)>'}),html=U.renderResult(p);a.ok(!html.includes('<h1 style="font-size:34px"><img'));a.ok(html.includes('\\u003cimg'));});
module.exports={meta,report,native,historical};
test('rendered scripts parse without string substitution corruption',()=>{const vm=require('node:vm'),p=historical(),html=U.renderPage({name:'Test',created_at:'2026-09-24'},[p]).html;for(const m of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)){if(m[0].includes('type="application/json"'))continue;new vm.Script(m[1]);}const page=U.renderResult(p);for(const m of page.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)){if(m[0].includes('type="application/json"'))continue;new vm.Script(m[1]);}});
test('a correction is additive and keeps old evidence identity',()=>{const p=historical(),m={...meta(),relation:{kind:'correction',target:p.sha256,note:'Corrected the attribution; source trials unchanged.'},contributor:'Corrected author'};const q=C.make(p.payload.kind,p.payload.body,m);a.notEqual(q.sha256,p.sha256);a.equal(C.summarize(q).fingerprint,C.summarize(p).fingerprint);a.equal(q.payload.metadata.relation.target,p.sha256);});
test('copied hub can seed the next generation without the first source tree',()=>{const d=tmp(),h=path.join(d,'first'),p=historical(),f=path.join(d,'packet.json');U.init(h,'First',false);fs.writeFileSync(f,JSON.stringify(p));U.stage(f,h);U.review(p.sha256,h,'accept','Test','Fixture');U.buildHub(h);const cp=require('node:child_process');cp.execFileSync(process.execPath,[path.join(h,'app','cli.cjs'),'init',path.join(d,'second'),'--name','Second'],{encoding:'utf8'});a.equal(JSON.parse(fs.readFileSync(path.join(d,'second','site','board.json'))).payload.records.length,1);fs.rmSync(d,{recursive:true,force:true});});
test('relative local sources do not count as public URLs',()=>a.throws(()=>C.sourceURL('../secret')));
test('record source URLs preserve the declared public reference',()=>a.equal(C.sourceURL('https://example.org/results?revision=x'),'https://example.org/results?revision=x'));
test('native result is rejected when internal price arithmetic is forged',()=>{const p=native();p.payload.body.report.payload.sides[0].cost.total=0;p.payload.body.report.sha256=C.hash(p.payload.body.report.payload);p.sha256=C.hash(p.payload);a.throws(()=>C.verify(p));});
test('invalid feeds are rejected before any review is inherited',()=>{const f=U.feed({name:'Source',created_at:'2026-09-24'},[historical()]);f.payload.records[0].payload.metadata.title='tampered';f.sha256=C.hash(f.payload);a.throws(()=>U.verifyFeed(f));});
test('privacy scan recognizes Unix home paths and email',()=>{const p=historical();p.payload.metadata.funding='/home/example/private file@example.com';a.deepEqual(C.privacy(p).sort(),['email','local path']);});
test('unknown workload cost basis cannot be called invoice verified',()=>{const p=native();p.payload.body.cost_basis='invoice-reconciled';p.sha256=C.hash(p.payload);a.throws(()=>C.verify(p));});
test('separate findings cannot forge a native workload group',()=>{const p=historical(),q=copy(p);q.payload.body.task='unrelated';q.sha256=C.hash(q.payload);const c={left:p.sha256,right:q.sha256,metric:'ratio',operator:'at_least',threshold:0,scope:'observed',wording:'Compare two different tasks'};a.equal(C.checkClaim([p,q],c).status,'EVIDENCE_GAP');});

test('historical source zero can be preserved without pricing it as free',()=>{const p=historical();p.payload.body.trials[0].source_cost_usd=0;p.payload.body.trials[0].cost_usd=null;p.sha256=C.hash(p.payload);a.equal(C.summarize(p).cost_per_unit,null);a.equal(C.verify(p).payload.body.trials[0].source_cost_usd,0);});
