#!/usr/bin/env node
/* Writes campaign/cells.sh: one `docker exec vllm vllm bench serve …` line per cell, built by
   the runner's own argument builder (runner/lib/vllm.cjs) from plan.hotaisle.json. The manual
   arms therefore run byte-identical benchmark arguments to the cells the runner drives on the
   Hot Aisle arm: same dataset, lengths, prompt count, seed rule, export flags and identity
   metadata. Only the result directory and the plan hash differ (the manual arms have no
   approved plan, so plan_sha256 is omitted and cell metadata says so). */
const fs = require('node:fs');
const path = require('node:path');
const vllm = require('../runner/lib/vllm.cjs');

const here = __dirname;
const plan = JSON.parse(fs.readFileSync(path.join(here, 'plan.hotaisle.json'), 'utf8'));
const command = plan.target.vllm_command || ['vllm', 'bench', 'serve'];
const resultDir = plan.target.remote_dir || '/tmp/workload-report';
const cells = [];
for (const concurrency of plan.concurrency) for (let repeat = 0; repeat < plan.repeats; repeat++) cells.push({ concurrency, repeat });

/* One file per runtime: the only difference is the declared runtime digest, which must name
   the image that actually served the requests on that arm. */
const identity = JSON.parse(fs.readFileSync(path.join(here, 'identity.json'), 'utf8'));
for (const kind of ['amd', 'nvidia']) {
  const runtime = identity.runtimes[kind].runtime_digest;
  const lines = [
    '# GENERATED by campaign/gen-cells.cjs from campaign/plan.hotaisle.json + identity.json. Do not edit; regenerate.',
    '# ' + cells.length + ' cells: concurrency ' + plan.concurrency.join(', ') + ' × ' + plan.repeats + ' repeats · ' + plan.workload.model + ' · runtime ' + runtime,
    '# Each line is one complete benchmark for `arm.sh bench ' + kind + '` (manual arms). The Hot Aisle arm gets the',
    '# same arguments from the runner over ssh, plus plan_sha256 in its metadata.',
  ];
  for (const cell of cells) {
    const resultFile = 'cell-c' + cell.concurrency + '-r' + cell.repeat + '.json';
    const args = vllm.buildArgs({ ...plan, sha256: undefined, identity: { ...plan.identity, runtime_digest: runtime } }, cell, resultDir, resultFile);
    lines.push(vllm.commandString(command, args));
  }
  const out = path.join(here, 'cells.' + kind + '.sh');
  fs.writeFileSync(out, lines.join('\n') + '\n');
  console.log('wrote ' + path.relative(process.cwd(), out) + ': ' + cells.length + ' cells, runtime ' + runtime.slice(0, 40) + '…');
}
