'use strict';
const test=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),http=require('node:http'),{spawn}=require('node:child_process'),{PassThrough}=require('node:stream');
const B=require('../scripts/connect.cjs'),C=require('../engine.cjs'),fixture=require('./fixtures.json');
function setup(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'compute-test-'));fs.writeFileSync(path.join(dir,'private-customer-name.json'),JSON.stringify(fixture.a));return dir;}
const req=(origin,route,headers={},method='GET')=>new Promise((resolve,reject)=>{const r=http.request(origin+route,{headers,method},res=>{const b=[];res.on('data',s=>b.push(s));res.on('end',()=>resolve({status:res.statusCode,headers:res.headers,text:Buffer.concat(b).toString()}));});r.on('error',reject);r.end();});
test('CLI accepts only explicit flags',()=>{a.equal(B.parseArgs(['--mcp','--results','/tmp']).mcp,true);a.throws(()=>B.parseArgs(['--secret']));a.throws(()=>B.parseArgs(['--results']));a.throws(()=>B.parseArgs(['--port','70000']));});
test('endpoint addresses require secure explicit scope',()=>{a.throws(()=>B.makeWorkspace({endpoint:'http://other.test:8000'}));a.throws(()=>B.makeWorkspace({endpoint:'https://user:secret@example.test'}));a.throws(()=>B.makeWorkspace({endpoint:'file:///tmp/private'}));});
test('read configured runs and strip raw content and filenames',()=>{const dir=setup();try{const raw=JSON.parse(fs.readFileSync(path.join(dir,'private-customer-name.json')));raw.generated_texts=['TOP SECRET'];raw.privateHost='INTERNAL';fs.writeFileSync(path.join(dir,'private-customer-name.json'),JSON.stringify(raw));const ws=B.makeWorkspace({results:dir}),r=ws.listRuns();a.equal(r.runs.length,1);a.equal(r.runs[0].synthetic,true);const full=ws.getRun(r.runs[0].id),s=JSON.stringify(full);a.ok(!s.includes('TOP SECRET'));a.ok(!s.includes('private-customer-name'));a.ok(!s.includes('INTERNAL'));}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('hash identifies original data; forged paths refuse',()=>{const dir=setup();try{const w=B.makeWorkspace({results:dir}),r=w.listRuns();a.equal(r.runs.length,1);a.throws(()=>w.getRun('../passwd'));a.throws(()=>w.getRun('0'.repeat(64)));const first=r.runs[0].id;fs.appendFileSync(path.join(dir,'private-customer-name.json'),' ');const second=w.listRuns().runs[0].id;a.notEqual(first,second);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('malformed files are visible holds and do not erase valid runs',()=>{const dir=setup();try{fs.writeFileSync(path.join(dir,'bad.json'),'{bad');const r=B.makeWorkspace({results:dir}).listRuns();a.equal(r.runs.length,1);a.equal(r.holds.length,1);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('duplicate bytes do not become additional trials',()=>{const dir=setup();try{fs.copyFileSync(path.join(dir,'private-customer-name.json'),path.join(dir,'second.json'));const r=B.makeWorkspace({results:dir}).listRuns();a.equal(r.runs.length,1);a.equal(r.holds.length,1);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('symlinks are excluded from allowed directory',()=>{const dir=setup();try{fs.symlinkSync(path.join(dir,'private-customer-name.json'),path.join(dir,'link.json'));const r=B.makeWorkspace({results:dir}).listRuns();a.equal(r.runs.length,1);a.ok(r.holds.some(h=>h.reason.includes('Symlink')));}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('no configured paths is valid empty workspace',async()=>{const w=B.makeWorkspace({});a.equal(w.listRuns().runs.length,0);a.equal(w.hardware(),null);a.equal((await w.getEndpoint()).status,'NOT_CONFIGURED');});
test('only selected hardware receipt is read and reduced',()=>{const dir=setup();try{const p=path.join(dir,'hardware.json');fs.writeFileSync(p,JSON.stringify({schema:'aperture-support/1',host:'private',cpu:{model:'CPU'},nvidia:[{name:'GPU',totalBytes:123,serial:'secret'}]}));const r=B.makeWorkspace({aperture:p}).hardware();a.equal(r.cpu,'CPU');a.ok(!JSON.stringify(r).includes('secret'));}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('MCP tools are real read-only invocations',async()=>{const dir=setup();try{const w=B.makeWorkspace({results:dir}),input=new PassThrough(),output=new PassThrough();let text='';output.on('data',s=>text+=s);const m=B.startMcp(w,input,output);for(const obj of [{jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-11-25',capabilities:{},clientInfo:{name:'test',version:'1'}}},{jsonrpc:'2.0',method:'notifications/initialized'},{jsonrpc:'2.0',id:2,method:'tools/list'},{jsonrpc:'2.0',id:3,method:'tools/call',params:{name:'compute_list_runs',arguments:{}}},{jsonrpc:'2.0',id:4,method:'tools/call',params:{name:'compute_list_offers',arguments:{hours:10,asOf:'2026-09-22',provider:'hotaisle'}}}])input.write(JSON.stringify(obj)+'\n');await m.done();const lines=text.trim().split('\n').map(JSON.parse);a.equal(lines[0].result.protocolVersion,'2025-11-25');a.equal(lines[1].result.tools.length,11);a.equal(lines[2].result.structuredContent.runs.length,1);a.equal(lines[3].result.structuredContent.offers.length,4);a.ok(lines[1].result.tools.every(x=>x.annotations.readOnlyHint));input.destroy();output.destroy();}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('MCP unknown arguments and methods fail explicitly',async()=>{const w=B.makeWorkspace({});await a.rejects(B.call(w,'compute_list_runs',{path:'/etc/passwd'}));await a.rejects(B.call(w,'provision_gpu',{}));});
test('HTTP private session binds host, origin, method and token',async()=>{const dir=setup(),s=await B.startHttp(B.makeWorkspace({results:dir}));try{const auth={Authorization:'Bearer '+s.token};a.equal((await req(s.origin,'/')).status,200);a.equal((await req(s.origin,'/api/runs')).status,401);const r=await req(s.origin,'/api/runs',auth);a.equal(r.status,200);a.equal(JSON.parse(r.text).runs.length,1);a.equal(r.headers['access-control-allow-origin'],undefined);a.equal((await req(s.origin,'/api/runs',{...auth,Origin:'https://evil.invalid'})).status,403);a.equal((await req(s.origin,'/api/runs',{...auth,Host:'evil.invalid'})).status,403);a.equal((await req(s.origin,'/api/runs',auth,'POST')).status,405);a.equal((await req(s.origin,'/etc/passwd',auth)).status,404);const id=JSON.parse(r.text).runs[0].id;a.equal((await req(s.origin,'/api/runs/'+id,auth)).status,200);}finally{await new Promise(r=>s.server.close(r));fs.rmSync(dir,{recursive:true,force:true});}});
test('endpoint reads models and allowlisted counters without inference',async()=>{let calls=[];const server=http.createServer((req,res)=>{calls.push([req.method,req.url]);if(req.url==='/v1/models'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify({data:[{id:'test-model',secret:'secret'}]}));}else if(req.url==='/metrics')res.end('vllm:num_requests_running{model="test"} 2\nvllm:num_requests_running{model="other"} 3\nvllm:generation_tokens_total 500\nunallowed_secret_metric 77\n');else{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));try{const w=B.makeWorkspace({endpoint:'http://127.0.0.1:'+server.address().port}),r=await w.getEndpoint();a.equal(r.status,'OBSERVED');a.deepEqual(r.models,['test-model']);a.equal(r.metrics['vllm:num_requests_running'],5);a.equal(Object.keys(r.metrics).length,2);a.deepEqual(calls,[['GET','/v1/models'],['GET','/metrics']]);}finally{server.closeAllConnections();await new Promise(r=>server.close(r));}});
test('redirecting configured endpoint is refused',async()=>{const s=http.createServer((q,r)=>{r.writeHead(302,{Location:'http://127.0.0.1:1/private'});r.end();});await new Promise(r=>s.listen(0,'127.0.0.1',r));try{const w=B.makeWorkspace({endpoint:'http://127.0.0.1:'+s.address().port});a.equal((await w.getEndpoint()).status,'UNAVAILABLE');}finally{s.closeAllConnections();await new Promise(r=>s.close(r));}});
test('actual stdio process handshakes and returns deterministic economics',async()=>{const cp=spawn(process.execPath,[path.join(__dirname,'../scripts/connect.cjs'),'--mcp'],{stdio:['pipe','pipe','pipe']});let out='',err='';cp.stdout.on('data',s=>out+=s);cp.stderr.on('data',s=>err+=s);cp.stdin.end([{jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-11-25'}},{jsonrpc:'2.0',method:'notifications/initialized'},{jsonrpc:'2.0',id:2,method:'tools/call',params:{name:'compute_plan',arguments:{offerIds:['ha-mi300x-1'],hours:160,asOf:'2026-09-22'}}}].map(JSON.stringify).join('\n')+'\n');const code=await new Promise((r,j)=>{cp.on('error',j);cp.on('exit',r);});a.equal(code,0,err);const lines=out.trim().split('\n').map(JSON.parse);a.equal(lines[1].result.structuredContent.options[0].total,478.40000000000003);a.equal(lines[1].result.structuredContent.authority.execute,false);});

test('MCP rejects schema type drift rather than coercing',async()=>{const w=B.makeWorkspace({});await a.rejects(B.call(w,'compute_list_offers',{hours:'10'}));await a.rejects(B.call(w,'compute_list_offers',{gpus:.5}));await a.rejects(B.call(w,'compute_list_offers',{provider:{}}));});

test('materials MCP tool exposes fixed-source recipe and no execution authority',async()=>{const r=await B.call({},'compute_materials',{recipe:'coding-burst'});a.equal(r.schema,'second-run/material-view@1');a.equal(r.recipes.length,1);a.equal(r.recipes[0].id,'coding-burst');a.ok(r.sources.length>0);a.ok(r.actions_not_granted.includes('execute'));a.ok(r.actions_not_granted.includes('read secrets'));});
test('materials tool rejects arbitrary source and path arguments',async()=>{await a.rejects(B.call({},'compute_materials',{url:'http://127.0.0.1/'}));await a.rejects(B.call({},'compute_materials',{path:'/private'}));await a.rejects(B.call({},'compute_materials',{recipe:'unknown'}));});
test('actual stdio client consumes operating materials',async()=>{const cp=spawn(process.execPath,[path.join(__dirname,'../scripts/connect.cjs'),'--mcp'],{stdio:['pipe','pipe','pipe']});let out='',err='';cp.stdout.on('data',s=>out+=s);cp.stderr.on('data',s=>err+=s);cp.stdin.end([{jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-11-25'}},{jsonrpc:'2.0',method:'notifications/initialized'},{jsonrpc:'2.0',id:2,method:'tools/call',params:{name:'compute_materials',arguments:{recipe:'documents-and-search'}}}].map(JSON.stringify).join('\n')+'\n');const code=await new Promise((r,j)=>{cp.on('error',j);cp.on('exit',r);});a.equal(code,0,err);const rows=out.trim().split('\n').map(JSON.parse);a.equal(rows[1].result.isError,false);a.equal(rows[1].result.structuredContent.recipes[0].id,'documents-and-search');a.ok(rows[1].result.structuredContent.actions_not_granted.includes('install'));});

// Keep the new material checks under the existing bridge-test entrypoint.
// No workflow permission or workflow change is required for this source-only release.
require('./test_materials.cjs');
test('bounded public-feed Python suite passes',async()=>{const python=process.env.PYTHON||(process.platform==='win32'?'python':'python3');const cp=spawn(python,['-m','unittest','discover','-s',__dirname,'-p','test_material_feeds.py','-v'],{stdio:['ignore','pipe','pipe'],env:{...process.env,PYTHONDONTWRITEBYTECODE:'1'}});let out='';cp.stdout.on('data',s=>out+=s);cp.stderr.on('data',s=>out+=s);const code=await new Promise((r,j)=>{cp.on('error',j);cp.on('exit',r);});a.equal(code,0,out);a.match(out,/Ran 24 tests/);});
