'use strict';
const test=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const C=require('../engine.cjs'),H=require('../adapters/workload-engine.cjs'),{verify}=require('../scripts/recompute.cjs');
const data=JSON.parse(fs.readFileSync(path.join(__dirname,'../data/catalog.json'))),copy=x=>JSON.parse(JSON.stringify(x));
const find=id=>data.offers.find(o=>o.id===id),p={hours:160,asOf:'2026-09-22',minMemoryGB:24,gpus:1};
const own={hours:160,capex:1500,residual:300,months:24,loadWatts:400,idleWatts:70,kwhPrice:.2,opsMonthly:10,cloudHourly:.5};
const rp={requests:100,premiumHourly:3,qualificationCost:10,repeats:20,validationCostPerRequest:0,classes:[{name:'routine',share:80,baselineSeconds:1,targetSeconds:1,targetHourly:.5,fallbackPercent:0,premium:false},{name:'judgment',share:20,baselineSeconds:20,targetSeconds:20,targetHourly:3,fallbackPercent:0,premium:true}]};
function near(x,y){a.ok(Math.abs(x-y)<1e-9,`${x} != ${y}`);}
test('catalog contains four distinct providers and 30 sourced offers',()=>{C.validateCatalog(data);a.equal(data.providers.length,4);a.equal(data.offers.length,30);});
test('published-price order is not a performance ranking',()=>{const r=C.market(data,p);a.equal(r[0].id,'rp-a5000');a.equal(r[0].total,43.2);a.equal(r[0].evidence,'PUBLISHED_PRICE_MODEL');});
test('DigitalOcean reviewed rates supersede historical comparison',()=>{near(data.offers.find(x=>x.provider==='digitalocean'&&x.gpu==='MI300X').rate,2.59);near(data.offers.find(x=>x.provider==='digitalocean'&&x.gpu==='H100').rate,4.41);});
test('date-aware Nebius schedule',()=>{const o=data.offers.find(x=>x.provider==='nebius'&&x.gpu.includes('H100'));near(C.priceAt(o,'2026-09-22').rate,3.85);near(C.priceAt(o,'2026-10-01').rate,4.5);});
test('unknown historical price refuses backcasting',()=>a.throws(()=>C.priceAt(data.offers[0],'2026-07-01')));
test('zero rental duration does not imply a minimum reservation',()=>a.equal(C.quote(find('ha-mi300x-8'),{...p,hours:0}).total,0));
test('eight GPU whole-node minimum counts all eight GPUs for 30 days',()=>{const o=data.offers.find(o=>o.provider==='hotaisle'&&o.gpus===8),r=C.quote(o,{...p,hours:1});a.equal(r.billedHours,720);near(r.total,3.39*8*720);a.equal(r.minimumApplied,true);});
test('memory is per GPU and never pooled',()=>a.equal(C.market(data,{...p,minMemoryGB:256,provider:'hotaisle',gpus:0}).length,0));
test('filter GPU count explicitly',()=>a.ok(C.market(data,{...p,gpus:8}).every(r=>r.gpus===8)));
test('provider search and vendor filter',()=>a.ok(C.market(data,{...p,query:'MI300X',vendor:'AMD'}).every(r=>r.vendor==='AMD')));
test('extras count for billed hours',()=>{const r=C.quote(data.offers[0],{...p,extraPerHour:1,fixedCost:5});near(r.extraCharge,165);});
test('no matches returns empty rather than an invented recommendation',()=>a.deepEqual(C.market(data,{...p,minMemoryGB:1000}),[]));
test('duplicate offer identifier refuses',()=>{const x=copy(data);x.offers.push(x.offers[0]);a.throws(()=>C.validateCatalog(x));});
test('negative price refuses',()=>{const x=copy(data);x.offers[0].rate=-1;a.throws(()=>C.validateCatalog(x));});
for(const bad of [-1,Infinity,NaN,'160'])test('invalid reserved hours '+String(bad),()=>a.throws(()=>C.market(data,{...p,hours:bad})));
test('freshness detects 31 days but preserves snapshot',()=>{a.equal(C.freshness(data,'2026-10-23').status,'STALE');a.equal(C.freshness(data,'2026-10-22').status,'DATED_SNAPSHOT');a.equal(C.freshness(data,'2026-09-01').status,'FUTURE_SNAPSHOT');});
test('invalid calendar date refuses',()=>a.throws(()=>C.date('2026-02-30')));
test('ownership includes idle energy, depreciation, maintenance',()=>{const r=C.ownership(own);near(r.energyMonthly,20.64);near(r.amortizationMonthly,50);near(r.ownershipMonthly,80.64);near(r.rentalMonthly,80);a.equal(r.basis,'EQUAL_RESERVED_HOURS_NOT_EQUAL_OUTPUT');});
test('zero active time still pays idle energy and ownership',()=>{const r=C.ownership({...own,hours:0});near(r.energyMonthly,10.08);near(r.rentalMonthly,0);a.equal(r.cashBreakevenMonths,null);});
test('matched-rate declaration adjusts rental hours',()=>{const r=C.ownership({...own,localRate:10,cloudRate:20});near(r.cloudHours,80);near(r.rentalMonthly,40);a.equal(r.hardwarePerformanceVerified,false);});
test('partial rate pair refuses',()=>a.throws(()=>C.ownership({...own,localRate:10})));
test('zero rate refuses a finite equal-work comparison',()=>a.throws(()=>C.ownership({...own,localRate:0,cloudRate:10})));
test('residual larger than capex refuses',()=>a.throws(()=>C.ownership({...own,residual:2000})));
test('impossible idle power refuses',()=>a.throws(()=>C.ownership({...own,idleWatts:500})));
test('same-work capacity constraint visible',()=>a.equal(C.ownership({...own,localRate:10,cloudRate:1}).capacityWarning,true));
test('rental minimum remains in same-work ownership calculation',()=>a.equal(C.ownership({...own,cloudMinimumHours:720}).rentalMonthly,360));
test('80 percent of requests only 16.7 percent of premium time',()=>{const r=C.route(rp);near(r.requestsMovedPct,80);near(r.premiumTimeReductionPct,100/6);a.equal(r.capacityReleased,null);});
test('failed smaller attempts and premium rescue both count',()=>{const x=copy(rp);x.classes[0].fallbackPercent=100;const r=C.route(x);near(r.requestsMovedPct,0);near(r.classes[0].fallbackCost,80/3600*3);near(r.classes[0].attemptCost,80/3600*.5);a.ok(r.recurringPerBatch>r.baselinePerBatch);});
test('initial qualification charged once across repeats',()=>{const r=C.route(rp);near(r.proposedTotal,r.recurringPerBatch*20+10);});
test('validation costs are explicit',()=>{const r=C.route({...rp,validationCostPerRequest:.5});near(r.recurringPerBatch-C.route(rp).recurringPerBatch,50);});
test('wrong workload shares refuse',()=>{const x=copy(rp);x.classes[0].share=79;a.throws(()=>C.route(x));});
test('premium terminal price mismatch refuses',()=>{const x=copy(rp);x.classes[1].targetHourly=.01;a.throws(()=>C.route(x));});
test('premium terminal cannot fallback to itself',()=>{const x=copy(rp);x.classes[1].fallbackPercent=2;a.throws(()=>C.route(x));});
test('proposal contains no execution or payment authority',()=>{const r=C.plan(data,{...p,offerIds:['ha-mi300x-1']});a.ok(Object.values(r.authority).every(x=>x===false));a.equal(r.status,'PROPOSAL');});
test('duplicate and unknown plans refuse',()=>{a.throws(()=>C.plan(data,{...p,offerIds:['unknown']}));a.throws(()=>C.plan(data,{...p,offerIds:['ha-mi300x-1','ha-mi300x-1']}));});
test('memory estimate includes entire resident parameters',()=>{const r=C.footprint({parametersB:30,bits:4,kvGB:4});near(r.estimatedGB,24.25);a.equal(r.status,'PLANNING_ESTIMATE_NOT_NATIVE_FIT');});
test('aperture whitelist excludes secret and device IDs',()=>{const r=C.aperture({schema:'aperture-support/1',host:'private',apiKey:'secret',nvidia:[{name:'GPU',totalBytes:123,uuid:'private'}],memory:{totalBytes:456},cpu:{model:'CPU'}});a.ok(!JSON.stringify(r).includes('secret'));a.ok(!JSON.stringify(r).includes('private'));a.equal(r.graphics[0].totalBytes,123);});
test('Aperture inventory requires exact supported schema',()=>a.throws(()=>C.aperture({schema:'other'})));
test('decision roundtrip verifies, tampering fails even if rechecksummed',()=>{const payload={schema:'second-run/compute-decision@1',version:C.VERSION,kind:'reuse',inputs:rp,result:C.route(rp)},e={schema:'second-run/sealed-compute-decision@1',payload,sha256:H.sha256(new TextEncoder().encode(C.canonical(payload)))};a.equal(verify(e).status,'RECOMPUTED');e.payload.result.baselineTotal+=10;e.sha256=H.sha256(new TextEncoder().encode(C.canonical(e.payload)));a.throws(()=>verify(e));});
test('existing vLLM fixtures preserve synthetic and successful unit distinction',()=>{const raw=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures.json'))).a,b=Buffer.from(JSON.stringify(raw)),r=H.normalize(raw,{sha256:H.sha256(b),bytes:b.length,record_index:0}),v=H.aggregate([r],{identity:{}});a.equal(v.synthetic,true);a.ok(v.unit.includes('completed'));});
test('Runpod offers declare the listed tier so the lowest list rate is not quietly the pricier one',()=>{const rp=data.offers.filter(o=>o.provider==='runpod');a.ok(rp.length>0);a.ok(rp.every(o=>o.tier==='Secure Cloud'));a.ok(data.sources.runpod.note.includes('Community Cloud'));C.validateCatalog(data);});
test('page review date and price schedules are generated from the catalogue, not hard-coded',()=>{const template=fs.readFileSync(path.join(__dirname,'../template.html'),'utf8'),page=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');a.ok(template.includes('<span id="reviewed-date">/*REVIEWED_DATE*/</span>'));a.ok(template.includes('<select id="as-of">/*AS_OF_OPTIONS*/</select>'));const options=page.match(/<select id="as-of">([\s\S]*?)<\/select>/)[1],values=[...options.matchAll(/value="(\d{4}-\d{2}-\d{2})"/g)].map(m=>m[1]);const expected=[data.reviewedOn,...[...new Set(data.offers.flatMap(o=>o.schedules.map(s=>s.effectiveOn)))].filter(d=>d>data.reviewedOn).sort()];a.deepEqual(values,expected);for(const v of values)C.priceAt(data.offers[0],v);a.ok(page.includes('<span id="reviewed-date">22 Sep 2026</span>'));});
test('release manifest names the engine version separately from the release version',()=>{const m=JSON.parse(fs.readFileSync(path.join(__dirname,'../MANIFEST.json'),'utf8'));a.equal(m.version,'0.3.0');a.equal(m.engineVersion,C.VERSION);a.ok(!m.files.some(f=>f.path.startsWith('ci/')));});
test('browser app never interpolates record concurrency into HTML without escaping',()=>{const app=fs.readFileSync(path.join(__dirname,'../app.js'),'utf8');a.ok(!/\$\{view\.primary_concurrency/.test(app));a.ok(!/\$\{x\.concurrency\}/.test(app));a.ok(!/'c'\+x\.concurrency/.test(app));a.ok(app.includes("esc(String(view.primary_concurrency??'—'))"));});
