(function(){'use strict';
const C=SecondRunCommunity,H=HA,$=id=>document.getElementById(id),esc=H.escape;
const raw=JSON.parse($('board-data').textContent);if(raw.schema!=='second-run/board@1'||C.hash(raw.payload)!==raw.sha256)throw Error('Board index checksum mismatch.');
const board=raw.payload,rows=board.records,cache=new Map(Object.entries(board.embedded||{})),selected=new Set(),STORE='second-run-community-decisions-v1';let active='results',draft=null,approved=null,lastDecision=null,saved=[];
try{const v=JSON.parse(localStorage.getItem(STORE)||'[]');if(Array.isArray(v))saved=v;const th=localStorage.getItem('second-run-community-theme');if(['light','dark'].includes(th))document.documentElement.dataset.theme=th;}catch{}
function notice(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(notice.timer);notice.timer=setTimeout(()=>$('toast').hidden=true,6000);}
function problem(e){$('error').textContent=e.message||String(e);$('error').hidden=false;}
function guarded(fn){return async(...a)=>{try{$('error').hidden=true;await fn(...a);}catch(e){problem(e);}};}
function download(name,text,type='application/json'){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);}
const pretty=x=>JSON.stringify(x,null,2)+'\n',fmt=x=>x===null||x===undefined?'—':Number(x).toLocaleString('en-US',{maximumFractionDigits:2}),usd=x=>x===null?'Unmeasured':'$'+Number(x).toLocaleString('en-US',{minimumFractionDigits:x<.01?5:2,maximumFractionDigits:x<.01?5:3});
function navigate(name,write=true){if(!['results','claims','contribute','hub','saved'].includes(name))return;active=name;for(const b of document.querySelectorAll('[data-tab]')){const on=b.dataset.tab===name;b.setAttribute('aria-selected',String(on));b.tabIndex=on?0:-1;$('panel-'+b.dataset.tab).hidden=!on;}if(name==='saved')renderSaved();if(write)history.replaceState(null,'','#'+name);}
for(const b of document.querySelectorAll('[data-tab]')){b.onclick=()=>navigate(b.dataset.tab);b.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const a=[...document.querySelectorAll('[data-tab]')],i=a.indexOf(b),j=e.key==='Home'?0:e.key==='End'?a.length-1:(i+(e.key==='ArrowRight'?1:-1)+a.length)%a.length;navigate(a[j].dataset.tab);a[j].focus();};}
addEventListener('hashchange',()=>navigate(location.hash.slice(1),false));$('theme').onclick=()=>{const t=document.documentElement.dataset.theme==='light'?'dark':'light';document.documentElement.dataset.theme=t;try{localStorage.setItem('second-run-community-theme',t);}catch{}};
$('hub-name').textContent=board.name;$('footer-hub').textContent=board.name;$('coverage').textContent=rows.length+' recorded paths · '+new Set(rows.map(r=>r.provider)).size+' execution surfaces';$('asof').textContent='Built '+board.built_at.slice(0,10)+' · '+raw.sha256.slice(0,12);$('saved-count').textContent=saved.length;
for(const [id,key] of [['price-link','prices'],['rating-link','rating'],['kit-link','kit'],['docs-link','docs']]){const link=board.links?.[key];if(link){if(/^(?:javascript:|data:|\/\/)/i.test(link))throw Error('Unsafe hub link');$(id).href=link;}else $(id).hidden=true;}
for(const w of [...new Set(rows.map(r=>r.workload))].sort()){const o=new Option(w,w);$('workload').add(o);}for(const [k,v] of Object.entries(C.METRICS))$('metric').add(new Option(v[0]+' ('+v[1]+')',k));
for(const r of rows){const label=r.title+' · '+r.workload;$('left').add(new Option(label,r.id));$('right').add(new Option(label,r.id));}
function render(){let rs=C.search(rows,$('search').value);if($('workload').value)rs=rs.filter(r=>r.workload===$('workload').value);if($('evidence').value)rs=rs.filter(r=>r.evidence===$('evidence').value);else rs=rs.filter(r=>!r.synthetic);const [key,dir]=$('sort').value.split(':');rs=C.sort(rs,key,dir);$('row-count').textContent=rs.length+' / '+rows.length;$('empty').hidden=rs.length>0;
 $('rows').innerHTML=rs.map(r=>`<tr><td><input type="checkbox" data-pick="${r.id}" ${selected.has(r.id)?'checked':''} aria-label="Select ${esc(r.title)}"></td><td><span class="path-title">${esc(r.title)}</span><span class="sub">${esc(r.provider)} · ${esc(r.hardware)}</span></td><td><span>${esc(r.workload)}</span><span class="sub">${esc(r.support||r.variant)}</span></td><td><span class="number">${fmt(r.accepted)} / ${fmt(r.attempted)}</span><span class="sub">${esc(r.unit)}</span></td><td><span class="number cost">${usd(r.cost_per_unit)}</span><span class="sub">${esc(r.cost_basis||'Unmeasured')} ${r.cost_per_unit!==null?'· per '+esc(r.unit):''}</span></td><td><span class="number">${fmt(r.ttft_p50)} / ${fmt(r.ttft_p99)} ms</span></td><td><span class="tag ${r.kind==='workload-report'?'pilot':''}">${esc(r.evidence)}</span><span class="sub">${fmt(r.repeats)} ${r.kind==='historical-finding'?'study observation':'recorded trial'+(r.repeats===1?'':'s')} · ${esc(r.observed_at.slice(0,10))}</span></td><td><button class="row-button" data-open="${r.id}">Inspect ↗</button></td></tr>`).join('');
 for(const b of document.querySelectorAll('[data-pick]'))b.onchange=()=>{if(b.checked){if(selected.size>=2){b.checked=false;notice('Choose two paths for a controlled comparison.');return;}selected.add(b.dataset.pick);}else selected.delete(b.dataset.pick);tray();};for(const b of document.querySelectorAll('[data-open]'))b.onclick=guarded(()=>inspect(b.dataset.open));tray();}
function tray(){$('tray').hidden=selected.size===0;$('selection').textContent=selected.size+' path'+(selected.size===1?'':'s')+' selected';}
for(const id of ['search','workload','evidence','sort'])$(id).addEventListener(id==='search'?'input':'change',render);$('reset').onclick=()=>{$('search').value='';$('workload').value='';$('evidence').value='';$('sort').value='observed_at:desc';render();};$('clear').onclick=()=>{selected.clear();render();};$('compare').onclick=()=>{const [a,b]=[...selected];$('left').value=a;$('right').value=b||'';rightChange();navigate('claims');};
async function packet(id){C.verify;if(cache.has(id)){const p=C.verify(cache.get(id));if(p.sha256!==id)throw Error('Packet identity mismatch.');return p;}const row=rows.find(r=>r.id===id);if(!row)throw Error('Record not listed by this hub.');const rel=(board.record_base||'community/records/')+id+'.json';if(location.protocol==='file:'){throw Error('For full evidence on disk, open the standalone record in '+(board.report_base||'community/r/')+id+'.html, or start the included local hub.');}const u=new URL(rel,location.href);if(u.origin!==location.origin)throw Error('Record path left this hub.');const response=await fetch(u,{redirect:'error',signal:AbortSignal.timeout(8000)});if(!response.ok)throw Error('Record is unavailable. Download the hub kit or retry this exact result.');const reader=response.body.getReader();let size=0,parts=[];try{for(;;){const t=await reader.read();if(t.done)break;size+=t.value.length;if(size>C.MAX_BYTES)throw Error('Record exceeds read limit.');parts.push(t.value);}}finally{await reader.cancel().catch(()=>{});}const bytes=new Uint8Array(size);let o=0;for(const p of parts){bytes.set(p,o);o+=p.length;}const p=C.verify(C.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes)));if(p.sha256!==id||H.canonical(C.summarize(p))!==H.canonical(row))throw Error('Result differs from the admitted board snapshot.');cache.set(id,p);return p;}
async function inspect(id){const p=await packet(id),r=C.summarize(p);$('detail-title').textContent=r.title;const content=`<span class="status">${esc(r.evidence)}</span><p>${esc(r.model)} · ${esc(r.hardware)}</p><div class="detail-stats"><div><strong>${fmt(r.accepted)} / ${fmt(r.attempted)}</strong><span>${esc(r.unit)}</span></div><div><strong>${usd(r.cost_per_unit)}</strong><span>per ${esc(r.unit)} · ${esc(r.cost_basis)}</span></div><div><strong>${fmt(r.ttft_p99)} ms</strong><span>p99 first token · ${fmt(r.repeats)} recorded trials</span></div></div><dl class="detail-meta"><dt>Workload</dt><dd>${esc(r.workload)}</dd><dt>Method / support</dt><dd>${esc(r.support||r.variant)}</dd><dt>Contributor</dt><dd>${esc(r.contributor)}</dd><dt>Funding</dt><dd>${esc(r.funding)}</dd><dt>Relationship</dt><dd>${esc(r.relationship)}</dd><dt>Observed</dt><dd>${esc(r.observed_at)}</dd><dt>Not measured here</dt><dd>${esc(r.not_measured.join(', '))}</dd></dl><h3>Limits that travel with the number</h3><ul class="detail-limits">${r.limitations.map(x=>'<li>'+esc(x)+'</li>').join('')}</ul>${r.relation?'<p class="small">'+esc(r.relation.kind)+' of '+esc(r.relation.target)+': '+esc(r.relation.note)+'</p>':''}<details><summary>Source records and exact identity</summary><ul>${r.sources.map(s=>'<li>'+esc(s.label)+(s.url?' · <a href="'+esc(s.url)+'" target="_blank" rel="noopener noreferrer">Source ↗</a>':'')+'<p class="hash">'+esc(s.revision||'Revision not supplied')+'<br>'+esc(s.sha256||'Source byte identity not supplied')+'</p></li>').join('')}</ul><p class="hash">Packet '+esc(id)+'<br>Underlying evidence '+esc(r.fingerprint)+'</p><p class="small">Recomputation checks the supplied calculation and its bindings. It does not authenticate the producer or independently rerun hardware.</p></details><div class="actions"><button class="primary" id="detail-check">Check a claim</button><button id="detail-download">Download evidence</button><a class="button" href="${esc((board.report_base||'community/r/')+id+'.html')}" target="_blank" rel="noopener">Keep standalone result ↗</a><button id="detail-replicate">Prepare replication plan</button></div>`;
 $('detail-body').innerHTML=content;$('detail').showModal();$('detail-check').onclick=()=>{$('left').value=id;$('detail').close();navigate('claims');};$('detail-download').onclick=()=>download('result-'+id.slice(0,12)+'.json',pretty(p));$('detail-replicate').onclick=()=>replication(p);}
$('detail-close').onclick=()=>$('detail').close();$('detail').addEventListener('click',e=>{if(e.target===$('detail'))$('detail').close();});
function rightChange(){$('threshold-label').hidden=!!$('right').value;}$('right').onchange=rightChange;
let claimEpoch=0;
function invalidateClaim(){claimEpoch++;lastDecision=null;$('check-output').textContent='Choose the evidence and check this claim. Previous answers do not apply to changed inputs.';}
for(const id of ['wording','left','right','metric','operator','threshold','claim-scope'])$(id).addEventListener('input',invalidateClaim);
function claimInput(){return {wording:$('wording').value.trim()||'Selected comparison',left:$('left').value,right:$('right').value||null,metric:$('metric').value,operator:$('operator').value,threshold:Number($('threshold').value),scope:$('claim-scope').value};}
function answer(d){lastDecision=d;const x=d.payload.result;const names={SUPPORTED_IN_SELECTED_RECORDS:'Supported by these observations',CONTRADICTED_IN_SELECTED_RECORDS:'Contradicted by these observations',SCOPE_LIMIT:'The general claim exceeds this evidence',EVIDENCE_GAP:'A missing measurement prevents this comparison'};$('check-output').innerHTML=`<span class="status">${esc(x.status.replaceAll('_',' '))}</span><h3>${esc(names[x.status])}</h3><p>${esc(d.payload.claim.wording)}</p><div class="answer-values"><div><span>Selected path</span><strong>${x.units==='USD'?usd(x.left_value):fmt(x.left_value)} ${x.units==='USD'?'':esc(x.units)}</strong></div><div><span>Comparison</span><strong>${x.units==='USD'?usd(x.right_value):fmt(x.right_value)} ${x.units==='USD'?'':esc(x.units)}</strong></div></div><ul>${[...x.issues,...x.limits].map(t=>'<li>'+esc(t)+'</li>').join('')}</ul><p>${esc(x.next)}</p><div class="actions"><button class="primary" id="save-check">Save this decision</button><button id="export-check">Export with evidence</button></div><p class="hash">${esc(d.sha256)}</p>`;$('save-check').onclick=()=>save(d);$('export-check').onclick=()=>download('second-run-decision-'+d.sha256.slice(0,12)+'.json',pretty(d));}
$('check').onclick=guarded(async()=>{invalidateClaim();const epoch=claimEpoch,c=claimInput();$('check').disabled=true;$('check-output').textContent='Checking the selected evidence…';try{const ps=[await packet(c.left),...(c.right?[await packet(c.right)]:[])];if(epoch===claimEpoch)answer(C.decision(ps,c));}finally{$('check').disabled=false;}});
for(const b of document.querySelectorAll('[data-example]'))b.onclick=()=>{const name=b.dataset.example;let a,z;if(name==='method'){a=rows.find(r=>r.task.toLowerCase().includes('intervals')&&r.support.toLowerCase().includes('generic'));z=rows.find(r=>r.task.toLowerCase().includes('intervals')&&r.support.toLowerCase().includes('solo')&&r.model.toLowerCase().includes('haiku'));$('metric').value='ratio';$('operator').value='greater';$('wording').value='The frozen review method found more of the five planted issues than this model found unaided.';}else{a=rows.find(r=>r.kind==='workload-report'&&r.provider==='Hot Aisle'&&r.variant.toLowerCase().includes('default'));z=rows.find(r=>r.kind==='workload-report'&&r.provider==='DigitalOcean');$('metric').value=name==='tail'?'ttft_p99':'cost_per_unit';$('operator').value='less';if(name==='tail'){[a,z]=[z,a];$('wording').value='The DigitalOcean H100 had lower p99 first-token latency on this recorded workload.';}else $('wording').value='Hot Aisle had a lower modeled cost per accepted request for this recorded run and allocation scenario.';}$('claim-scope').value='observed';if(a)$('left').value=a.id;if(z)$('right').value=z.id;rightChange();invalidateClaim();navigate('claims');};
function save(d){C.verifyDecision(d);if(saved.some(v=>v.sha256===d.sha256)){notice('Already saved.');return;}if(saved.length>=30){notice('This browser has 30 retained decisions. Export them before clearing space.');return;}const next=[...saved,d];try{localStorage.setItem(STORE,JSON.stringify(next));saved=next;$('saved-count').textContent=saved.length;notice('Saved with the complete evidence. Export keeps it outside this browser.');}catch{notice('Browser storage is full or unavailable. Use Export with evidence to keep this decision.');}}
function renderSaved(){$('saved-list').innerHTML=saved.length?saved.map((d,i)=>{let valid=true;try{C.verifyDecision(d);}catch{valid=false;}return `<article class="saved-card"><h3>${esc(d.payload?.claim?.wording||'Unrecognized retained record')}</h3><p>${valid?esc(d.payload.result.status.replaceAll('_',' ')):'Needs re-verification · original retained'}</p><p class="hash">${esc(String(d.sha256||'Unknown identity'))}</p><div class="actions"><button data-export="${i}">Export original</button>${valid?'<button data-review="'+i+'">Review</button>':''}<button data-remove="${i}">Remove from this browser</button></div></article>`;}).join(''):'<div class="empty">Check a claim and save the decision. Its evidence stays with it.</div>';for(const b of document.querySelectorAll('[data-export]'))b.onclick=()=>download('retained-decision.json',pretty(saved[Number(b.dataset.export)]));for(const b of document.querySelectorAll('[data-review]'))b.onclick=()=>{answer(saved[Number(b.dataset.review)]);navigate('claims');};for(const b of document.querySelectorAll('[data-remove]'))b.onclick=()=>{if(!confirm('Remove this local decision? Export it first to keep another copy.'))return;const next=saved.filter((_,i)=>i!==Number(b.dataset.remove));try{localStorage.setItem(STORE,JSON.stringify(next));saved=next;$('saved-count').textContent=saved.length;renderSaved();}catch(e){problem(e);}};}
$('decision-file').onchange=guarded(async e=>{const f=e.target.files[0];if(!f)return;if(f.size>C.MAX_BYTES*2)throw Error('Decision file exceeds limit.');const d=C.verifyDecision(C.parse(await f.text()));answer(d);navigate('claims');notice('Recomputed against the evidence inside this decision.');});
function baseMeta(r){return {title:r.identity?.model||'My workload result',provider:r.cost?.provider||'To declare',hardware:'To declare',workload:r.identity?.workload||'To declare',variant:'Supplied workload report',observed_at:new Date().toISOString(),contributor:'To declare',funding:'To declare',relationship:'To declare',limitations:['This contribution was prepared from supplied evidence. Independent execution and invoice verification are not established.'],sources:[{label:'Supplied sealed workload report',url:'',sha256:null,revision:null}],relation:null};}
function setDraft(p){draft=C.verify(p);approved=null;$('consent').checked=false;$('export-packet').disabled=true;$('submit-instructions').hidden=true;const m=draft.payload.metadata;$('draft-form').hidden=false;$('draft-title').value=m.title;$('draft-author').value=m.contributor;$('draft-provider').value=m.provider;$('draft-funding').value=m.funding;$('draft-relationship').value=m.relationship;$('draft-limit').value='';$('public-preview').textContent='Review the labels, then build the exact preview. Model identities, measurement data, cost basis and source commitments remain in the public packet.';}
$('import').onchange=guarded(async e=>{const f=e.target.files[0];if(!f)return;if(f.size>C.MAX_BYTES)throw Error('File exceeds 16 MiB.');const v=C.parse(await f.text());if(v.schema==='second-run/result-packet@1')setDraft(v);else if(v.schema==='hot-aisle/sealed-report@1'){const r=H.recompute(v);if(r.sides.length!==1)throw Error('Export one configuration per contribution.');setDraft(C.fromReport(v,baseMeta({...r.sides[0].aggregate,cost:r.sides[0].cost}),'supplied-total'));}else throw Error('Use a community result packet or a one-configuration sealed workload report.');$('import-status').textContent='Loaded locally. Nothing was uploaded.';});
function replication(p){const r=C.summarize(p),payload={schema:'second-run/replication-plan@1',target:p.sha256,source_fingerprint:r.fingerprint,workload:r.task,model:r.model,method:r.support,requirements:r.limitations,acceptance_source:r.sources,authority:{execute:false,provision:false,publish:false},instructions:['Freeze the task and acceptance rule before collecting new outcomes.','Use a separate authorized environment and keep all attempts, including failures.','Collect new source-bound evidence; copying this packet is not replication.','Declare support, funding, operator independence and the cost basis.','Package the new result and link it to this target with relation kind replication.']};download('replication-plan-'+p.sha256.slice(0,12)+'.json',pretty({payload,sha256:C.hash(payload)}));notice('Downloaded a bounded replication brief. No work has been dispatched.');}
$('use-selected').onclick=guarded(async()=>{const id=[...selected][0]||$('left').value;if(!id)throw Error('Select a result first.');replication(await packet(id));});
function invalidate(){approved=null;$('consent').checked=false;$('export-packet').disabled=true;$('submit-instructions').hidden=true;}
for(const id of ['draft-title','draft-author','draft-provider','draft-funding','draft-relationship','draft-limit'])$(id).oninput=invalidate;
$('preview').onclick=guarded(()=>{if(!draft)throw Error('Choose evidence first.');const m=structuredClone(draft.payload.metadata);m.title=$('draft-title').value.trim();m.provider=$('draft-provider').value.trim();m.contributor=$('draft-author').value.trim();m.funding=$('draft-funding').value.trim();m.relationship=$('draft-relationship').value.trim();if($('draft-limit').value.trim())m.limitations.push($('draft-limit').value.trim());for(const v of [m.contributor,m.funding,m.relationship])if(/^(to declare|unknown|tbd|todo)$/i.test(v))throw Error('Complete contributor, funding and relationship before publication.');const p=C.make(draft.payload.kind,draft.payload.body,m),flags=C.privacy(p);if(flags.length)throw Error('Public packet contains '+flags.join(', ')+'. Redact or recreate the source safely before publishing.');approved=p;$('public-preview').textContent=pretty({sha256:p.sha256,bytes:new TextEncoder().encode(JSON.stringify(p)).length,metadata:p.payload.metadata,result:C.summarize(p),disclosure:'The downloaded JSON includes the normalized evidence needed to recompute this result. Review the exact file before submitting.'});$('consent').checked=false;$('export-packet').disabled=true;});
$('consent').onchange=()=>{$('export-packet').disabled=!approved||!$('consent').checked;};$('export-packet').onclick=guarded(()=>{if(!approved||!$('consent').checked)throw Error('Review and approve the exact public packet.');const name='contribution-'+approved.sha256.slice(0,12)+'.json';download(name,pretty(approved));$('submit-command').textContent='node community/cli.cjs submit '+name+' \\\n  --repository '+(board.submission_repository||'OWNER/REPO')+' \\\n  --approve-public '+approved.sha256;$('submit-instructions').hidden=false;});
render();renderSaved();navigate(location.hash.slice(1)||'results',false);
})();
