/* Second Run community records. MIT. Every measured workload finding delegates to HA. */
(function(root,factory){const H=typeof module==='object'&&module.exports?require('./workload-engine.cjs'):root.HA;const api=factory(H);if(typeof module==='object'&&module.exports)module.exports=api;root.SecondRunCommunity=api;})(typeof globalThis==='undefined'?this:globalThis,function(H){
'use strict';
const VERSION='0.1.0', MAX_BYTES=16*1024*1024, encoder=new TextEncoder();
const fail=m=>{throw new Error(m)}, obj=x=>x!==null&&typeof x==='object'&&!Array.isArray(x);
const clone=x=>JSON.parse(JSON.stringify(x));
function text(s,label,max=500){if(typeof s!=='string'||!s.trim()||s.length>max||/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(s))fail(label+' needs bounded plain text.');return s;}
function n(x,label,min=0){if(typeof x!=='number'||!Number.isFinite(x)||x<min||x>Number.MAX_SAFE_INTEGER)fail(label+' must be a finite nonnegative number.');return x;}
function integer(x,label){n(x,label);if(!Number.isSafeInteger(x))fail(label+' must be an integer.');return x;}
function keys(o,allowed,label){if(!obj(o))fail(label+' must be an object.');for(const k of Object.keys(o))if(!allowed.includes(k))fail(label+' has unsupported field '+k);}
function date(s){text(s,'Date',40);if(!/^\d{4}-\d\d-\d\d(?:T[^\s]+)?$/.test(s)||!Number.isFinite(Date.parse(s))||new Date(s.slice(0,10)).toISOString().slice(0,10)!==s.slice(0,10))fail('Use an ISO date.');return s;}
function hash(x){return H.sha256(encoder.encode(H.canonical(x)));}
function hex(s){if(typeof s!=='string'||!/^[a-f0-9]{64}$/.test(s))fail('Expected a SHA-256 identity.');return s;}
function sourceURL(s){if(s==='')return s;text(s,'Source URL',1200);let u;try{u=new URL(s);}catch{fail('Source URL must be HTTPS.');}if(u.protocol!=='https:'||u.username||u.password)fail('Source URL must be HTTPS without credentials.');return s;}
function boundedTree(value,depth=0){if(depth>30)fail('Record nesting exceeds the limit.');if(typeof value==='number')n(value,'Numeric field',-Number.MAX_SAFE_INTEGER);if(typeof value==='string'&&value.length>8*1024*1024)fail('Text field exceeds limit.');if(Array.isArray(value)){if(value.length>250000)fail('Too many array entries.');for(const x of value)boundedTree(x,depth+1);}else if(obj(value)){for(const [k,v] of Object.entries(value)){if(['__proto__','prototype','constructor'].includes(k))fail('Unsafe object key.');boundedTree(v,depth+1);}}else if(value===undefined)fail('Undefined fields are unsupported.');}
function parse(s){if(typeof s!=='string'||encoder.encode(s).length>MAX_BYTES)fail('Record exceeds 16 MiB.');const v=JSON.parse(s);boundedTree(v);return v;}
function privacy(p){const s=JSON.stringify(p);const flags=[];for(const [name,re] of [['credential',/\b(?:gh[pousr]_[A-Za-z0-9]{15,}|sk-[A-Za-z0-9_-]{20,}|Bearer\s+[A-Za-z0-9_.-]{12,}|-----BEGIN [A-Z ]*PRIVATE KEY-----)/],['local path',/(?:[A-Za-z]:\\\\(?:Users|Projects|Scratch)\\\\|\/home\/[^/\s"\\]+\/|\/Users\/[^/\s"\\]+\/)/],['email',/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i]])if(re.test(s))flags.push(name);return flags;}
function metadata(m){keys(m,['title','provider','hardware','workload','variant','observed_at','contributor','funding','relationship','limitations','sources','relation'],'Metadata');for(const k of ['title','provider','hardware','workload','variant','contributor','funding','relationship'])text(m[k],k,k==='title'?180:500);date(m.observed_at);if(!Array.isArray(m.limitations)||m.limitations.length>20)fail('Provide a limitations list.');m.limitations.forEach(x=>text(x,'Limitation',1500));if(!Array.isArray(m.sources)||!m.sources.length||m.sources.length>20)fail('Provide source references.');for(const s of m.sources){keys(s,['label','url','sha256','revision'],'Source');text(s.label,'Source label');sourceURL(s.url);if(s.sha256!==null)hex(s.sha256);if(s.revision!==null)text(s.revision,'Source revision',100);}if(m.relation!==null){keys(m.relation,['kind','target','note'],'Relation');if(!['replication','correction','transfer','supersedes'].includes(m.relation.kind))fail('Unknown relation.');hex(m.relation.target);text(m.relation.note,'Relation note',1500);}return m;}
function cleanReport(envelope){const p=H.recompute(envelope);const sides=p.sides.map(s=>{const runs=s.normalized.map(H.restoreRun),settings={identity:clone(s.settings.identity||{}),ttft:s.settings.ttft??null,e2e:s.settings.e2e??null,queue:s.settings.queue===true,quality:s.settings.quality===true},aggregate=H.aggregate(runs,settings),price={provider:s.price.provider||'',gpus:s.price.gpus,rate:s.price.rate,extra:s.price.extra??0,total:s.price.total??null,source:s.price.source||'',period:s.price.period||'',quote:s.price.quote||''};return {label:s.label||'Measured configuration',normalized:runs,settings,price,aggregate,cost:H.costing(aggregate,price)};});const payload={schema:'hot-aisle/workload-report@2',version:H.VERSION,synthetic:sides.some(s=>s.aggregate.synthetic),sides,comparison:sides.length===2?H.compare(sides[0].aggregate,sides[0].cost,sides[1].aggregate,sides[1].cost):null};return {schema:'hot-aisle/sealed-report@1',payload,sha256:hash(payload)};}
function make(kind,body,meta){const payload={schema:'second-run/result@1',kind,metadata:metadata(clone(meta)),body:clone(body)};boundedTree(payload);const packet={schema:'second-run/result-packet@1',payload,sha256:hash(payload)};verify(packet);return packet;}
function fromReport(envelope,meta,costBasis='modeled'){const report=cleanReport(envelope);return make('workload-report',{report,cost_basis:costBasis},meta);}
function historical(body){keys(body,['task','model','effort','support','cost_basis','unit','verifier','trials','source_sha256','claim_basis'],'Historical record');for(const k of ['task','model','effort','support','cost_basis','unit','verifier','claim_basis'])text(body[k],k,1500);hex(body.source_sha256);if(!['shadow-estimated','upper-bound','source-reported','unknown'].includes(body.cost_basis))fail('Historical costs require their declared evidence basis.');if(!Array.isArray(body.trials)||!body.trials.length||body.trials.length>2000)fail('Historical trials missing or excessive.');const seen=new Set();for(const t of body.trials){keys(t,['line','sha256','outcome','cost_usd','source_cost_usd','latency_ms','input_tokens','output_tokens'],'Trial');integer(t.line,'Source line');hex(t.sha256);if(seen.has(t.line))fail('Duplicate source line.');seen.add(t.line);if(t.source_cost_usd!==undefined&&t.source_cost_usd!==null)n(t.source_cost_usd,'Source-declared cost');if(!['pass','fail','error','partial','unknown'].includes(t.outcome))fail('Unknown outcome.');for(const k of ['cost_usd','latency_ms','input_tokens','output_tokens'])if(t[k]!==null)n(t[k],k);}return body;}
function finding(body){keys(body,['model','support','task','measure','value','maximum','cost_usd','cost_basis','source_sha256','source_excerpt','study_status'],'Finding');for(const k of ['model','support','task','measure','cost_basis','source_excerpt','study_status'])text(body[k],k,k==='source_excerpt'?12000:500);hex(body.source_sha256);n(body.value,'Finding value');n(body.maximum,'Finding maximum',1);if(body.value>body.maximum)fail('Finding exceeds maximum.');if(body.cost_usd!==null)n(body.cost_usd,'Finding cost');if(!['upper-bound','shadow-estimated','unknown'].includes(body.cost_basis))fail('Historical finding has an unsupported cost basis.');return body;}
function verify(packet){keys(packet,['schema','payload','sha256'],'Packet');if(packet.schema!=='second-run/result-packet@1')fail('Use a Second Run result packet.');hex(packet.sha256);if(hash(packet.payload)!==packet.sha256)fail('Packet checksum mismatch.');const p=packet.payload;keys(p,['schema','kind','metadata','body'],'Result');if(p.schema!=='second-run/result@1')fail('Unsupported result version.');metadata(p.metadata);boundedTree(p.body);if(p.kind==='workload-report'){keys(p.body,['report','cost_basis'],'Workload body');if(!['modeled','reported-invoice','supplied-total'].includes(p.body.cost_basis))fail('Unsupported workload cost basis.');const r=H.recompute(p.body.report);if(r.sides.length!==1)fail('Publish one independently inspectable configuration per packet.');}else if(p.kind==='tierbench-trials')historical(p.body);else if(p.kind==='historical-finding')finding(p.body);else fail('Unsupported result kind.');if(encoder.encode(H.canonical(packet)).length>MAX_BYTES)fail('Packet exceeds 16 MiB.');return packet;}
function summarize(packet){verify(packet);const p=packet.payload,m=p.metadata,b=p.body;let row={id:packet.sha256,...clone(m),kind:p.kind,model:null,support:null,task:null,unit:null,attempted:null,accepted:null,completed:null,cost:null,cost_per_unit:null,cost_basis:null,latency_ms:null,ttft_p50:null,ttft_p95:null,ttft_p99:null,e2e_p95:null,repeats:null,synthetic:false,evidence:'source-reported',fingerprint:null,group:null,ratio:null,not_measured:['uptime','live availability','autonomy','human intervention','energy'],holds:[]};
 if(p.kind==='workload-report'){const s=H.recompute(b.report).sides[0],a=s.aggregate,c=s.cost;row={...row,model:a.identity.model,support:m.variant,task:a.identity.workload||m.workload,unit:a.unit,attempted:a.attempted,accepted:a.accepted,completed:a.completed,cost:c.total,cost_per_unit:c.costPer1000===null?null:c.costPer1000/1000,cost_basis:b.cost_basis,latency_ms:a.metrics.e2e.p50,ttft_p50:a.metrics.ttft.p50,ttft_p95:a.metrics.ttft.p95,ttft_p99:a.metrics.ttft.p99,e2e_p95:a.metrics.e2e.p95,repeats:a.runs,synthetic:a.synthetic,evidence:a.synthetic?'synthetic':'source-bound execution',ratio:a.qualifiedFraction,holds:a.holds};row.fingerprint=hash(a.sources.map(s=>[s.sha256,s.record_index]).sort((a,b)=>H.canonical(a).localeCompare(H.canonical(b))));row.group=hash({workload:a.identity.workload,model:a.identity.model,revision:a.identity.revision,precision:a.identity.precision,tokenizer:a.identity.tokenizer,load:a.identity.load,cache:a.identity.cache,gates:a.gates,criterion:a.criterion,unit:a.unit});if(!a.identity.workload||!a.identity.revision||!a.identity.load)row.group=null;}
 else if(p.kind==='tierbench-trials'){const ts=b.trials,lat=ts.map(t=>t.latency_ms).filter(x=>x!==null),costKnown=ts.every(t=>t.cost_usd!==null),passed=ts.filter(t=>t.outcome==='pass').length;row={...row,model:b.model,support:b.support,task:b.task,unit:b.unit,attempted:ts.length,accepted:passed,completed:ts.filter(t=>['pass','fail'].includes(t.outcome)).length,repeats:ts.length,cost:costKnown?ts.reduce((s,t)=>s+t.cost_usd,0):null,cost_basis:b.cost_basis,latency_ms:lat.length===ts.length?H.quantile(lat,.5):null,ratio:passed/ts.length,evidence:'historical trial summary',fingerprint:hash([b.source_sha256,ts.map(t=>t.line)]),group:null};row.cost_per_unit=row.cost!==null&&passed?row.cost/passed:null;}
 else{row={...row,model:b.model,support:b.support,task:b.task,unit:b.measure,attempted:b.maximum,accepted:b.value,completed:null,repeats:1,cost:b.cost_usd,cost_basis:b.cost_basis,evidence:'historical finding',ratio:b.value/b.maximum,fingerprint:hash([b.source_sha256,b.model,b.task,b.support]),group:hash({source:b.source_sha256,task:b.task,measure:b.measure})};}
 return row;}
function compare(left,right){const a=summarize(left),b=summarize(right),issues=[];if(a.synthetic||b.synthetic)issues.push('Synthetic data is a software demonstration.');if(!a.group||a.group!==b.group)issues.push('Workload, model identity or acceptance conditions do not establish a controlled comparison.');if(a.fingerprint===b.fingerprint)issues.push('These packets reuse the same underlying evidence.');if(a.cost_basis!==b.cost_basis)issues.push('Cost bases differ.');if(a.holds.length||b.holds.length)issues.push('An acceptance gate remains held.');if(a.cost_per_unit===null||b.cost_per_unit===null)issues.push('Cost per accepted outcome is missing.');const eligible=!issues.length;return {status:eligible?'SAME_CONTRACT_OBSERVATION':'DESCRIPTIVE_ONLY',issues,left:a.id,right:b.id,savings:eligible&&b.cost_per_unit>0?1-a.cost_per_unit/b.cost_per_unit:null,independence:'Not established by hashes or contributor names.',scope:'Observed configurations only; no causal hardware ranking or production recommendation.'};}
const METRICS={cost_per_unit:['Cost per accepted outcome','USD'],cost:['Recorded run cost','USD'],latency_ms:['Median completion latency','ms'],ttft_p50:['Median first token','ms'],ttft_p95:['p95 first token','ms'],ttft_p99:['p99 first token','ms'],e2e_p95:['p95 completion','ms'],accepted:['Accepted outcomes','count'],ratio:['Accepted / attempted','fraction'],repeats:['Recorded trials','count']};
function checkClaim(packets,claim){keys(claim,['left','right','metric','operator','threshold','scope','wording'],'Claim');if(!METRICS[claim.metric])fail('Choose a supported measurement.');if(!['less','greater','at_most','at_least'].includes(claim.operator))fail('Unsupported comparison.');if(!['observed','general'].includes(claim.scope))fail('Choose observed configurations or a general marketing claim.');text(claim.wording||'Comparison','Claim wording',2000);const l=packets.find(p=>p.sha256===claim.left),r=claim.right?packets.find(p=>p.sha256===claim.right):null;if(!l||claim.right&&!r)fail('Select retained results.');const a=summarize(l),b=r?summarize(r):null,issues=[];if(a.synthetic||b?.synthetic)issues.push('Synthetic results cannot establish a real performance claim.');if(b){const c=compare(l,r);issues.push(...c.issues.filter(x=>claim.metric.includes('cost')||!x.includes('Cost')));}const v=a[claim.metric],ref=b?b[claim.metric]:n(claim.threshold,'Threshold');if(v===null||ref===null)issues.push('The selected metric is unmeasured.');const test=issues.length?null:{less:v<ref,greater:v>ref,at_most:v<=ref,at_least:v>=ref}[claim.operator];const status=issues.length?'EVIDENCE_GAP':claim.scope==='general'?'SCOPE_LIMIT':test?'SUPPORTED_IN_SELECTED_RECORDS':'CONTRADICTED_IN_SELECTED_RECORDS';return {schema:'second-run/claim-check@1',claim:clone(claim),status,left_value:v,right_value:ref,selected_observations_match:test,units:METRICS[claim.metric][1],issues,limits:claim.scope==='general'?['Selected runs do not establish a universal provider, model or hardware claim.']:['One retained observation is not a repeatability or independence guarantee.'],record_ids:[a.id,...(b?[b.id]:[])],next:issues.length?'Capture the missing measurement under the same contract, or select compatible evidence.':claim.scope==='general'?'Freeze a representative prospective cohort and repeat across operators, configurations and dates.':'Retain this check with the source records; recheck after relevant changes.'};}
function decision(packets,claim,created=new Date().toISOString()){const result=checkClaim(packets,claim),selected=result.record_ids.map(id=>packets.find(p=>p.sha256===id));const payload={schema:'second-run/community-decision@1',created_at:date(created),claim:clone(claim),result,records:selected};return {schema:'second-run/sealed-community-decision@1',payload,sha256:hash(payload)};}
function verifyDecision(d){if(d?.schema!=='second-run/sealed-community-decision@1'||hash(d.payload)!==d.sha256)fail('Decision checksum mismatch.');const p=d.payload;const fresh=decision(p.records,p.claim,p.created_at);if(H.canonical(fresh)!==H.canonical(d))fail('Decision differs from its retained evidence.');return d;}
function search(rows,q){const words=q.toLowerCase().split(/\s+/).filter(Boolean);return rows.filter(r=>words.every(w=>[r.title,r.model,r.provider,r.hardware,r.workload,r.variant,r.task,r.support].join(' ').toLowerCase().includes(w)));}
function sort(rows,key,direction='asc'){if(![...Object.keys(METRICS),'title','observed_at','provider','model'].includes(key))fail('Unsupported sort.');return [...rows].sort((a,b)=>{const av=a[key],bv=b[key];if(av===null||av===undefined)return bv===null||bv===undefined?a.id.localeCompare(b.id):1;if(bv===null||bv===undefined)return -1;const d=typeof av==='number'?av-bv:String(av).localeCompare(String(bv));return (direction==='desc'?-d:d)||a.id.localeCompare(b.id);});}
return {VERSION,MAX_BYTES,METRICS,parse,hash,verify,make,fromReport,cleanReport,summarize,compare,checkClaim,decision,verifyDecision,privacy,metadata,search,sort,sourceURL};
});
