#!/usr/bin/env node
/* Explicit source acquisition followed by offline conversion. Does not run models. */
'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto');
const C=require('./core.cjs'),H=require('./workload-engine.cjs'),U=require('./cli.cjs');
const ROOT=__dirname,AX='5276ef9f090673a4a514a692a2799b402e0ebb07',TB='f6137258ce3f0462ccbf09c6adee01454332f7ec';
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),sources=[];
const acquire=process.argv.includes('--acquire'),rawDir=path.resolve(process.env.SECOND_RUN_SEED_CACHE||path.join(ROOT,'seed-cache'));
fs.mkdirSync(rawDir,{recursive:true});
function source(repo,ref,p){const key=sha(Buffer.from(repo+'@'+ref+':'+p)),file=path.join(rawDir,key+'.raw');
 if(!fs.existsSync(file)){if(!acquire)throw Error('Missing retained source '+p+'; explicitly --acquire or supply the source cache.');
 const response=cp.execFileSync('gh',['api',`repos/${repo}/contents/${p}?ref=${ref}`],{encoding:'utf8',maxBuffer:16*1024*1024,timeout:45000,windowsHide:true});const doc=JSON.parse(response);if(doc.encoding!=='base64'||!doc.content)throw Error('Unsupported source '+p);const b=Buffer.from(doc.content.replace(/\s/g,''),'base64');if(doc.sha!==shaGit(b))throw Error('Git blob mismatch '+p);fs.writeFileSync(file,b,{flag:'wx'});}
 const bytes=fs.readFileSync(file);const mf=path.join(ROOT,'data/source-manifest.json');if(fs.existsSync(mf)){const prior=JSON.parse(fs.readFileSync(mf,'utf8')).sources.find(s=>s.cache_key===key);if(prior&&prior.sha256!==sha(bytes))throw Error('Retained source bytes changed: '+p);}const s={label:p,url:`https://github.com/${repo}/blob/${ref}/${p}`,sha256:sha(bytes),revision:ref};sources.push({...s,cache_key:key,bytes:bytes.length});return {bytes,text:bytes.toString('utf8'),source:s,json:()=>JSON.parse(bytes.toString('utf8'))};}
function shaGit(b){return crypto.createHash('sha1').update(Buffer.concat([Buffer.from('blob '+b.length+'\0'),b])).digest('hex');}
function meta(title,provider,hardware,workload,variant,refs,limitations,date='2026-09-24'){return {title,provider,hardware,workload,variant,observed_at:date,contributor:'Second Run',funding:provider==='DigitalOcean'?'Operator-funded. Published cost is modeled at list; invoice reconciliation remains open.':provider==='Hot Aisle'?'Hot Aisle supplied $200 credit. Modeled costs use undiscounted list rates.':'Original TierBench experiments; accounting basis preserved per record.',relationship:provider==='Hot Aisle'?'Evaluator received provider compute credit and is proposing paid engineering work.':'Original experiment operator; no independent replication asserted.',limitations,sources:refs,relation:null};}
const packets=[];
for(const arm of ['a-t0','a-t1','n-t0']){
 const prefix='hot-aisle/campaign/results/run3-scored-'+arm+'/';const d=source('BigBirdReturns/axm-tools',AX,prefix+'detailed.json'),e=source('BigBirdReturns/axm-tools',AX,prefix+'grade/evaluation.json'),t=source('BigBirdReturns/axm-tools',AX,prefix+'ledger-times.json'),env=source('BigBirdReturns/axm-tools',AX,prefix+'env.json'),cl=source('BigBirdReturns/axm-tools',AX,prefix+'closure.json');
 let run=H.normalize(d.json(),{sha256:d.source.sha256,bytes:d.bytes.length,record_index:0});run=H.attachQuality(run,e.json());const times=t.json(),closure=cl.json(),amd=arm.startsWith('a'),rate=amd?2.99:4.41;
 let seconds,note;if(arm==='n-t0'){seconds=(Date.parse(closure.t_released)-Date.parse(closure.t_request))/1000;note='Recorded request-to-provider-release interval at list; invoice not reconciled.';}else{seconds=(Date.parse(times.t_script_end)-Date.parse(times.t_script_start))/1000+(arm==='a-t0'?122:0);note=arm==='a-t0'?'Dedicated-equivalent scenario: this arm script interval plus 122 s observed seat provisioning. The actual seat was shared; this is not an invoice or an actual dedicated rental.':'Own-arm script interval at list on the shared seat. Setup/idle overhead is not allocated to this row; compare cost scopes explicitly.';}
 const settings={identity:{},quality:true,ttft:1000,e2e:60000,queue:true},aggregate=H.aggregate([run],settings),price={provider:amd?'Hot Aisle':'DigitalOcean',gpus:1,rate,extra:0,total:seconds*rate/3600,source:note,period:'2026-09-24 campaign observation',quote:'Modeled cost, before credits'};
 const payload={schema:'hot-aisle/workload-report@2',version:H.VERSION,synthetic:false,sides:[{label:arm,normalized:[run],settings,price,aggregate,cost:H.costing(aggregate,price)}],comparison:null};
 const report={schema:'hot-aisle/sealed-report@1',payload,sha256:C.hash(payload)};const variant=arm==='a-t1'?'Forced ROCM_AITER_FA':'Default attention selection';const m=meta((amd?'MI300X':'H100')+' · graded coding · '+variant,price.provider,amd?'1× MI300X 192 GB':'1× H100 80 GB','Graded coding under Azure CODE arrival timing',variant,[d.source,e.source,t.source,env.source,cl.source],[note,'One scored run per configuration; 8,622 requests cycle 542 distinct tasks.','Historical arrival timing replayed for one hour, not a live customer workload.','Accepted means base+plus tests and arrival-aware 1 s first-token / 60 s completion deadlines.','Latency percentiles describe completed requests. Correctness and deadline acceptance are separate fields.','Operator-produced and source-bound; independent execution and invoice authenticity are not established.','Performance cannot be transferred to another allocation or provider without qualification.']);
 packets.push(C.fromReport(report,m,'modeled'));
}
const ledger=source('BigBirdReturns/tier-bench',TB,'experiments/breadth/run/ledger.jsonl');const groups=new Map();
ledger.text.split(/\r?\n/).forEach((line,i)=>{if(!line.trim())return;const r=JSON.parse(line);if(!r.model||!r.task_id)return;const k=JSON.stringify([r.model,r.task_id,r.effort||'unspecified',r.phase||'unspecified']);if(!groups.has(k))groups.set(k,[]);groups.get(k).push({r,line:i+1,sha256:sha(Buffer.from(line))});});
for(const values of groups.values()){
 const r=values[0].r;const num=v=>typeof v==='number'&&Number.isFinite(v)&&v>=0?v:null;
 const estimated=values.some(({r})=>/est|upper.bound|90\/10|shadow|subscription/i.test(r.note||''));
 const body={task:r.task_id,model:r.model,effort:r.effort||'unspecified',support:r.phase||'source-declared harness',cost_basis:values.every(({r})=>!(r.cost_usd>0))?'unknown':estimated?'shadow-estimated':'source-reported',unit:'source-reported task passes',verifier:'Original TierBench validator reports; not independently rerun for this board.',claim_basis:'Historical source rows imported from an exact commit; task and grader epochs may be incomplete.',source_sha256:ledger.source.sha256,trials:values.map(({r,line,sha256})=>({line,sha256,outcome:['pass','fail','error','partial'].includes(r.outcome)?r.outcome:'unknown',cost_usd:r.cost_usd>0?num(r.cost_usd):null,source_cost_usd:num(r.cost_usd),latency_ms:num(r.latency_ms),input_tokens:num(r.input_tokens),output_tokens:num(r.output_tokens)}))};
 const dates=values.map(v=>v.r.ts).filter(x=>typeof x==='string'&&Number.isFinite(Date.parse(x))).sort();
 const m=meta(r.task_id+' · '+r.model,'TierBench historical model route','Execution surface declared in original ledger','TierBench / '+r.task_id,body.support,[ledger.source],['Historical trial summary, not a fresh run on the current model label.','No cross-task hardware or provider ranking is inferred.','All recorded attempts are retained; unavailable cost or latency stays unknown. A historical zero without an explicit billing basis remains source_cost_usd=0 but contributes unknown cost, not free execution.','Token splits and dollar figures may be estimates; this is not invoice reconciliation.','Source names and hashes do not establish independent replication.'],dates[0]||'2026-07-07');packets.push(C.make('tierbench-trials',body,m));
}
const study=source('BigBirdReturns/tier-bench',TB,'experiments/tier-uplift/LEDGER.md');const start=study.text.indexOf('## Task 05'),end=study.text.indexOf('## Task 06');if(start<0||end<start)throw Error('Historical finding headings moved.');const excerpt=study.text.slice(start,end).trim();
for(const [model,support,value] of [['haiku','Solo baseline',3],['sonnet','Solo baseline',4],['opus','Solo baseline',4],['haiku','Frozen generic five-lens sweep',5]]){const body={model,support,task:'Task 05 / intervals / held-out bug finding',measure:'reported bugs found',value,maximum:5,cost_usd:null,cost_basis:'unknown',source_sha256:study.source.sha256,source_excerpt:excerpt,study_status:'One held-out subject; historical author-reported finding. No new evaluation performed.'};const m=meta(model+' · '+support,'TierBench historical method study','Model hardware not recorded','Transfer study / intervals',support,[study.source],['One subject; this does not establish general model equivalence.','Precision costs and extra findings were not fully quantified.','Five focused passes increase work; runtime cost is unmeasured in this row.','Generic lenses were recorded as frozen before this subject. Source-authenticity remains external.'],'2026-07-07');packets.push(C.make('historical-finding',body,m));}
for(const p of packets){const warnings=C.privacy(p);if(warnings.length)throw Error('Seed privacy review: '+warnings.join(', '));const dest=path.join(ROOT,'data','records',p.sha256+'.json');fs.mkdirSync(path.dirname(dest),{recursive:true});const txt=JSON.stringify(p,null,2)+'\n';if(fs.existsSync(dest)&&fs.readFileSync(dest,'utf8')!==txt)throw Error('Immutable packet changed');fs.writeFileSync(dest,txt);}
const cfg={schema:'second-run/board-release@1',version:'0.1.0',name:'Second Run · Results',built_at:'2026-09-24T00:00:00Z',submission_repository:'BigBirdReturns/axm-tools',records:packets.map(p=>p.sha256).sort(),source_manifest:'source-manifest.json',release_scope:'Operator-owned native campaign evidence and source-linked historical TierBench records. No community adoption, independent replication, or new native execution is asserted.'};
fs.writeFileSync(path.join(ROOT,'data/release.json'),JSON.stringify(cfg,null,2)+'\n');fs.writeFileSync(path.join(ROOT,'data/source-manifest.json'),JSON.stringify({schema:'second-run/seed-source-manifest@1',sources,records:packets.length,acquisition:'Retained exact published bytes. Git blob identity checked at acquisition; source statements are not independent execution attestation.'},null,2)+'\n');console.log(JSON.stringify({records:packets.length,native:packets.filter(p=>p.payload.kind==='workload-report').map(p=>C.summarize(p)),sources:sources.length},null,2));
