#!/usr/bin/env python3
"""Cantos builder. Stdlib only.

Projects the existing owners byte-exactly (ResearchCore from research-desk/app.html,
Compute from compute/engine.cjs) into native/, then inlines them with the foundation,
seed, style and page into one self-contained HTML file.

    python research-desk/cantos/build.py --out DIR      # write DIR/cantos.html, cantos-seed.json, BUILD.json, cantos-portable.zip
    python research-desk/cantos/build.py --check        # build in memory, run every check and the native test, exit 1 on failure
    python research-desk/cantos/build.py --out DIR --check

No network, no dependencies, no execution of page code except `node scripts/test_foundation.cjs` under --check.
"""
from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import re
import subprocess
import sys
import zipfile
from pathlib import Path

HERE = Path(__file__).resolve().parent            # research-desk/cantos
DESK = HERE.parent                                 # research-desk
ROOT = DESK.parent                                 # repo root
APP = DESK / 'app.html'
APP_SHA256 = '5951f7f3d994ec980d2958ae18246edc6dbe5b57db8d38e90c1c18956b96e470'
COMPUTE = ROOT / 'compute' / 'engine.cjs'
NATIVE = HERE / 'native'
CORE_RE = re.compile(r'<script id="research-core">([\s\S]*?)</script>')
PLACEHOLDERS = ['style', 'native_core', 'native_compute', 'foundation', 'seed', 'build', 'page_script']
PRIVATE_PATTERNS = [
    ('absolute Windows path', re.compile(r'[A-Za-z]:\\(?:Users|Projects|Scratch)')),
    ('absolute Windows path (forward)', re.compile(r'\b[A-Za-z]:/(?:Users|Projects|Scratch)')),
    ('home path', re.compile(r'/home/[A-Za-z0-9_.-]+/')),
    ('VM host string', re.compile(r'enc1-gpuvm')),
    ('IPv4 address', re.compile(r'\b(?:\d{1,3}\.){3}\d{1,3}\b')),
    ('provider account host', re.compile(r'@hotaisle\.app')),
    ('credential', re.compile(r'gh[pousr]_[A-Za-z0-9]{15,}|sk-[A-Za-z0-9_-]{20,}|Bearer\s+[A-Za-z0-9_.-]{12,}|-----BEGIN [A-Z ]*PRIVATE KEY-----|AKIA[0-9A-Z]{16}')),
    ('e-mail address', re.compile(r'[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}')),
]
EXTERNAL_PATTERNS = [
    ('script src', re.compile(r'<script[^>]*\ssrc=', re.I)),
    ('link href', re.compile(r'<link[^>]*\shref=', re.I)),
    ('css import', re.compile(r'@import\s', re.I)),
    ('remote url()', re.compile(r'url\(\s*["\']?\s*(?:https?:)?//', re.I)),
    ('img src http', re.compile(r'<img[^>]*\ssrc=["\']?https?://', re.I)),
    ('iframe', re.compile(r'<iframe', re.I)),
    ('fetch call', re.compile(r'\bfetch\s*\(')),
    ('XMLHttpRequest', re.compile(r'XMLHttpRequest')),
    ('WebSocket', re.compile(r'new\s+WebSocket')),
    ('sendBeacon', re.compile(r'sendBeacon')),
]


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def read(path: Path) -> str:
    return path.read_text(encoding='utf-8')


def project() -> dict:
    """Byte-exact projections of the existing owners into native/."""
    app = APP.read_bytes()
    if sha(app) != APP_SHA256:
        raise SystemExit('research-desk/app.html is not the frozen 1.0.0 file (sha256 %s).' % sha(app))
    text = app.decode('utf-8')
    scripts = CORE_RE.findall(text)
    if len(scripts) != 1:
        raise SystemExit('Exactly one marked ResearchCore script is required in app.html.')
    core = scripts[0]
    compute = read(COMPUTE)
    NATIVE.mkdir(exist_ok=True)
    manifest = {
        'schema': 'cantos/native-manifest@1',
        'app_sha256': APP_SHA256,
        'artifacts': {
            'research-core.js': {'source_path': 'research-desk/app.html#research-core', 'source_sha256': APP_SHA256, 'projected_sha256': sha(core.encode('utf-8'))},
            'compute-engine.js': {'source_path': 'compute/engine.cjs', 'source_sha256': sha(compute.encode('utf-8')), 'projected_sha256': sha(compute.encode('utf-8'))},
        },
        'rule': 'Generated by research-desk/cantos/build.py from the existing owners; never edit by hand.',
    }
    (NATIVE / 'research-core.js').write_text(core, encoding='utf-8', newline='')
    (NATIVE / 'compute-engine.js').write_text(compute, encoding='utf-8', newline='')
    (NATIVE / 'MANIFEST.json').write_text(json.dumps(manifest, indent=2) + '\n', encoding='utf-8')
    return {'core': core, 'compute': compute, 'manifest': manifest}


def verify_projection(p: dict) -> list[str]:
    errors = []
    for name in ('research-core.js', 'compute-engine.js'):
        on_disk = (NATIVE / name).read_bytes()
        want = p['manifest']['artifacts'][name]['projected_sha256']
        if sha(on_disk) != want:
            errors.append('native/%s drifted from its source (%s != %s).' % (name, sha(on_disk), want))
    if sha(COMPUTE.read_bytes()) != p['manifest']['artifacts']['compute-engine.js']['source_sha256']:
        errors.append('compute/engine.cjs changed during build.')
    return errors


def load_inputs() -> dict:
    page = HERE / 'page.html'
    seed = HERE / 'data' / 'seed.json'
    inputs = {
        'page_status': 'opus' if page.exists() else 'provisional',
        'page': read(page) if page.exists() else read(HERE / 'scripts' / 'fallback-page.html'),
        'page_script': read(HERE / 'page.js') if (HERE / 'page.js').exists() else '',
        'style': read(HERE / 'style.css') if (HERE / 'style.css').exists() else '',
        'seed_status': 'sol' if seed.exists() else 'provisional',
        'seed_text': read(seed) if seed.exists() else read(HERE / 'scripts' / 'provisional-seed.json'),
        'foundation': read(HERE / 'foundation.js'),
    }
    inputs['seed'] = json.loads(inputs['seed_text'])
    return inputs


def check_seed(seed: dict) -> list[str]:
    errors = []
    if seed.get('schema') != 'cantos/seed@1':
        errors.append('seed schema must be cantos/seed@1.')
    records = seed.get('records') or []
    ids = set()
    roles = {}
    for r in records:
        rid = r.get('id')
        if rid in ids:
            errors.append('duplicate seed record id %s' % rid)
        ids.add(rid)
        role = (r.get('data') or {}).get('role')
        roles.setdefault(role, []).append(rid)
        for d in r.get('deps') or []:
            if d.get('id') not in ids:
                errors.append('seed record %s depends on %s before it is defined' % (rid, d.get('id')))
        rp = (r.get('data') or {}).get('relative_path')
        if rp and re.match(r'^(?:[A-Za-z]:|\\\\|/)', rp):
            errors.append('seed record %s relative_path is absolute' % rid)
        if role == 'economics' and 'result' in (r.get('data') or {}):
            errors.append('seed record %s supplies a result; the bridge derives it' % rid)
    for role in ('price', 'economics', 'recommendation'):
        if len(roles.get(role, [])) != 1:
            errors.append('seed needs exactly one %s record (found %d)' % (role, len(roles.get(role, []))))
    if not roles.get('measurement'):
        errors.append('seed needs at least one measurement record')
    target = (seed.get('case') or {}).get('target')
    if target not in roles.get('recommendation', []):
        errors.append('case.target must name the recommendation record')
    return errors


def script_safe(text: str) -> str:
    return text.replace('</script', '<\\/script').replace('<!--', '<\\!--')


def json_safe(text: str) -> str:
    return text.replace('<', '\\u003c').replace('\u2028', '\\u2028').replace('\u2029', '\\u2029')


def assemble(p: dict, inputs: dict, built_at: str) -> tuple[str, dict]:
    seed_text = json.dumps(inputs['seed'], ensure_ascii=False, separators=(',', ':'))
    build = {
        'schema': 'cantos/build@1',
        'built_at': built_at,
        'app_sha256': APP_SHA256,
        'research_core_sha256': p['manifest']['artifacts']['research-core.js']['projected_sha256'],
        'compute_sha256': p['manifest']['artifacts']['compute-engine.js']['projected_sha256'],
        'foundation_sha256': sha(inputs['foundation'].encode('utf-8')),
        'seed_sha256': sha(json_safe(seed_text).encode('utf-8')),  # hash of the exact embedded #cantos-seed text
        'seed_status': inputs['seed_status'],
        'page_status': inputs['page_status'],
        'page_script_sha256': sha(inputs['page_script'].encode('utf-8')),
        'style_sha256': sha(inputs['style'].encode('utf-8')),
    }
    values = {
        'style': inputs['style'].replace('</style', '<\\/style'),
        'native_core': script_safe(p['core']),
        'native_compute': script_safe(p['compute']),
        'foundation': script_safe(inputs['foundation']),
        'seed': json_safe(seed_text),
        'build': json_safe(json.dumps(build, separators=(',', ':'))),
        'page_script': script_safe(inputs['page_script']),
    }
    html = inputs['page']
    errors = []
    last = -1
    for name in PLACEHOLDERS:
        token = '{{cantos.%s}}' % name
        n = html.count(token)
        if n != 1:
            errors.append('template must contain %s exactly once (found %d)' % (token, n))
            continue
        pos = html.index(token)
        if pos < last:
            errors.append('template placeholder %s is out of order' % token)
        last = pos
    if errors:
        raise SystemExit('\n'.join(errors))
    for name in PLACEHOLDERS:
        html = html.replace('{{cantos.%s}}' % name, values[name], 1)
    return html, build


def scan(html: str) -> list[str]:
    errors = []
    if '{{cantos.' in html:
        errors.append('unfilled placeholder remains in output')
    for label, rx in PRIVATE_PATTERNS:
        for m in rx.finditer(html):
            snippet = html[max(0, m.start() - 20):m.end() + 20].replace('\n', ' ')
            errors.append('private-content scan hit (%s): ...%s...' % (label, snippet))
            break
    for label, rx in EXTERNAL_PATTERNS:
        m = rx.search(html)
        if m:
            errors.append('external-request pattern (%s) at offset %d' % (label, m.start()))
    if 'id="research-core"' not in html or 'id="compute-engine"' not in html or 'id="cantos-seed"' not in html or 'id="cantos-build"' not in html:
        errors.append('page must place the projected scripts in <script id="research-core">, <script id="compute-engine">, <script id="cantos-seed"> and <script id="cantos-build">')
    return errors


def native_test() -> tuple[int, str]:
    p = subprocess.run(['node', str(HERE / 'scripts' / 'test_foundation.cjs')], capture_output=True, text=True, encoding='utf-8', cwd=str(ROOT))
    return p.returncode, (p.stdout + p.stderr)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--out', help='output directory for cantos.html, cantos-seed.json, BUILD.json and cantos-portable.zip')
    ap.add_argument('--check', action='store_true', help='run projection, seed, privacy, external-request and native checks; exit 1 on failure')
    args = ap.parse_args(argv)
    if not args.out and not args.check:
        ap.print_help()
        return 2
    built_at = dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat().replace('+00:00', 'Z')
    p = project()
    inputs = load_inputs()
    errors = check_seed(inputs['seed'])
    if errors:
        for e in errors:
            print('SEED  FAIL ' + e)
        return 1
    html, build = assemble(p, inputs, built_at)
    build['html_sha256'] = sha(html.encode('utf-8'))
    print('projection  research-core %s  compute %s  app %s' % (build['research_core_sha256'][:12], build['compute_sha256'][:12], APP_SHA256[:12]))
    print('inputs      page=%s seed=%s foundation=%s' % (inputs['page_status'], inputs['seed_status'], build['foundation_sha256'][:12]))
    failures = []
    if args.check:
        failures += verify_projection(p)
        failures += scan(html)
        code, out = native_test()
        print(out.rstrip())
        if code:
            failures.append('native test exited %d' % code)
        for f in failures:
            print('CHECK FAIL ' + f)
        print('checks      %s' % ('PASS' if not failures else 'FAIL (%d)' % len(failures)))
    if args.out:
        out = Path(args.out).resolve()
        out.mkdir(parents=True, exist_ok=True)
        (out / 'cantos.html').write_text(html, encoding='utf-8', newline='\n')
        (out / 'cantos-seed.json').write_text(json.dumps(inputs['seed'], indent=2, ensure_ascii=False) + '\n', encoding='utf-8')
        build['checks'] = 'PASS' if (args.check and not failures) else ('FAIL' if args.check else 'not run')
        (out / 'BUILD.json').write_text(json.dumps(build, indent=2) + '\n', encoding='utf-8')
        with zipfile.ZipFile(out / 'cantos-portable.zip', 'w', zipfile.ZIP_DEFLATED) as z:
            for name in ('cantos.html', 'cantos-seed.json', 'BUILD.json'):
                z.write(out / name, 'cantos/' + name)
        print('written     %s  (cantos.html %d bytes, sha256 %s)' % (out, len(html.encode('utf-8')), build['html_sha256'][:12]))
    return 1 if failures else 0


if __name__ == '__main__':
    sys.exit(main())
