/* Second Run Research Desk 1.0.0. Original code, MIT.
   Pure calculations and event journal. No network, credentials or execution adapters. */
(function(root){
'use strict';
const VERSION='1.0.1', SCHEMA='second-run/research-desk@1';
const kinds=['source','claim','policy','run','calculation','conclusion','instruments','diligence','mandate'];
const tiers=['public_observation','operator_supplied','synthetic','proposal'];
const enc=new TextEncoder();
function assert(ok,message){if(!ok)throw new Error(message);}
function plain(v){return v!==null&&typeof v==='object'&&!Array.isArray(v)&&(Object.getPrototypeOf(v)===Object.prototype||Object.getPrototypeOf(v)===null);}
function safeTree(v,depth=0){assert(depth<60,'Object nesting exceeds 60 levels.'); if(typeof v==='number')assert(Number.isFinite(v),'Non-finite numbers are forbidden.'); if(v&&typeof v==='object'){assert(Array.isArray(v)||plain(v),'Only plain JSON data is supported.'); for(const k of Object.keys(v)){assert(!['__proto__','constructor','prototype'].includes(k),'Unsafe object key.');safeTree(v[k],depth+1);}}}
function canonical(v){safeTree(v);if(Array.isArray(v))return '['+v.map(canonical).join(',')+']';if(plain(v))return '{'+Object.keys(v).sort().filter(k=>v[k]!==undefined).map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}';assert(v!==undefined,'Undefined JSON value.');return JSON.stringify(v);}
function clone(v){return JSON.parse(canonical(v));}
async function hash(v){const bytes=typeof v==='string'?enc.encode(v):v instanceof Uint8Array?v:enc.encode(canonical(v));const crypto=root.crypto || (typeof require!=='undefined'?require('node:crypto').webcrypto:null);assert(crypto?.subtle,'Web Crypto is unavailable; use a current browser or localhost.');return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');}
function str(v,n,label){assert(typeof v==='string'&&v.trim().length>0&&v.length<=n,label+' must be a nonempty string (max '+n+').');}
function number(v,min,label){assert(typeof v==='number'&&Number.isFinite(v)&&v>=min,label+' must be a finite number >= '+min+'.');}
function id(v){str(v,90,'ID');assert(/^[a-zA-Z0-9][a-zA-Z0-9_.:-]*$/.test(v),'Invalid ID.');}
function isoDate(v){return typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v))&&new Date(v+'T00:00:00Z').toISOString().slice(0,10)===v;}
function timestamp(v){assert(typeof v==='string'&&/T.*(?:Z|[+-]\d\d:\d\d)$/.test(v)&&Number.isFinite(Date.parse(v)),'Timestamp requires a timezone.');}
function parse(text){assert(typeof text==='string'&&text.length<=12000000,'File limit is 12 MB.');const v=JSON.parse(text);safeTree(v);return v;}
function empty(label='Private research workspace'){str(label,200,'Workspace label');return {schema:SCHEMA,version:VERSION,label,events:[]};}
function state(ws){const s={records:{},reviews:[],reports:[]};for(const e of ws.events){if(e.type==='record'){const r=e.payload;(s.records[r.id]??=[]).push(r);}if(e.type==='review')s.reviews.push({...e.payload,at:e.at,event_hash:e.hash});if(e.type==='freeze')s.reports.push({...e.payload,at:e.at,event_hash:e.hash});}return s;}
function latest(s,key){return s.records[key]?.at(-1)||null;}
function version(s,key,rev){return s.records[key]?.find(x=>x.revision===rev)||null;}
function checkRecord(s,r){safeTree(r);id(r.id);assert(kinds.includes(r.kind),'Unsupported record kind.');if(latest(s,r.id))assert(latest(s,r.id).kind===r.kind,'A successor cannot change the record kind.');str(r.title,240,'Title');assert(typeof r.summary==='string'&&r.summary.length<=30000,'Summary too long.');assert(tiers.includes(r.tier),'Evidence tier is required.');assert(['open','observed','supported','conflict','withdrawn','draft'].includes(r.disposition),'Invalid disposition.');assert(Array.isArray(r.deps)&&r.deps.length<=100,'Dependencies must be an array.');assert(r.revision===(latest(s,r.id)?.revision||0)+1,'Revision must be the next sequence.');const seen=new Set();for(const d of r.deps){id(d.id);assert(!seen.has(d.id),'Duplicate dependency.');seen.add(d.id);assert(d.id!==r.id,'A record cannot depend on itself.');assert(Number.isInteger(d.revision)&&version(s,d.id,d.revision),'Dependency revision missing: '+d.id);}
 // Check stable-ID DAG as well as version graph: future edits cannot create circular review paths.
 const walk=(key,visited=new Set())=>{assert(key!==r.id,'Dependency cycle.');if(visited.has(key))return;visited.add(key);for(const d of latest(s,key)?.deps||[])walk(d.id,visited);};for(const d of r.deps)walk(d.id);
 assert(plain(r.data),'Record data must be an object.');if(r.kind==='policy')validatePolicy(r.data);if(r.kind==='run')validateRun(r.data);if(r.kind==='instruments')validateDeal(r.data);
 if(r.kind==='calculation'){
   assert(r.data.recipe==='task-cost@1','Unsupported calculation recipe. Use a claim record for manually supplied analysis.');
   const refs=r.deps.map(d=>version(s,d.id,d.revision)),policies=refs.filter(x=>x.kind==='policy'),runs=refs.filter(x=>x.kind==='run');
   assert(policies.length===1&&runs.length>=1&&refs.length===runs.length+1,'Calculation needs one policy and one or more runs.');
   const expected={...compare(runs.map(x=>x.data),policies[0].data),selectedRecordIds:runs.map(x=>x.id),recipe:'task-cost@1'};
   assert(canonical(expected)===canonical(r.data),'Derived calculation does not recompute from its pinned inputs.');
   if(runs.some(x=>x.tier==='synthetic'))assert(r.tier==='synthetic','Synthetic calculations must retain their evidence tier.');
 }
 if(r.kind==='diligence'){
   assert(r.data.recipe==='diligence@1'&&r.deps.length===1,'Unsupported diligence recipe.');
   const input=version(s,r.deps[0].id,r.deps[0].revision);assert(input.kind==='instruments','Diligence requires instrument records.');
   assert(canonical({...assessDeal(input.data),recipe:'diligence@1'})===canonical(r.data),'Diligence does not recompute from its pinned inputs.');
   if(input.tier==='synthetic')assert(r.tier==='synthetic','Synthetic diligence must retain its evidence tier.');
 }

}
function dependencyState(s,key,visited=new Set()){const r=latest(s,key);if(!r)return {current:false,blockers:['Missing '+key]};if(visited.has(key))return {current:false,blockers:['Cycle '+key]};visited=new Set(visited);visited.add(key);const blockers=[];if(['conflict','withdrawn','open'].includes(r.disposition))blockers.push(key+': '+r.disposition);for(const d of r.deps){const now=latest(s,d.id);if(!now||now.revision!==d.revision)blockers.push(d.id+': pinned v'+d.revision+', current v'+(now?.revision||'?'));for(const b of dependencyState(s,d.id,visited).blockers)blockers.push(b);}return {current:!blockers.length,blockers:[...new Set(blockers)]};}
function impact(s,key){const result=[],seen=new Set([key]);let changed=true;while(changed){changed=false;for(const k of Object.keys(s.records)){if(!seen.has(k)&&latest(s,k).deps.some(d=>seen.has(d.id))){seen.add(k);result.push(k);changed=true;}}}return result;}
function closure(s,key,result={}){const r=latest(s,key);assert(r,'Record missing.');if(result[key])return result;result[key]=r;for(const d of r.deps)closure(s,d.id,result);return result;}
async function fingerprint(s,key){return hash({target:key,records:closure(s,key)});}
async function reviewState(s,key){const f=await fingerprint(s,key);const review=[...s.reviews].reverse().find(r=>r.target===key&&r.fingerprint===f);return {fingerprint:f,review:review||null,ready:dependencyState(s,key).current&&review?.decision==='accept'};}
async function append(ws,type,payload,actor,at=new Date().toISOString()){
 str(actor,160,'Actor');timestamp(at);assert(ws.events.length<3000,'Workspace event limit reached; archive this engagement.');const s=state(ws);payload=clone(payload);
 if(type==='record')checkRecord(s,payload);
 else if(type==='review'){id(payload.target);assert(latest(s,payload.target),'Review target missing.');str(payload.rationale,4000,'Review rationale');assert(payload.rationale.trim().length>=12,'Explain the review in at least 12 characters.');assert(['accept','hold','reject'].includes(payload.decision),'Invalid review decision.');assert(payload.fingerprint===await fingerprint(s,payload.target),'Review is bound to an old graph.');if(payload.decision==='accept')assert(dependencyState(s,payload.target).current,'Resolve stale or open dependencies before accepting.');payload.reviewer=actor;}
 else if(type==='freeze'){const rs=await reviewState(s,payload.target);assert(rs.ready,'A current accepted review is required before freezing.');assert(payload.fingerprint===rs.fingerprint,'Freeze fingerprint is stale.');assert(payload.snapshot_hash===await hash(payload.snapshot),'Snapshot checksum mismatch.');assert(canonical(payload.snapshot.records)===canonical(closure(s,payload.target)),'Snapshot must contain the exact current dependency closure.');assert(canonical(payload.snapshot.review)===canonical(rs.review),'Snapshot review contents differ from the journal review.');}
 else throw new Error('Unknown journal event.');
 const body={seq:ws.events.length+1,prev:ws.events.at(-1)?.hash||'0'.repeat(64),type,actor,at,payload};const e={...body,hash:await hash(body)};assert(canonical({...ws,events:[...ws.events,e]}).length<=11000000,'Workspace exceeds the 11 MB working limit; archive and begin a new engagement.');ws.events.push(e);return e;
}
async function put(ws,record,actor='Local operator',at){const s=state(ws);const r={...clone(record),revision:(latest(s,record.id)?.revision||0)+1};await append(ws,'record',r,actor,at);return r;}
async function review(ws,target,decision,rationale,actor,at){const s=state(ws);return append(ws,'review',{target,decision,rationale,fingerprint:await fingerprint(s,target)},actor,at);}
async function freeze(ws,target,actor,at){const s=state(ws),rs=await reviewState(s,target);assert(rs.ready,'Current review required.');const snapshot={schema:'second-run/research-report@1',workspace:ws.label,target,records:closure(s,target),review:rs.review,evidence_boundary:'Source identity and recomputable reasoning; not source truth, authenticated human identity or investment approval.'};return append(ws,'freeze',{target,fingerprint:rs.fingerprint,snapshot,snapshot_hash:await hash(snapshot)},actor,at);}
async function pack(ws){return {schema:'second-run/research-packet@1',workspace:clone(ws),sha256:await hash(ws),boundary:'Checksum and journal detect changes relative to this packet. They do not authenticate a publisher or prevent a hostile party from rebuilding an entirely new chain. Retain a trusted prior checksum separately.'};}
async function verifyPacket(packet){safeTree(packet);assert(packet.schema==='second-run/research-packet@1','Unsupported workspace envelope.');const ws=packet.workspace;assert(ws?.schema===SCHEMA&&['1.0.0',VERSION].includes(ws.version),'Unsupported workspace version.');str(ws.label,200,'Workspace label');assert(Array.isArray(ws.events)&&ws.events.length<=3000,'Invalid event list.');assert(await hash(ws)===packet.sha256,'Workspace checksum failed.');const clean=empty(ws.label);clean.version=ws.version;for(const event of ws.events){assert(event.seq===clean.events.length+1,'Noncontiguous event sequence.');assert(event.prev===(clean.events.at(-1)?.hash||'0'.repeat(64)),'Broken predecessor.');const {hash:stored,...body}=event;assert(await hash(body)===stored,'Event hash failed.');const rebuilt=await append(clean,event.type,event.payload,event.actor,event.at);assert(canonical(rebuilt)===canonical(event),'Event replay mismatch.');}return clean;}
function validatePolicy(p){assert(['strict_json','extract_json'].includes(p.grader),'Unsupported grading contract.');number(p.deadline_ms,1,'Deadline');number(p.quality_floor,0,'Quality floor');assert(p.quality_floor<=1,'Quality floor exceeds 1.');assert(Number.isInteger(p.min_tasks)&&p.min_tasks>=1,'Minimum distinct tasks must be positive.');assert(['actual','quote'].includes(p.cost_basis),'Cost basis must be actual or quote.');assert(['task','hardware'].includes(p.comparison_mode),'Invalid comparison mode.');}
function validateRun(r){safeTree(r);assert(r.schema==='second-run/task-run@1','Unsupported task-run schema.');id(r.run_id);str(r.label,200,'Run label');assert(['synthetic','producer_reported','independently_rerun'].includes(r.evidence),'Run evidence class required.');assert(plain(r.pins),'Configuration pins required.');for(const k of ['taskset','contract','load','boundary'])str(r.pins[k],200,'Pin '+k);assert(Array.isArray(r.tasks)&&r.tasks.length>0&&r.tasks.length<=5000,'1–5,000 tasks required.');const ids=new Set();for(const t of r.tasks){id(t.id);assert(!ids.has(t.id),'Duplicate original task ID.');ids.add(t.id);assert(plain(t.expected)&&Object.keys(t.expected).length>0,'Expected field object required.');for(const v of Object.values(t.expected))assert(v===null||['string','boolean','number'].includes(typeof v),'Answer keys require scalar fields.');assert(Array.isArray(t.attempts)&&t.attempts.length>0&&t.attempts.length<=100,'Task attempts missing or too many.');let prev=-1;for(const a of t.attempts){assert(['ok','timeout','error','refused'].includes(a.status),'Invalid attempt status.');number(a.elapsed_ms,0,'Elapsed time');assert(a.elapsed_ms>=prev,'Attempts must follow cumulative elapsed time.');prev=a.elapsed_ms;assert(typeof a.output==='string'&&a.output.length<=50000,'Invalid output text.');if(a.cost_usd!==null)number(a.cost_usd,0,'Attempt cost');}}
 assert(plain(r.billing),'Billing object required.');for(const key of ['actual_total_usd','quote_total_usd'])if(r.billing[key]!==null)number(r.billing[key],0,key);str(r.billing.scope,400,'Billing scope');assert(r.billing.currency==='USD','Only USD accounting is implemented.');
}
function answer(output,grader){if(grader==='strict_json'){try{const x=JSON.parse(output.trim());return plain(x)?x:null;}catch{return null;}}
 // Accept one JSON object, either as the entire answer, a sole fenced block,
 // or one unambiguous object amid prose. Never execute generated text.
 try{const x=JSON.parse(output.trim());if(plain(x))return x;}catch{}
 const candidates=[];let start=-1,depth=0,inString=false,escape=false;
 for(let i=0;i<output.length;i++){const c=output[i];if(start<0){if(c==='{'){start=i;depth=1;inString=false;}continue;}if(inString){if(escape)escape=false;else if(c==='\\')escape=true;else if(c==='"')inString=false;continue;}if(c==='"'){inString=true;continue;}if(c==='{')depth++;if(c==='}'&&--depth===0){try{const x=JSON.parse(output.slice(start,i+1));if(plain(x))candidates.push(x);}catch{}start=-1;}}
 return candidates.length===1?candidates[0]:null;
}
function grade(output,expected,grader){const obj=answer(output,grader);return !!obj&&Object.keys(expected).length===Object.keys(obj).length&&Object.keys(expected).every(k=>Object.hasOwn(obj,k)&&canonical(obj[k])===canonical(expected[k]));}
function percentile(a,p){if(!a.length)return null;const b=[...a].sort((a,b)=>a-b);return b[Math.max(0,Math.ceil(b.length*p)-1)];}
function evaluate(r,p){validateRun(r);validatePolicy(p);let attempts=0,quality=0,accepted=0,censored=0,cost=0,unknownCost=0;const times=[],rows=[];for(const t of r.tasks){let q=false,pass=false;for(const a of t.attempts){attempts++;if(a.cost_usd===null)unknownCost++;else cost+=a.cost_usd;if(a.status==='timeout')censored++;if(a.status==='ok')times.push(a.elapsed_ms);const good=a.status==='ok'&&grade(a.output,t.expected,p.grader);q=q||good;pass=pass||(good&&a.elapsed_ms<=p.deadline_ms);}quality+=q?1:0;accepted+=pass?1:0;rows.push({id:t.id,quality:q,accepted:pass,attempts:t.attempts.length});}
 const actual=r.billing.actual_total_usd,quote=r.billing.quote_total_usd,total=p.cost_basis==='actual'?actual:quote;const n=r.tasks.length;const blockers=[];
 if(total===null)blockers.push('Complete '+p.cost_basis+' cost missing.');if(actual!==null&&!unknownCost&&actual+1e-10<cost&&!r.billing.reconciliation)blockers.push('Actual total is below recorded attempt charges; reconciliation required.');if(n<p.min_tasks)blockers.push('Too few distinct tasks for the configured gate.');if(accepted/n<p.quality_floor)blockers.push('Joint quality/deadline floor missed.');if(!accepted)blockers.push('Zero accepted original tasks.');
 return {run_id:r.run_id,label:r.label,evidence:r.evidence,tasks:n,attempts,quality,accepted,success_rate:accepted/n,censored,completed_latency_p95_ms:percentile(times,.95),attempt_cost_usd:unknownCost?null:cost,actual_total_usd:actual,quote_total_usd:quote,total_usd:total,cost_basis:p.cost_basis,cost_per_success:total!==null&&accepted?total/accepted:null,eligible:!blockers.length,blockers,rows,scope:'Observed fixed-task result. No population reliability estimate or production qualification.'};}
function compare(runs,p){assert(Array.isArray(runs)&&runs.length>=1,'No runs supplied.');const results=runs.map(r=>evaluate(r,p)),blocks=[];const ids=runs.map(r=>r.run_id);if(new Set(ids).size!==ids.length)blocks.push('Duplicate run identities.');const keys=['taskset','contract','load','boundary'];if(p.comparison_mode==='hardware')keys.push('model','revision','precision','tokenizer','runtime','cache');for(const key of keys){const values=runs.map(r=>r.pins[key]);if(values.some(v=>!v))blocks.push('Missing comparison pin: '+key);else if(new Set(values).size>1)blocks.push('Mismatched comparison pin: '+key);}
 const populations=runs.map(r=>canonical([...r.tasks].sort((a,b)=>a.id.localeCompare(b.id)).map(t=>({id:t.id,expected:t.expected}))));if(new Set(populations).size>1)blocks.push('Different original tasks or answer keys.');if(new Set(runs.map(r=>r.evidence)).size>1)blocks.push('Evidence classes differ.');const eligible=results.filter(r=>r.eligible).sort((a,b)=>a.cost_per_success-b.cost_per_success);return {results,blockers:blocks,winner:blocks.length||!eligible.length?null:eligible[0].run_id,tied:eligible.length>1&&eligible[0].cost_per_success===eligible[1].cost_per_success,scope:runs.every(r=>r.evidence==='synthetic')?'SYNTHETIC ACCOUNTING EXERCISE':'PRODUCER EVIDENCE / CONFIGURED SAMPLE ONLY'};}
function reprice(run,gpus,rate,hours,extras=0){validateRun(run);number(gpus,1,'Billable GPU count');assert(Number.isInteger(gpus),'GPU count must be an integer.');number(rate,0,'Rate');number(hours,0,'Full billed hours');number(extras,0,'Additional costs');const r=clone(run);r.billing.quote_total_usd=gpus*rate*hours+extras;r.billing.quote_calculation={gpus,rate,hours,extras};return r;}
function validateDeal(d){assert(d.schema==='second-run/diligence-case@1','Unsupported diligence schema.');str(d.company,160,'Company');assert(isoDate(d.as_of),'As-of date required.');number(d.claimed_arr_usd,0,'Claimed ARR');assert(Array.isArray(d.instruments)&&d.instruments.length<=5000,'Instrument list required.');const ids=new Set();for(const i of d.instruments){id(i.id);assert(!ids.has(i.id),'Duplicate instrument.');ids.add(i.id);str(i.counterparty,200,'Counterparty');assert(['recurring_contract','pilot','mou','loi'].includes(i.kind),'Invalid instrument type.');assert(['signed','unsigned','terminated'].includes(i.status),'Invalid instrument status.');number(i.annual_usd,0,'Annual consideration');number(i.cash_received_usd,0,'Reported cash received');assert(['accepted','pending','none'].includes(i.acceptance),'Invalid acceptance status.');for(const key of ['starts','ends'])if(i[key]!==null)assert(isoDate(i[key]),'Invalid instrument date.');if(i.starts!==null&&i.ends!==null)assert(i.starts<=i.ends,'Instrument ends before it starts.');assert(Array.isArray(i.evidence_refs),'Instrument evidence references required.');}
 assert(Array.isArray(d.tests),'Tests required.');for(const t of d.tests){id(t.id);str(t.claim,1000,'Test claim');assert(['not_run','pass','fail','inconclusive'].includes(t.result),'Invalid test result.');str(t.procedure,4000,'Test procedure');str(t.acceptance,2000,'Acceptance criterion');assert(Array.isArray(t.evidence_refs),'Test evidence references required.');}
}
function assessDeal(d){validateDeal(d);let signed=0,cash=0,accepted=0;const customers=new Set(),rows=[];for(const i of d.instruments){const active=i.status==='signed'&&i.starts!==null&&i.starts<=d.as_of&&(i.ends===null||i.ends>=d.as_of);const evidenced=i.evidence_refs.length>0;const recurring=active&&evidenced&&i.kind==='recurring_contract';if(recurring){signed+=i.annual_usd;customers.add(i.counterparty);}cash+=i.cash_received_usd;if(active&&evidenced&&['recurring_contract','pilot'].includes(i.kind)&&i.acceptance==='accepted')accepted++;rows.push({id:i.id,active,recurring,annual_included_usd:recurring?i.annual_usd:0,reason:!evidenced?'No source reference':!active?'Unsigned, terminated, not started or expired':i.kind!=='recurring_contract'?'Nonrecurring or nonbinding instrument':'Active signed recurring consideration'});}
 const tests=d.tests.map(t=>({...t,source_referenced_pass:t.result==='pass'&&t.evidence_refs.length>0,status:t.result==='pass'&&!t.evidence_refs.length?'UNSUPPORTED PASS':t.result.toUpperCase()}));return {company:d.company,as_of:d.as_of,relationships:d.instruments.length,contracted_customers:customers.size,signed_annualized_usd:signed,claimed_arr_usd:d.claimed_arr_usd,unbridged_usd:d.claimed_arr_usd-signed,reported_cash_received_usd:cash,accepted_instruments:accepted,tests,rows,scope:'Supplied instrument classification. Signed annualized consideration is neither recognized revenue nor audited ARR. Cash is a supplied amount, not bank reconciliation.'};}
function vllmSummary(v){safeTree(v);assert(plain(v)&&typeof v.completed==='number'&&typeof v.duration==='number','Expected a vLLM summary with completed and duration.');number(v.completed,0,'Completed requests');number(v.duration,0,'Duration');if(v.total_output_tokens!==undefined)number(v.total_output_tokens,0,'Output tokens');assert(Number.isInteger(v.completed),'Completed must be integer.');return {format:'vllm-summary',completed:v.completed,duration_s:v.duration,request_throughput:v.duration?v.completed/v.duration:null,total_output_tokens:typeof v.total_output_tokens==='number'?v.total_output_tokens:null,quality:'UNAVAILABLE',cost_per_accepted_task:null,scope:'Serving completions only. Supply original-task identities, evaluator outcomes, timing and full billing to compute accepted-work economics.'};}
function csv(rows,keys){const cell=v=>{let s=v===null||v===undefined?'':typeof v==='object'?canonical(v):String(v);if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};return [keys.map(cell).join(','),...rows.map(r=>keys.map(k=>cell(r[k])).join(','))].join('\r\n');}
function escape(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function reportHTML(snapshot,status,checksum){
 const records=Object.values(snapshot.records),target=snapshot.records[snapshot.target],review=snapshot.review;
 const money=(n,d=2)=>typeof n==='number'&&Number.isFinite(n)?'$'+n.toFixed(d):'Unavailable';
 const calcTable=r=>r.data.recipe==='task-cost@1'&&Array.isArray(r.data.results)?'<div class="table-scroll"><table><thead><tr><th>Configuration</th><th>Accepted / original</th><th>Complete supplied cost</th><th>Cost / accepted</th><th>Eligible</th></tr></thead><tbody>'+r.data.results.map(x=>'<tr><td>'+escape(x.label)+'</td><td>'+escape(x.accepted+' / '+x.tasks)+'</td><td>'+money(x.total_usd)+' <small>('+escape(x.cost_basis)+')</small></td><td>'+money(x.cost_per_success,6)+'</td><td>'+escape(x.eligible?'Yes':'No')+'</td></tr>').join('')+'</tbody></table></div><p class="small">Acceptance joins the exact answer contract to the cumulative deadline. Sample eligibility does not establish population reliability or production readiness.</p>':'';
 const detail=r=>['calculation','diligence','mandate'].includes(r.kind)?calcTable(r)+'<details class="machine"><summary>Inspect complete calculation / record data</summary><pre>'+escape(JSON.stringify(r.data,null,2))+'</pre></details>':'';
 return '<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; style-src \'unsafe-inline\'; base-uri \'none\'; form-action \'none\'"><title>'+escape(target?.title||'Second Run research report')+'</title><style>body{font:16px/1.6 system-ui;margin:40px auto;padding:0 24px;max-width:980px;color:#17212c}h1{font-size:38px;line-height:1.1;letter-spacing:-.03em}.status{padding:14px;background:#fff0f6;border-left:4px solid #d72f71}.review{border:1px solid #d9dfe8;border-radius:8px;padding:16px 20px;margin:24px 0}.review p{margin:8px 0}article{border-top:1px solid #ccd;padding:20px 0}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#f3f5f6;padding:15px}small,.small{color:#526070;font-size:13px}small{overflow-wrap:anywhere}.table-scroll{overflow:auto}table{width:100%;border-collapse:collapse;margin:22px 0}td,th{text-align:left;vertical-align:top;padding:12px;border-bottom:1px solid #d9dfe8}th{background:#f4f5f8;font-size:12px}summary{cursor:pointer;color:#a5114b;padding:10px 0}@media(max-width:600px){body{margin:24px auto;padding:0 18px}h1{font-size:30px}td,th{padding:8px;font-size:12px}}@media print{body{margin:0}.machine{display:none}.review{break-inside:avoid}h2{break-after:avoid}}</style><body><p class="small">SECOND RUN / RESEARCH DELIVERY</p><h1>'+escape(target?.title||snapshot.workspace)+'</h1><p>'+escape(snapshot.workspace)+'</p><p class="status">'+escape(status)+'</p>'+(review?'<section class="review"><strong>Snapshot review: '+escape(review.decision.toUpperCase())+'</strong><p>'+escape(review.reviewer)+' · '+escape(review.at)+'</p><p>'+escape(review.rationale)+'</p><p class="small">Review is bound to this exact target and dependency set. The name is operator-supplied, not identity-authenticated.</p></section>':'<p class="status">No review is bound to this draft.</p>')+records.map(r=>'<article><small>'+escape(r.id)+' · v'+r.revision+' · '+escape(r.kind)+' · '+escape(r.tier)+'</small><h2>'+escape(r.title)+'</h2><p>'+escape(r.summary)+'</p>'+detail(r)+'<p class="small">Authored record state: '+escape(r.disposition)+'. Pinned inputs: '+escape(r.deps.map(d=>d.id+'@'+d.revision).join(', ')||'source record')+'.</p></article>').join('')+'<footer><p>'+escape(snapshot.evidence_boundary)+'</p><p>Snapshot SHA-256: <small>'+escape(checksum||'not frozen')+'</small></p><p class="small">Prepared locally with Research Desk '+VERSION+'. Full machine data is expandable in the digital report and retained in the separate packet. No publication, purchase, trade or production effect was executed.</p></footer></body></html>';
}

async function encrypt(packet,password){assert(typeof password==='string'&&password.length>=12,'Use at least 12 characters.');const c=root.crypto||(typeof require!=='undefined'?require('node:crypto').webcrypto:null);const salt=c.getRandomValues(new Uint8Array(16)),iv=c.getRandomValues(new Uint8Array(12));const key=await c.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);const derived=await c.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},key,{name:'AES-GCM',length:256},false,['encrypt']);const bytes=new Uint8Array(await c.subtle.encrypt({name:'AES-GCM',iv},derived,enc.encode(canonical(packet))));const hex=a=>[...a].map(x=>x.toString(16).padStart(2,'0')).join('');return {schema:'second-run/encrypted-packet@1',kdf:'PBKDF2-SHA256',iterations:250000,salt:hex(salt),iv:hex(iv),ciphertext:hex(bytes)};}
async function decrypt(data,password){assert(data.schema==='second-run/encrypted-packet@1'&&data.iterations===250000,'Unsupported encrypted format.');const unhex=s=>{assert(typeof s==='string'&&s.length%2===0&&/^[0-9a-f]+$/.test(s),'Invalid encryption encoding.');return Uint8Array.from(s.match(/../g).map(x=>parseInt(x,16)));};const c=root.crypto||(typeof require!=='undefined'?require('node:crypto').webcrypto:null),salt=unhex(data.salt),iv=unhex(data.iv);assert(salt.length===16&&iv.length===12,'Invalid encryption parameters.');const key=await c.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);const derived=await c.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},key,{name:'AES-GCM',length:256},false,['decrypt']);let b;try{b=await c.subtle.decrypt({name:'AES-GCM',iv},derived,unhex(data.ciphertext));}catch{throw new Error('Wrong password or altered encrypted packet.');}const packet=parse(new TextDecoder().decode(b));return verifyPacket(packet);}
const api={VERSION,SCHEMA,assert,canonical,clone,hash,parse,empty,state,latest,version,put,append,dependencyState,impact,fingerprint,reviewState,review,freeze,pack,verifyPacket,validateRun,validatePolicy,answer,grade,evaluate,compare,reprice,validateDeal,assessDeal,vllmSummary,csv,escape,reportHTML,encrypt,decrypt};
root.ResearchCore=api;if(typeof module!=='undefined')module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
