#!/usr/bin/env python3
"""Build findings.jsonl. Numbers are read from the intermediate JSON the analysis scripts wrote to $WORK, so nothing is
retyped except a few constants copied from a named source file (marked 'src:'). Evidence hashes are computed from disk
here (sha256 of the file as it exists now) except the two very large inputs, whose hashes were computed by the
streaming scripts (ix_extract.py, price_dispersion.py) in the same pass that read them.
Usage:  WORK=<dir with the *_result.json / _run*.json files> python make_findings.py"""
import json, os, hashlib
WORK = os.environ['WORK']
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..', '..'))          # .../axm-tools
MAIN = os.path.join(ROOT, 'main')
BIG = {  # sha256 of very large inputs, computed by the scripts that streamed them (input_sha256 / sha256 fields)
    'sessions/public-tail-20260929/lanes/inferencex-history/imported-main/inferencex-2026-09-29.jsonl': '1eab076241673432f84802d83597161aeb31420c95a87b49ae4b64accf69bf2f',
    'sessions/public-tail-20260929/lanes/opencomputeprices/rows/prices.jsonl': '390b25b1b25d59631166dae6273ba7b04c4a8645191002eafafe865afaa73bd0',
}
def J(name): return json.load(open(os.path.join(WORK, name), encoding='utf-8'))
def sha(rel):
    if rel in BIG: return BIG[rel]
    p = os.path.join(ROOT, rel)
    h = hashlib.sha256()
    with open(p, 'rb') as f:
        for b in iter(lambda: f.read(1 << 22), b''): h.update(b)
    return h.hexdigest()
def ev(*rels): return [{'path': r, 'sha256': sha(r)} for r in rels]
R = 'main/hot-aisle/campaign/results/'
C = 'main/hot-aisle/campaign/'
S = 'sessions/public-tail-20260929/lanes/'
rows = []
def F(id, kind, cls, claim, numbers, evidence, producer, conditions, implication, confidence, confirm, window):
    rows.append(dict(id=id, kind=kind, evidence_class=cls, claim=claim, numbers=numbers, evidence=evidence, producer=producer,
                     window=window, conditions=conditions, implication_for_a_shop=implication, confidence=confidence, what_would_confirm=confirm))
r2 = J('_run2_cells.json'); D, E = r2['default'], r2['explore']
r3 = J('_run3_arms.json'); tk = J('_run3_tokens.json'); ut = J('_run3_util.json'); r1 = J('_run1_cells.json')
rd = lambda x, n=4: None if x is None else round(x, n)
# ---------------------------------------------------------------- T01 / T02 Run 2 forced vs auto
cells = []
for c, e in E.items():
    for base in (c, c.replace('-r0', '-r1')):
        if base in D and (base == c or c.startswith('cell-long')):
            d = D[base]
            cells.append({'cell': c.replace('cell-', '').replace('-r0', ''), 'auto_run': base.replace('cell-', ''), 'auto_req_s': rd(d['req_s']), 'forced_req_s': rd(e['req_s']), 'delta_pct': rd((e['req_s']/d['req_s']-1)*100, 1),
                          'ttft_p50_ms_auto_forced': [rd(d['ttft_p50'], 0), rd(e['ttft_p50'], 0)], 'ttft_p95_ms_auto_forced': [rd(d['ttft_p95'], 0), rd(e['ttft_p95'], 0)], 'ttft_p99_ms_auto_forced': [rd(d['ttft_p99'], 0), rd(e['ttft_p99'], 0)],
                          'e2e_p95_ms_auto_forced': [rd(d['e2e_p95'], 0), rd(e['e2e_p95'], 0)], 'peak_kv_pct_auto_forced': [d['peak_kv_pct'], e['peak_kv_pct']]})
F('T01', 'telemetry', 'measured', 'Run 2 (Llama-3.3-70B FP8, 1x MI300X, vLLM 0.30.0): forcing --attention-backend ROCM_AITER_FA over the auto-selected ROCM_ATTN changes throughput per cell as listed; the 46% headline is one cell and the sign and size depend on cell.',
  {'cells': cells, 'note': 'auto has two repeats for long cells (r0, r1) and one for short cells; forced has one repeat (r0). Repeat-to-repeat spread on auto: long-c8 0.2179 vs 0.2157 req/s, long-c32 0.3032 vs 0.3016 req/s.', 'unit_req_s': 'requests/second', 'prompts_per_cell': {'long': '16 at c1, 64 at c8, 128 at c32', 'short': '16 at c1, 64 at c8, 128 at c32, 256 at c64'}},
  ev(R+'run2-hotaisle-mi300x/arm-log.txt', R+'run2-explore-hotaisle-mi300x/arm-log.txt', R+'run2-hotaisle-mi300x/cell-long-c32-r0.json', R+'run2-hotaisle-mi300x/cell-long-c32-r1.json', R+'run2-explore-hotaisle-mi300x/cell-long-c32-r0.json', R+'run2-hotaisle-mi300x/serve.log', R+'run2-explore-hotaisle-mi300x/serve.log', R+'run2-explore-hotaisle-mi300x/env.json', R+'run2-hotaisle-mi300x/env.json'),
  'ours', 'Same host enc1-gpuvm002, same image vllm/vllm-openai-rocm sha256:2e7da1ad..., same flags except --attention-backend. Auto arm ran 19:11-22:00 UTC, forced arm 22:01-22:26 UTC on 2026-09-23 (about 2.5 h later). Forced arm is post-hoc and unregistered (EXPLORE.md).', 'Attention backend is a per-workload choice: measure both on your own prompt shape before fixing it. The gain is largest where the KV cache is nearly full or prompts are long (long c8 +28%, long c32 +46%) and small on short prompts (+2.5% to +11%).', 'high for the deltas on these cells (auto repeats agree within 1%); low that they transfer', 'A frozen confirmation run: 3 repeats of forced and auto interleaved in one session, on the same cells.', '2026-09-23 19:17-22:26 UTC')
F('T02', 'telemetry', 'measured', 'In Run 2 the forced backend did not leave c1 unchanged in latency: time to first token fell 12.5% (long) and 7.7% (short) at c1 while requests/second stayed within 0.4%.',
  {'long_c1_ttft_p50_ms_auto_r0_r1_forced': [D['cell-long-c1-r0']['ttft_p50'], D['cell-long-c1-r1']['ttft_p50'], E['cell-long-c1-r0']['ttft_p50']], 'short_c1_ttft_p50_ms_auto_forced': [D['cell-short-c1-r0']['ttft_p50'], E['cell-short-c1-r0']['ttft_p50']],
   'long_c1_req_s_auto_r0_r1_forced': [D['cell-long-c1-r0']['req_s'], D['cell-long-c1-r1']['req_s'], E['cell-long-c1-r0']['req_s']], 'long_c32_ttft_p95_ms_auto_r0_forced': [D['cell-long-c32-r0']['ttft_p95'], E['cell-long-c32-r0']['ttft_p95']], 'long_c32_ttft_p99_ms_auto_r0_forced': [D['cell-long-c32-r0']['ttft_p99'], E['cell-long-c32-r0']['ttft_p99']]},
  ev(R+'run2-hotaisle-mi300x/cell-long-c1-r0.json', R+'run2-hotaisle-mi300x/cell-long-c1-r1.json', R+'run2-explore-hotaisle-mi300x/cell-long-c1-r0.json', R+'run2-hotaisle-mi300x/cell-short-c1-r0.json', R+'run2-explore-hotaisle-mi300x/cell-short-c1-r0.json'),
  'ours', 'c1 cells have 16 prompts, so p95 and p99 sit at the maximum (DISCLOSURES).', 'DISCLOSURES says c1 was unchanged; that holds for throughput, not for first-token latency. Interactive single-stream users see the backend even when batch throughput does not move.', 'medium (16 prompts per c1 cell, one forced repeat)', 'Repeat c1 with at least 200 prompts, forced and auto interleaved.', '2026-09-23')
# ---------------------------------------------------------------- T03 Run 3 forced vs auto
a0, a1, n0 = r3['run3-scored-a-t0'], r3['run3-scored-a-t1'], r3['run3-scored-n-t0']
F('T03', 'telemetry', 'measured', 'Run 3 (Qwen3-Coder-30B-A3B FP8, one hour of Azure code trace, 8,622 requests): on the short-prompt MoE the forced ROCM_AITER_FA arm is worse than auto on every latency percentile and accepted count; its 7 failures are client-side concurrency-limit events, not server errors.',
  {'ttft_ms_p50_p95_p99_from_send': {'A/T0 auto ROCM_ATTN': [rd(a0['ttft_from_send_ms']['50'], 1), rd(a0['ttft_from_send_ms']['95'], 1), rd(a0['ttft_from_send_ms']['99'], 1)], 'A/T1 forced ROCM_AITER_FA': [rd(a1['ttft_from_send_ms']['50'], 1), rd(a1['ttft_from_send_ms']['95'], 1), rd(a1['ttft_from_send_ms']['99'], 1)]},
   'ttft_ms_p50_p95_p99_from_scheduled_arrival': {'A/T0': [rd(a0['ttft_ms']['50'], 1), rd(a0['ttft_ms']['95'], 1), rd(a0['ttft_ms']['99'], 1)], 'A/T1': [rd(a1['ttft_ms']['50'], 1), rd(a1['ttft_ms']['95'], 1), rd(a1['ttft_ms']['99'], 1)]},
   'p99_ratio_forced_over_auto': rd(a1['ttft_from_send_ms']['99']/a0['ttft_from_send_ms']['99'], 3), 'p95_ratio': rd(a1['ttft_from_send_ms']['95']/a0['ttft_from_send_ms']['95'], 3),
   'accepted_auto_forced': [a0['accepted'], a1['accepted']], 'accepted_delta_pct': rd((a1['accepted']/a0['accepted']-1)*100, 2), 'correct_auto_forced': [a0['correct'], a1['correct']],
   'failed_forced': a1['errors'], 'failed_error_string': 'client_concurrency_limit x7 at request_index 2389-2430, end_ts == scheduled_ts', 'e2e_p95_ms_from_scheduled_auto_forced': [rd(a0['e2e_ms']['95'], 0), rd(a1['e2e_ms']['95'], 0)]},
  ev(R+'run3-scored-a-t0/replay/requests.jsonl', R+'run3-scored-a-t1/replay/requests.jsonl', R+'run3-scored-a-t0/detailed.json', R+'run3-scored-a-t1/detailed.json', R+'run3-scored-a-t0/grade/evaluation.json', R+'run3-scored-a-t1/grade/evaluation.json', R+'run3-scored-a-t1/serve.log'),
  'ours', 'One run per arm on one seat (enc1-gpuvm004), A/T0 00:45-01:45Z then A/T1 01:49-02:49Z on 2026-09-24. Client cap is 256 workers (load string workers=256).', 'Do not carry a tuning flag between workloads: on this workload forcing the vendor attention backend doubled p99 first-token latency (ratio shown) for no throughput gain. Also check whether a reported failure count is the server or your own load generator.', 'medium (single run; p99 of 8,622 is about 86 requests)', 'Three interleaved repeats per tier; raise the client worker cap above the burst peak so the 7 dropped requests are not confounded.', '2026-09-24 00:45-02:49 UTC')
# ---------------------------------------------------------------- T04 KV overload
def cell(c): return D[c]
F('T04', 'telemetry', 'measured', 'Run 2 KV-cache cells: long c32 already sits at 92% KV usage (32 x 8,704 tokens = 278,528 of a 300,192-token cache); c64 and c128 are past capacity, and doubling concurrency from c32 to c64 halves throughput and multiplies median first-token latency by 15.7. c64 and c128 measure overload, not capacity.',
  {'kv_cache_tokens_auto': 300192, 'kv_cache_tokens_forced': 299440, 'tokens_in_flight_by_construction_long': {'c8': 69632, 'c32': 278528, 'c64': 557056, 'c128': 1114112},
   'long_r0': {c: {'req_s': rd(cell('cell-long-'+c+'-r0')['req_s']), 'ttft_p50_s': rd(cell('cell-long-'+c+'-r0')['ttft_p50']/1000, 1), 'ttft_p95_s': rd(cell('cell-long-'+c+'-r0')['ttft_p95']/1000, 1), 'e2e_p50_s': rd(cell('cell-long-'+c+'-r0')['e2e_p50']/1000, 1), 'peak_kv_pct': cell('cell-long-'+c+'-r0')['peak_kv_pct'], 'max_waiting': cell('cell-long-'+c+'-r0')['max_waiting'], 'max_running': cell('cell-long-'+c+'-r0')['max_running'], 'duration_s': rd(cell('cell-long-'+c+'-r0')['dur_s'], 0)} for c in ('c1', 'c8', 'c32', 'c64', 'c128')},
   'throughput_c64_over_c32': rd(D['cell-long-c64-r0']['req_s']/D['cell-long-c32-r0']['req_s'], 3), 'throughput_c128_over_c64': rd(D['cell-long-c128-r0']['req_s']/D['cell-long-c64-r0']['req_s'], 3),
   'ttft_p50_c64_over_c32': rd(D['cell-long-c64-r0']['ttft_p50']/D['cell-long-c32-r0']['ttft_p50'], 1), 'preemption_lines_in_serve_log': 0,
   'short_c64_peak_kv_pct': D['cell-short-c64-r0']['peak_kv_pct']},
  ev(R+'run2-hotaisle-mi300x/serve.log', R+'run2-hotaisle-mi300x/arm-log.txt', R+'run2-hotaisle-mi300x/cell-long-c32-r0.json', R+'run2-hotaisle-mi300x/cell-long-c64-r0.json', R+'run2-hotaisle-mi300x/cell-long-c128-r0.json', C+'DISCLOSURES.md'),
  'ours', 'Peaks are read from 10-second vLLM log ticks ("GPU KV cache usage"), attributed to cells by arm-log start stamps (a stamp is written at cell start: next stamp minus this stamp equals duration plus about 15 s). max_running of 36 at c64/c128 is the KV-limited steady concurrency. DISCLOSURES calls c64/c128 overload; the c32 saturation is not stated there. Preemption count is not measured: vLLM does not log it at INFO and no metrics were scraped.', 'Size max concurrency from tokens in flight against the cache, not from GPU utilisation: past the cache limit you pay 2x the concurrency for half the throughput. Any tuning number taken at c32 on this workload is a near-saturated cell.', 'high for KV peaks and the throughput collapse; preemption itself unmeasured', 'Scrape vllm:num_preemptions_total and KV usage each second during the cells; repeat c32/c48/c64.', '2026-09-23 19:17-22:00 UTC')
# ---------------------------------------------------------------- T05 unequal software
F('T05', 'telemetry', 'measured', 'The arms never ran equal software. Run 1: AMD ran vLLM 0.27.1.dev5 (image rocm/vllm, tuned MI300X MoE config) against CUDA vLLM 0.30.0 (default FP8 MoE config); Run 2 and 3 AMD ran vLLM 0.30.0 in a different image. Run 3 has the same vLLM version on both vendors but different kernels selected: AITER FP8 MoE and AiterFp8BlockScaled GEMM on AMD; Triton FP8 MoE, FlashInfer/DeepGEMM FP8 GEMM and FLASH_ATTN on the H100.',
  {'run1': {'amd': {'vllm': '0.27.1.dev5+gf46a9dfe2.d20260827.rocm100', 'image': 'rocm/vllm@sha256:30761c2125ce150d556bef46406a0158446421886bf83a2e60154c6e4ca17a13', 'rocm': '7.2.4'}, 'nvidia': {'vllm': '0.30.0', 'image': 'vllm/vllm-openai@sha256:8a69ffad015f138d7170c4ddc429e230a3bc1c1719f67e14324749df200a4b90', 'driver': '580.173.02'}},
            'run2_run3_amd': {'vllm': '0.30.0', 'image': 'vllm/vllm-openai-rocm@sha256:2e7da1ad1c66836802072588adea75f9f4991da5f9545b4318e91d422c22ce6a', 'rocm': '7.2.3'},
            'run3_selected_kernels': {'A/T0': ['ROCM_ATTN (auto, TURBOQUANT overridden)', 'AiterFp8BlockScaledMMKernel', 'AITER Fp8 MoE backend'], 'A/T1': ['ROCM_AITER_FA (forced)', 'AiterFp8BlockScaledMMKernel', 'AITER Fp8 MoE backend'], 'N/T0': ['FLASH_ATTN', 'FlashInferFp8DeepGEMMDynamicBlockScaledKernel', 'TRITON Fp8 MoE backend', 'FlashInfer top-p/top-k sampling']},
            'run2_fp8_linear_kernel': 'RowWiseTorchFP8ScaledMMLinearKernel (torch fallback) on AMD in both auto and forced arms',
            'run1_serve_log_collected': False, 'run3_kv_cache_tokens': {'A/T0': 1484848, 'A/T1': 1484960, 'N/T0': 430592}},
  ev(R+'hotaisle-mi300x/env.normalized.json', R+'do-h100/env.normalized.json', R+'run2-hotaisle-mi300x/env.json', R+'run3-scored-a-t0/serve.log', R+'run3-scored-a-t1/serve.log', R+'run3-scored-n-t0/serve.log', R+'run3-scored-a-t0/invocation.json', C+'DISCLOSURES.md'),
  'ours', 'Run 1 kernel identity comes from DISCLOSURES (observed live, serve logs not collected); Run 2/3 kernel identity is read from serve.log selection lines. The Run 3 comparison is a different-complete-configuration comparison (MANUAL.md label), so it prices a stack, not a chip.', 'When a price gap is quoted between two vendors, name the kernels each stack selected; a stack change can move the answer as much as the price does (Run 2: attention backend alone moved throughput up to 46%).', 'high (serve.log selection lines)', 'Run each vendor with its best tuned kernels in a frozen tier design (T0 auto / T1 tuned) on both sides, as the Run 3 PREREG intended for AMD only.', 'Run 1 2026-09-23; Run 2 2026-09-23; Run 3 2026-09-24')
# ---------------------------------------------------------------- T06 E2E hold
hm, dh = r1, r1
def mx(arm): return max(r1['%s/%s' % (arm, c)]['derived_e2e_max_s'] for c in ('c1', 'c8', 'c32', 'c64'))
F('T06', 'telemetry', 'derived', 'Run 1 held the E2E gate on the AMD arm (the rocm/vllm 0.27.1.dev image writes no per-request latencies) and scored both arms on first-token time only. Derived AMD per-request E2E (ttft + sum of inter-token latencies) peaks at 5.34 s at c64, and the H100 at 7.38 s, both under the registered 15 s p95 gate, so the hold never changed a qualification.',
  {'derived_e2e_max_s': {'hotaisle-mi300x': rd(mx('hotaisle-mi300x'), 3), 'do-h100': rd(mx('do-h100'), 3)}, 'registered_gate_p95_e2e_s': 15,
   'per_cell_p95_e2e_field_ms_r0_r1_r2': {arm: {c: [rd(v, 0) for v in r1['%s/%s' % (arm, c)]['p95_e2el_ms']] for c in ('c1', 'c8', 'c32', 'c64')} for arm in ('hotaisle-mi300x', 'do-h100')},
   'amd_cells_have_latencies_list': False, 'nvidia_cells_have_latencies_list': True,
   'run3_e2e': 'Run 3 gates E2E <= 60 s from scheduled arrival on all three arms; measured E2E p95 ms (from scheduled) A/T0 %s, A/T1 %s, N/T0 %s' % (rd(a0['e2e_ms']['95'], 0), rd(a1['e2e_ms']['95'], 0), rd(n0['e2e_ms']['95'], 0))},
  ev(R+'hotaisle-mi300x/cell-c64-r1.json', R+'do-h100/cell-c64-r0.json', R+'run1-engine/hotaisle-mi300x.ttft1000.json', R+'run1-engine/do-h100.ttft1000.json', C+'DISCLOSURES.md'),
  'ours', 'The AMD cell JSONs carry aggregate p95_e2el_ms fields but no per-request latencies list; derived E2E uses ttfts and itls lists. The Run 1 ledger says the gate was held on both arms for symmetry, but its H100 cell rows say e2e_gate "applied"; the engine files (e2e_ms null) match the "held" statement.', 'A held gate costs nothing here, but say so with the number: the derived peak is a third of the gate. If your engine image drops per-request latency, log it yourself before the run.', 'high', 'Rerun the AMD arm on the 0.30.0 image, which writes latencies.', '2026-09-23 17:50-19:01 UTC')
# ---------------------------------------------------------------- T07 accepted vs scheduled
def share(a, k): return rd(a[k]/a['scheduled'], 4)
F('T07', 'telemetry', 'derived', 'Run 3 accepted count is a correctness count: 99.2% of rejected requests on A/T0 failed the EvalPlus tests; only 35 of 8,622 (0.41%) were correct but late, and all 35 fall in the first 5-minute window of the hour. The same holds on the other arms (42, 49).',
  {'scheduled': 8622, 'A/T0': {'accepted': a0['accepted'], 'accepted_share': share(a0, 'accepted'), 'correct': a0['correct'], 'incorrect': a0['incorrect'], 'rejected': a0['rejected_total'], 'rejected_because_incorrect_share': rd(a0['rejected_incorrect_share_of_rejected'], 4), 'correct_but_ttft_gt_1s': a0['correct_but_ttft_gt1s'], 'correct_but_e2e_gt_60s': a0['correct_but_e2e_gt60s'], 'late_by_5min_bucket': a0['correct_not_accepted_by_5min_bucket'], 'by_task_class': a0['class']},
   'A/T1': {'accepted': a1['accepted'], 'correct_but_late': a1['correct_not_accepted'], 'late_by_5min_bucket': a1['correct_not_accepted_by_5min_bucket']}, 'N/T0': {'accepted': n0['accepted'], 'correct_but_late': n0['correct_not_accepted'], 'late_by_5min_bucket': n0['correct_not_accepted_by_5min_bucket']},
   'humaneval_accept_share_A/T0': rd(a0['class']['HumanEval']['acc']/a0['class']['HumanEval']['n'], 4), 'mbpp_accept_share_A/T0': rd(a0['class']['Mbpp']['acc']/a0['class']['Mbpp']['n'], 4), 'task_mix': {'HumanEval': 2624, 'Mbpp': 5998}},
  ev(R+'run3-scored-a-t0/replay/requests.jsonl', R+'run3-scored-a-t0/grade/evaluation.json', R+'run3-scored-a-t0/grade/buckets.json', R+'run3-scored-a-t1/grade/evaluation.json', R+'run3-scored-n-t0/grade/evaluation.json', R+'run3-scored-n-t0/replay/requests.jsonl'),
  'ours', 'Accepted = EvalPlus base+plus pass and first token <= 1 s and done <= 60 s from scheduled arrival (replay.py). Recomputed from requests.jsonl and evaluation.json; counts reproduce 4,336 / 4,292 / 4,280 exactly.', 'On this workload the latency gates barely bind; the price per accepted request is a price per correct request. Quality of the output contract sets the denominator far more than serving does (see T15).', 'high', 'Recompute with replay.py buckets; already reproduced from raw request rows here.', '2026-09-24')
# ---------------------------------------------------------------- T08 TTFT per arm
def tt(a): return {'from_scheduled_arrival': [rd(a['ttft_ms'][p], 1) for p in ('50', '95', '99')], 'from_send': [rd(a['ttft_from_send_ms'][p], 1) for p in ('50', '95', '99')], 'max_ms': rd(a['ttft_max_ms'], 0), 'send_lag_ms_p50_p95_p99': [rd(a['send_lag_ms'][p], 1) for p in ('50', '95', '99')]}
F('T08', 'telemetry', 'measured', 'Run 3 first-token time p50/p95/p99 (ms): Hot Aisle auto 53/155/569, forced 60/202/1119, DigitalOcean H100 35/76/2234. The front door shows p50 and p99 only; the H100 has the best p50 and p95 and the worst p99 by 3.9x against the MI300X auto arm.',
  {'A/T0': tt(a0), 'A/T1': tt(a1), 'N/T0': tt(n0), 'p99_H100_over_MI300X_auto': rd(n0['ttft_from_send_ms']['99']/a0['ttft_from_send_ms']['99'], 2), 'p95_H100_over_MI300X_auto': rd(n0['ttft_from_send_ms']['95']/a0['ttft_from_send_ms']['95'], 3), 'published_p99_ms': {'A/T0': 571, 'N/T0': 2254}, 'unit': 'ms'},
  ev(R+'run3-scored-a-t0/detailed.json', R+'run3-scored-a-t1/detailed.json', R+'run3-scored-n-t0/detailed.json', R+'run3-scored-a-t0/replay/requests.jsonl', R+'run3-scored-n-t0/replay/requests.jsonl', 'main/hot-aisle/campaign/results/RUN3-RESULTS.md'),
  'ours', 'Two clocks: from send (detailed.json ttfts, what the page engine reports) and from scheduled arrival (includes client send lag; the acceptance rule uses scheduled). RUN3-RESULTS prints 571 and 2,254 ms for p99; recomputation gives 568.9 and 2,233.6 ms from send and 572.6 and 2,234.2 ms from scheduled, so the published figures are within 0.9% of either clock (probably a different percentile interpolation).', 'Ask a provider for p95 as well as p99: the H100 p95 of 76 ms and p99 of 2.2 s describe two different services. Acceptance at a 1 s gate is decided in that tail.', 'high', 'Rerun N/T0 with a second repeat to see whether the 2.2 s p99 is the burst schedule or the seat.', '2026-09-24 00:45-05:16 UTC')
# ---------------------------------------------------------------- T09 Run1 TTFT per cell
def r1c(arm, c, k): return r1['%s/%s' % (arm, c)][k]
F('T09', 'telemetry', 'measured', 'Run 1 per-cell first-token time: the H100 is faster at c1 (p50 67 vs 102 ms) but slower from c8 up (p50 223-244 vs 85-98 ms at c8; 468-509 vs 173-216 ms at c64), and at c64 118 of 600 H100 requests miss the 1 s gate (p95 1.89-1.91 s) against 0 of 600 on the MI300X.',
  {arm: {c: {'ttft_p50_ms_r0_r1_r2': [rd(v, 0) for v in r1c(arm, c, 'p50_ttft_ms')], 'ttft_p95_ms': [rd(v, 0) for v in r1c(arm, c, 'p95_ttft_ms')], 'ttft_p99_ms': [rd(v, 0) for v in r1c(arm, c, 'p99_ttft_ms')], 'req_s': [rd(v, 3) for v in r1c(arm, c, 'request_throughput')], 'requests_over_1s_ttft_of_600': r1c(arm, c, 'ttft_gt_1s')} for c in ('c1', 'c8', 'c32', 'c64')} for arm in ('hotaisle-mi300x', 'do-h100')},
  ev(*[R+'%s/cell-%s-r%d.json' % (arm, c, r) for arm in ('hotaisle-mi300x', 'do-h100') for c in ('c1', 'c64') for r in (0,)], R+'run1-engine/do-h100.ttft1000.json'),
  'ours', 'Random 2048-in/256-out prompts, 200 per cell, 3 repeats, different vLLM versions (T05). Per-cell values listed for each repeat.', 'The tail metric that decides a latency gate is concurrency-dependent and vendor-dependent; a single-concurrency benchmark (c1) would have ranked these seats the other way round from c64.', 'high (three repeats agree within about 10%)', 'Repeat on equal software (T05).', '2026-09-23 17:50-19:01 UTC')
# ---------------------------------------------------------------- T10 provisioning
F('T10', 'telemetry', 'measured', 'Time-to-SSH and time-to-ready per provider from the ledger and closures (single observations): DigitalOcean H100 60 s (Run 1, console, approximate) and 83 s (Run 3, API; active at 56 s); Hot Aisle 122 s (Run 3). Time from SSH to a ready server was 3.7x to 4.9x longer than time to SSH on the two seats where both are known.',
  {'digitalocean_h100_nyc2': {'run1_request_to_ssh_s': 60, 'run3_request_to_active_s': 56, 'run3_request_to_ssh_s': 83, 'run3_ssh_to_ready_s': 406, 'run3_ssh_to_ready_over_request_to_ssh': rd(406/83, 2), 'run1_ssh_to_ready_min': 9.97, 'create_success': '2 of 2 delivered attempts', 'run3_api_listing_at_04:08:02Z': 'regions=[] (no capacity) yet create at 04:08:03Z succeeded'},
   'hotaisle_enc1_1x': {'run3_request_to_ssh_s': 122, 'run3_smoke_ssh_to_ready_s': 457, 'run3_smoke_ssh_to_ready_over_request_to_ssh': rd(457/122, 2), 'run3_a_t1_restart_to_ready_min': 3.7, 'run1_request_to_ssh': 'not recorded', 'create_success': '2 of 2 delivered (Run 1 2026-09-23 18:17 UTC, Run 3 2026-09-24 00:08 UTC)'},
   'digitalocean_mi300x_h200': 'never delivered: out_of_capacity in all sampled regions on 2026-09-23 and by API on 2026-09-24 (see T11)'},
  ev(C+'availability/observations.jsonl', R+'run3-scored-n-t0/closure.json', R+'run3-scored-n-t0/ledger-times.json', R+'run3-smoke-a-t0/ledger-times.json', R+'run3-scored-a-t1/ledger-times.json', C+'ledger/examples/run1-do-h100.ledger.json', C+'results/RUN3-HOTAISLE-SUMMARY.md'),
  'ours', 'n=1 per provider per run; Run 1 clocks before 19:00 UTC are approximate to a few minutes (availability README); ready = health check plus warm-up, so it includes image pull, weight download and compile. counter records mark measured_3x false for both providers.', 'Quote time-to-ready, not time-to-SSH: model download and compile add roughly 4 to 5 times more wait on a 30B FP8 model, and it is billed on both seats.', 'low to medium (one observation each)', 'Three timed create/ready cycles per shop, per PROTOCOL.md in the counter kit.', '2026-09-23/24')
# ---------------------------------------------------------------- T11 availability
F('T11', 'telemetry', 'measured', 'Availability rows disagree with delivery: DigitalOcean API listed gpu-h100x1-80gb as available=true with regions=[] at 04:08:02Z on 2026-09-24 and a create at 04:08:03Z succeeded in nyc2 (56 s to active). MI300X and H200 were out of capacity in every region checked on 2026-09-23 (2 MI300X regions, 6 H200 regions) and by API again on 2026-09-24 at 04:08 and 05:19 UTC.',
  {'observation_rows': 30, 'digitalocean_rows': 24, 'hotaisle_rows': 5, 'runpod_rows': 1, 'delivered_creates': {'digitalocean': 2, 'hotaisle': 2}, 'out_of_capacity_rows_digitalocean': {'gpu-mi300x1-192gb': 4, 'gpu-h200x1-141gb': 8, 'gpu-h100x8-640gb': 1}, 'h200_regions_out_of_capacity_2026-09-23': ['nyc2', 'ric1', 'tor1', 'mkc1', 'mem1', 'ams3'], 'listing_says_available_but_regions_empty_rows': 4, 'listing_then_delivered': '1 of 1 (h100 nyc2)', 'h100_create_frozen_browser_2026-09-23_19:14': 'selectable; create not completed (browser froze); arm skipped'},
  ev(C+'availability/observations.jsonl', C+'availability/README.md'),
  'ours', 'Counts computed from observations.jsonl by row. Listing rows are not attempts. The API available flag is configuration availability, not capacity (availability README, UNVERIFIED until compared with console observations); the H100 create is the first such comparison.', 'A listing is a claim, an SSH prompt is a measurement. Track both denominators, and plan for the SKU you can actually get in the window you need.', 'medium (one comparison)', 'Scheduled probes with paired create attempts over a week (probe.py exists).', '2026-09-23 17:49 to 2026-09-24 05:19 UTC')
# ---------------------------------------------------------------- T12 cost windows
F('T12', 'telemetry', 'modeled', 'Hot Aisle A/T0 cost per 1,000 accepted is $0.6908, $0.7201, $0.7434, $0.8971 or $1.0845 depending on which window sits in the denominator; the spread is 1.57x on the same 4,336 accepted requests. None is an invoice.',
  {'usd_per_1k_accepted': {'in_page_headline_replay_seconds_only': 0.6908, 'arm_script_window_no_provisioning': 0.7201, 'own_seat_equivalent_incl_provisioning_published_0.74': 0.7434, 'whole_shared_seat_request_to_delete_9086_accepted_published_0.90': 0.8971, 'ledger_modeled_lower_bound_ssh_to_work_end': 1.0845},
   'windows': {'in_page': '3,606.58 s replay = 1.2022 accepted/s x 2.99/h; the page prints cost basis $3.00', 'own_seat_equivalent': '2.03 min request->SSH + 62.65 min script = 64.68 min = $3.2235', 'arm_script_only': '62.65 min = $3.1221', 'whole_seat': '163.57 min (00:08:55Z-02:52:29Z) = $8.1511 over 4,336+4,292+458 accepted', 'ledger_lower_bound': '94.37 min (t_ssh 00:10:57Z to t_work_end 01:45:19Z) = $4.7026, includes the 34 min of smoke and warm-up before A/T0 started'},
   'A/T1': {'ledger_lower_bound_usd_per_1k': 1.838, 'own_window_usd_per_1k': 0.7314, 'own_window_incl_provisioning_usd_per_1k': 0.7550, 'ledger_lower_bound_window_min': 158.3},
   'DigitalOcean_N/T0': {'request_to_release_min': 69.82, 'usd_per_1k': 1.1990, 'script_window_min_usd_per_1k': [66.03, 1.1339], 'replay_seconds_only_usd_per_1k_derived': 1.0322},
   'rate_usd_per_gpu_hour': {'hot_aisle': 2.99, 'digitalocean_h100': 4.41}, 'ratio_max_over_min_A/T0': rd(1.0845/0.6908, 2),
   'run1_windows_usd_per_1k': {'hotaisle_c64_cell_steady': 0.0717, 'do_h100_c32_cell_steady': 0.1526, 'hotaisle_whole_run_lower_bound': 0.9248, 'do_h100_whole_run_lower_bound': 0.9802}},
  ev(R+'RUN3-RESULTS.md', R+'RUN3-HOTAISLE-SUMMARY.md', 'main/hot-aisle/data/run3/headline.json', R+'run3-scored-a-t0/ledger/run3-run3-scored-a-t0.ledger.json', R+'run3-scored-a-t1/ledger/run3-run3-scored-a-t1.ledger.json', R+'run3-scored-n-t0/ledger/run3-run3-scored-n-t0.ledger.json', R+'run3-scored-a-t0/ledger-times.json', R+'run3-scored-a-t1/ledger-times.json', R+'run3-smoke-a-t0/ledger-times.json', R+'run3-scored-n-t0/ledger-times.json', C+'shop-eval/MANUAL.md'),
  'ours', 'All at undiscounted list ($2.99 credit-paid; $4.41 self-paid), recomputed by telemetry_costs.py from ledger-times.json. $0.72 (RUN3-HOTAISLE-SUMMARY) and $0.74 (RUN3-RESULTS, receipt) differ by exactly the 2.03 min provisioning. $1.0845 is the builder default that charged A/T0 for the seat time before it started; the summary file records the fix needed. MANUAL.md says not to average these.', 'Report the window with the number. A shop that quotes the replay-seconds figure ($0.69) and one that quotes request-to-release ($0.74 to $0.90) are 30% apart for the same run; the ledger lower bound is 57% above the in-page figure.', 'high for arithmetic; the invoice is the missing check', 'Reconcile the Hot Aisle and DigitalOcean invoices against the modeled windows (MANUAL.md items a-d).', '2026-09-24 00:08-05:17 UTC')
# ---------------------------------------------------------------- T13 price change
F('T13', 'telemetry', 'modeled', 'Hot Aisle 1x/2x/4x MI300X on-demand went from $1.99 to $2.99 per GPU-hour on 2026-07-27 in the aggregator series (+50.3%). Recomputed at the dated price with no GPU rerun, the Run 3 Hot Aisle cost per 1,000 accepted moves from $0.4948 to $0.7434 and its advantage over DigitalOcean H100 at the aggregator price ($3.39) from 46.3% to 19.3%; at the as-run $4.41 it is 38.0%.',
  {'ha_price_usd_per_gpu_hr': [1.99, 2.99], 'change_pct': rd((2.99/1.99-1)*100, 2), 'ha_usd_per_1k_accepted': [0.4948, 0.7434], 'do_h100_usd_per_1k_at_3.39': 0.9216, 'do_h100_usd_per_1k_at_4.41_as_run': 1.199, 'ha_cheaper_by_pct': {'at_1.99_vs_3.39': 46.3, 'at_2.99_vs_3.39': 19.3, 'as_run_2.99_vs_4.41': 38.0}, 'tie_h100_price_usd_per_hr_at_ha_2.99': 2.7345, 'tie_h100_price_usd_per_hr_at_ha_1.99': rd(0.4948/(1.199/4.41), 3),
   'july_2026_monthly_median_ha': 1.99, 'series_rows': {'1.99': 'first 2026-03-22 last 2026-07-27, 118 days', '2.99': 'first 2026-07-27 last 2026-07-29, 3 days'}, 'ha_8x_1.99_on_demand_last_seen': '2026-05-20', 'ha_8x_3.39_reserved': 'first 2026-05-20 through 2026-07-29', 'do_mi300x_aggregator_price_usd': 1.99, 'do_mi300x_staged_price_in_disclosures_usd': 2.59},
  ev(C+'market/RUN3-ECONOMICS-BY-DATE.jsonl', C+'market/MARKET.md', S+'opencomputeprices/rows/prices.jsonl', C+'DISCLOSURES.md'),
  'ours', 'Price series is imported (getdeploying feed for Hot Aisle and the DigitalOcean comparator), not provider quotes; the cost rows are our modeled recomputation on the retained accepted counts 4,336 and 4,280 and intervals 64.68 and 69.82 min. Tie prices computed from unrounded costs (RUN3-RESULTS and the receipt print $2.72 from rounded 0.74 and 1.20; unrounded gives $2.73). DO MI300X appears at $1.99 in the series and at $2.59 in the staged provider table the DISCLOSURES cite.', 'The winner of a cost comparison can move by 27 points on a provider list-price change while the hardware result is unchanged: keep price as a dated input, publish the tie price, and re-run the arithmetic when the list moves.', 'high for arithmetic; medium for the series being the true public price', 'Provider price page snapshots on 2026-07-26 and 2026-07-28.', '2026-03-22 to 2026-07-29 (series); Run 3 2026-09-24')
# ---------------------------------------------------------------- T14 operating point
hc1, hc64 = 1.6751, 0.0717
F('T14', 'telemetry', 'derived', 'Run 1 steady-state cost per 1,000 requests at list price is 23.4x higher at c1 than at c64 on the MI300X ($1.6751 vs $0.0717), and 9.3x higher at c1 than at c32 on the H100 ($1.4253 vs $0.1526). The 53% Hot Aisle advantage is a cell-to-cell figure; whole-run it is 5.7%.',
  {'hotaisle': {'c1': 1.6751, 'c8': 0.2751, 'c32': 0.1057, 'c64': 0.0717, 'unit': 'USD per 1,000 accepted at list, steady-state cell'}, 'do_h100': {'c1': 1.4253, 'c8': 0.3076, 'c32': 0.1526, 'c64': 0.1443, 'c64_accepted_pct': 80.3, 'c32_accepted_pct': 97.5},
   'ratio_c1_over_best': {'hotaisle_c1_over_c64': rd(1.6751/0.0717, 2), 'h100_c1_over_c32': rd(1.4253/0.1526, 2)}, 'h100_cheapest_qualifying_cell': 'c32 (registered rule: p95 TTFT <= 1000 ms, p95 E2E <= 15 s, failed <= 1%)', 'cell_level_gap_pct': 53.0, 'whole_run_gap_pct': 5.7, 'hotaisle_c1_costs_more_than_h100_c1_pct': 17.5},
  ev(R+'run1-engine/hotaisle-mi300x.ttft1000.json', R+'run1-engine/do-h100.ttft1000.json', C+'ledger/examples/run1-hotaisle-mi300x.ledger.json', C+'ledger/examples/run1-do-h100.ledger.json', C+'DISCLOSURES.md'),
  'ours', 'Steady-state cell cost = rate / (accepted per second) with no setup; H100 c64 cost 0.1443 counts only accepted (80.3%) requests, so it is cheaper per accepted than c32 only by a rejection-adjusted measure; registered rule disqualifies it. Random 2048/256 workload; latency-only acceptance.', 'The largest cost lever measured is not the vendor: it is running at a concurrency where the GPU is busy inside the latency gate. Publish the cost curve over concurrency, not one point.', 'high', 'Already three repeats per cell; add c16 and c48 to locate the knee.', '2026-09-23')
# ---------------------------------------------------------------- T15 token waste
F('T15', 'telemetry', 'measured', 'Run 3 A/T0: 67.2% of all decode tokens were spent on requests that failed grading; 12.3% of requests ended at the 1,024-token cap, consumed 41.0% of decode tokens, and passed 18.4% (vs 55.2% for stop-terminated). After evalplus.sanitize, HumanEval+ pass rises from 24.4% to 82.4% and total correct from 4,371 to 6,192 (+41.7%) with the same completions.',
  {'A/T0': tk['run3-scored-a-t0'], 'A/T1_length_share_of_tokens': rd(tk['run3-scored-a-t1']['length_share_of_tokens'], 4), 'N/T0_length_share_of_tokens': rd(tk['run3-scored-n-t0']['length_share_of_tokens'], 4),
   'posthoc_sanitized': {'humaneval_plus_pass_pct_raw_sanitized': [24.4, 82.4], 'humaneval_sanitized_pass_recomputed': '2161/2624 = 82.36%', 'mbpp_plus_pass_pct_raw_sanitized': [62.2, 67.2], 'correct_raw_sanitized': [4371, 6192], 'correct_gain_pct': rd((6192/4371-1)*100, 1)}},
  ev(R+'run3-scored-a-t0/replay/requests.jsonl', R+'run3-scored-a-t0/grade/evaluation.json', R+'run3-scored-a-t0/posthoc-sanitized/humaneval-sanitized_eval_results.json', R+'run3-scored-a-t0/posthoc-sanitized/README.md', R+'RUN3-RESULTS.md'),
  'ours', 'max_tokens 1024, temperature 0.2, raw function-completion prompts; sanitizer regrade is post-hoc and counts correctness only, not the deadline-qualified accepted count (RUN3-RESULTS correction). Token shares are computed from output_tokens per request.', 'Two-thirds of decode work bought nothing gradeable. A stop sequence or output contract that ends generation at the function body attacks cost and correctness together, before any GPU choice.', 'high for shares; the accepted-count effect of sanitizing is unmeasured', 'Rerun with stop sequences and the sanitizer in the client; recompute the deadline-qualified accepted count.', '2026-09-24')
# ---------------------------------------------------------------- T16 burst under-utilisation
F('T16', 'telemetry', 'derived', 'Run 3 server never queued: waiting requests were 0 at every 10-second log tick on all three arms; peak running 129/141/147 of a 256 cap; peak KV usage 3.6%/3.8%/13.2%. Median generation throughput was 882/946/915 tok/s against a 10-second peak of 7,808/7,566/8,693 tok/s (8.9x/8.0x/9.5x), and mean throughput over the hour (2,649,637 tokens / 3,606.6 s = 735 tok/s) is 9.4% of the A/T0 peak.',
  {'A/T0': ut['run3-scored-a-t0'], 'A/T1': ut['run3-scored-a-t1'], 'N/T0': ut['run3-scored-n-t0'], 'peak_over_median': {k: rd(v['gen_tok_s_max']/v['gen_tok_s_median'], 2) for k, v in ut.items()}, 'A/T0_mean_gen_tok_s': rd(2649637/3606.5797, 1), 'A/T0_mean_over_peak': rd((2649637/3606.5797)/ut['run3-scored-a-t0']['gen_tok_s_max'], 4), 'trace': '8,622 requests in 3,600 s at factor 0.95, up to 531 arrivals in a minute, gaps up to 217 s', 'max_num_seqs': 256},
  ev(R+'run3-scored-a-t0/serve.log', R+'run3-scored-a-t1/serve.log', R+'run3-scored-n-t0/serve.log', R+'RUN3-RESULTS.md'),
  'ours', 'vLLM logs a tick roughly every 10 s and only when active (214-217 ticks per hour), so instantaneous peaks between ticks are not seen. Different KV sizes per seat (1.48M tokens AMD, 0.43M H100).', 'A seat sized for the burst idles at about a tenth of its peak on average; the lever is smoothing arrivals or sharing the seat across workloads, not a faster GPU. Utilisation, not FLOPs, is the cost driver here.', 'medium (10-s ticks)', 'Per-second vllm:num_requests_running and tokens/s scrape during the run.', '2026-09-24')
# ---------------------------------------------------------------- T17 seat overhead
F('T17', 'telemetry', 'derived', 'Of the 163.57 minutes Hot Aisle billed on the shared Run 3 seat, 76.8% was scored work (A/T0 62.65 min + A/T1 63.00 min); the smoke (15.86 min) and 22.1 min of setup and gaps were the remaining 23.2%. Whole-seat cost per 1,000 accepted is $0.8971 against $0.7434 for the arm-equivalent window (+20.7%).',
  {'seat_min': 163.57, 'scored_min': rd(62.65+63.00, 2), 'smoke_min': 15.86, 'other_min': 22.1, 'scored_share_pct': 76.8, 'ssh_to_a_t0_ready_min': 34.17, 'a_t0_end_to_a_t1_ready_min': 3.7, 'a_t1_end_to_delete_min': 3.2, 'whole_seat_usd': 8.1511, 'whole_seat_accepted': 9086, 'whole_seat_usd_per_1k': 0.8971, 'own_window_usd_per_1k': 0.7434, 'overhead_pct': rd((0.8971/0.7434-1)*100, 1)},
  ev(R+'run3-scored-a-t0/ledger-times.json', R+'run3-scored-a-t1/ledger-times.json', R+'run3-smoke-a-t0/ledger-times.json', R+'RUN3-HOTAISLE-SUMMARY.md'),
  'ours', 'Derived from ledger-times script stamps and the summary request/delete times (00:08:55Z / 02:52:29Z); delete time is operator-reported, not an invoice line.', 'Setup, a smoke run and idle gaps are billed at the same rate as work: batch the scored arms in one boot and keep the smoke short, or price the overhead into the quote.', 'medium', 'Provider invoice line items for the seat.', '2026-09-24 00:08-02:52 UTC')
# ---------------------------------------------------------------- T18 spend records disagree
F('T18', 'telemetry', 'operator_report', 'Recorded Hot Aisle spend is not reconciled and the files give different totals: about $15 of the $200 credit for the 2026-09-23 seat (DISCLOSURES), $8.15 for the 2026-09-24 seat (RUN3-RESULTS), and a counter record that assigns modeled_cost_usd 15.0 to an evaluation dated 2026-09-24T00:08:55Z. DigitalOcean: $5.13 modeled for Run 3 (4.41 x 69.82 min) and $4.05 modeled for Run 1 arm B in the counter record; no invoice line is entered in any file.',
  {'ha_credit_spent_usd': {'2026-09-23_seat_disclosures': 15, '2026-09-24_seat_run3_results': 8.15, 'counter_record_modeled_cost_usd': 15.0}, 'ha_run1_seat_window_min_derived': rd(((22*60+35)-(18*60+17)), 0), 'ha_run1_seat_usd_at_list_derived': rd(((22*60+35)-(18*60+17))/60*2.99, 2), 'do_modeled_usd': {'run3': 5.1315, 'run1_arm_b_counter': 4.05, 'run1_ledger_lower_bound': 2.2222}, 'billed_usd_entered_anywhere': None, 'credit_total_usd': 200},
  ev(C+'DISCLOSURES.md', R+'RUN3-RESULTS.md', C+'shop-eval/counter/records/hotaisle-2026-09.json', C+'shop-eval/counter/records/digitalocean-2026-09.json', R+'run3-scored-n-t0/ledger/run3-run3-scored-n-t0.ledger.json'),
  'ours', 'Hot Aisle Run 1/2 seat window 18:17-~22:35 UTC on 2026-09-23 derived from the availability request stamp and the DISCLOSURES delete time (approximate). The counter record calls its $15 a historical compilation with no reconciled invoice.', 'Keep three fields per allocation (credit, modeled, invoice) as the ledger schema already requires, and do not publish a spend total until they agree.', 'high that they disagree; unknown which is right', 'Hot Aisle balance history and DigitalOcean invoice.', '2026-09-23/24')
# ---------------------------------------------------------------- T19 counter minimums
F('T19', 'telemetry', 'published_claim', 'Billing minimums and gates recorded in the counter records (not measured by us): Hot Aisle 1x VM per-minute with 1-minute minimum, 2x VM 1-hour minimum, 8x bare metal $3.39 per GPU-hour with a 1-month minimum; DigitalOcean per-second billing with the minimum disputed between its pricing page (5 min) and docs (60 s), new-account GPU Droplet limit 0 raised to 1 by a support ticket in under a day. Tenant hygiene, network posture and support response are unobserved for both.',
  {'ha_8x_bare_metal_month_min_usd_derived': rd(3.39*8*730, 0), 'ha_8x_month_hours_assumed': 730, 'do_quota_ticket_time': 'under a day (exact not recorded)', 'unobserved_fields': ['tenant_hygiene', 'network_path firewall posture', 'support response time', 'termination timing for DigitalOcean']},
  ev(C+'shop-eval/counter/records/hotaisle-2026-09.json', C+'shop-eval/counter/records/digitalocean-2026-09.json'),
  'ours', 'Counter records are compiled from campaign notes, evidence_class derived, every unobserved field is the string "unobserved" (a failure row and an unknown row must not collapse, MANUAL.md).', 'A 1-month minimum on 8x is about $19,800 of commitment at the listed rate; read minimums before you read the per-hour price.', 'low to medium (operator-reported)', 'Run the counter protocol on each shop.', '2026-09-23/24')
# ---------------------------------------------------------------- T20 HE vendor variance
F('T20', 'telemetry', 'measured', 'Run 3 HumanEval+ correct counts differ by vendor stack more than by tier: 640 (A/T0), 635 (A/T1), 569 (N/T0) of 2,624; MBPP+ 3,731 / 3,699 / 3,760 of 5,998. One run per arm at temperature 0.2, so run-to-run noise is not separated.',
  {'humaneval_correct': [a0['class']['HumanEval']['correct'], a1['class']['HumanEval']['correct'], n0['class']['HumanEval']['correct']], 'mbpp_correct': [a0['class']['Mbpp']['correct'], a1['class']['Mbpp']['correct'], n0['class']['Mbpp']['correct']], 'he_n0_vs_a0_pct': rd((569/640-1)*100, 1), 'he_a1_vs_a0_pct': rd((635/640-1)*100, 1)},
  ev(R+'run3-scored-a-t0/grade/evaluation.json', R+'run3-scored-a-t1/grade/evaluation.json', R+'run3-scored-n-t0/grade/evaluation.json'),
  'ours', 'Same seeds (700000 + request index), same tasks, different kernels (T05).', 'A price-per-accepted comparison across stacks embeds a correctness difference; report correctness per task class beside cost.', 'low (single run per arm)', 'Repeat each arm three times and test for a stack effect.', '2026-09-24')
# ---------------------------------------------------------------- T21 in-page headline
F('T21', 'telemetry', 'derived', 'The in-page report (data/run3/report.html, record rec-20260924T004243Z-run3at0) prices Hot Aisle at $0.6908 per 1,000 but carries the DigitalOcean H100 as price-only with no run and a required tie rate of $1.7732 per hour; the retained N/T0 run gives $1.0322 on the same replay-seconds basis, which would put Hot Aisle 33.1% cheaper on that basis (against 38.0% on the receipt basis).',
  {'in_page_ha_usd_per_1k': 0.6908, 'in_page_h100': {'runs': 0, 'price_only': True, 'required_rate_to_tie_usd_per_hr': 1.7732}, 'derived_h100_replay_seconds_usd_per_1k': 1.0322, 'derived_gap_pct': rd((1-0.6908/1.0322)*100, 1), 'receipt_gap_pct': 38.0, 'p95_e2e_ms_in_page': 12353.639},
  ev('main/hot-aisle/data/run3/headline.json', 'main/hot-aisle/data/run3/report.html', R+'receipt-run3.html', R+'run3-scored-n-t0/detailed.json'),
  'ours', 'The 1.7732 tie rate is computed inside the page from the A/T0 record alone; it does not use the N/T0 accepted count. 1.0322 is our derivation: 4.41 / 3600 / (4,280 / 3,606.39 s) x 1000.', 'The two public artefacts use two windows; a reader comparing them will not know that the same tie question has answers of $1.77 and $2.73.', 'high for arithmetic', 'Add the N/T0 record to the in-page report.', '2026-09-24 to 2026-09-29')
# ================================================================ MARKET
sp = J('ix_spread_result.json')['summary']; sk = J('ix_spread_result.json')['sku']
F('M01', 'market', 'derived', 'InferenceX: on 262 hardware x model x scenario x concurrency x precision keys where two or more frameworks report output throughput per GPU, the best-config-vs-best-config ratio between the best and worst framework has median 1.44x, p90 3.92x, and is at least 2x on 28.6% and at least 3x on 16.4% of keys (max 84.9x).',
  {'variant_all': sp['all'], 'keys_with_two_or_more_frameworks_any_rows': 269, 'keys_total': 2282, 'metric': 'output_throughput_per_gpu, tokens/s/GPU, best row per framework', 'most_common_best_worst_pairs': [['atom', 'vllm', 60], ['vllm', 'sglang', 28], ['sglang', 'vllm', 27], ['sglang', 'sglang-disagg', 20]]},
  ev('main/hot-aisle/campaign/backfill/IMPORT-SUMMARY.md', 'main/hot-aisle/campaign/backfill/imported/inferencex-2026-09-29.jsonl.POINTER.json', 'sessions/public-tail-20260929/lanes/inferencex-history/imported-main/inferencex-2026-09-29.jsonl'),
  'imported', 'Key = (hardware, model, scenario, ISL, OSL or dataset, concurrency, precision). The best row per framework may differ in TP/EP/GPU count/disaggregation/speculative decoding, so this is orchestration-and-config spread, not framework-only. Rows are upstream InferenceX results_bmk aggregates (imported, not our measurements). Extremes (tens of x) are dominated by rows that look like failed or misconfigured runs (e.g. sglang 0.1 tok/s/GPU on H200 GLM-5.2 at c3).', 'Framework and configuration choice moves per-GPU throughput by a median 44% on identical hardware and model; a shop that picks one stack without a sweep leaves that on the table half the time.', 'medium (public aggregates, config differs between compared rows)', 'Run the same model/scenario under two frameworks on one seat with identical parallelism (shop-eval arm).', 'InferenceX results_bmk artifacts created 2026-07-01 to 2026-09-29')
F('M02', 'market', 'derived', 'Restricting the InferenceX comparison to clean rows (error-drop <= 5%), best rows created within 7 days, and identical TP/EP/GPU-count/disagg/speculative settings leaves 35 keys with median 1.26x (p90 1.48x, max 2.12x); the spread that is framework alone is smaller than the spread that includes topology choices.',
  {'variants': sp, 'top_like_for_like': [{'key': t['key'], 'best': t['hi'], 'worst': t['lo'], 'ratio': rd(t['ratio'], 3), 'best_tok_s_gpu': rd(t['hi_v'], 1), 'worst_tok_s_gpu': rd(t['lo_v'], 1), 'days_apart': rd(t['days'], 1), 'rows': [t['hi_row'], t['lo_row']]} for t in J('ix_spread_result.json')['top_like_for_like'][:5]]},
  ev('main/hot-aisle/campaign/backfill/IMPORT-SUMMARY.md', 'sessions/public-tail-20260929/lanes/inferencex-history/imported-main/inferencex-2026-09-29.jsonl'),
  'imported', 'Clean = records_error_dropped / records_total <= 0.05 where reported. Same-week is a proxy for same software version; images differ.', 'Some of the spread is real framework difference (median 26%), the rest is topology and parallelism choice: both are decisions a shop makes, and both need a measured sweep.', 'medium', 'Same as M01 with images pinned.', 'as M01')
F('M03', 'market', 'derived', 'By SKU (all keys / clean same-week keys): H100 1 key, 1.65x; H200 21 keys median 1.25x (max 53.2x) / 18 keys median 1.22x; B200 27 keys median 1.53x (max 35.4x) / 16 keys 1.52x; MI300X 6 keys median 2.29x (max 36.1x) / 4 keys 12.6x. MI300X has only six comparable keys, driven by Qwen3-0.6B (vllm vs atom) and Qwen3.5-397B (sglang vs sglang-disagg).',
  {'by_sku': {k: sk[k] for k in ('H100', 'H200', 'B200', 'MI300X')}, 'mi300x_keys': 'Qwen3-0.6B fp16 128/32 at c1 and c4 (vllm 463.6 vs atom 12.9 tok/s/GPU at c1); Qwen3.5-397B-A17B-FP8 agentic-256k at c1,8,16,32 (sglang vs sglang-disagg 1.01-2.89x)'},
  ev('main/hot-aisle/campaign/backfill/IMPORT-SUMMARY.md', 'sessions/public-tail-20260929/lanes/inferencex-history/imported-main/inferencex-2026-09-29.jsonl'),
  'imported', 'The Qwen3-0.6B pair is a toy model at 128/32 tokens where the atom rows use 2 GPUs; do not read 36x as a serving fact.', 'On H100 and MI300X the public record is too thin to pick a framework from: a shop needs its own measured sweep.', 'low for MI300X and H100 (n<=6)', 'More MI300X InferenceX rows or our own sweep.', 'as M01')
F('M04', 'market', 'derived', 'InferenceX agentic-coding success: the headline success rate (profiled/total records) differs between frameworks on the same key by a median 2.6 points (p90 24.2, max 65.1), but that includes warmup drops; counting only error-dropped records the median spread is 0.05 points (p90 8.31, max 36.0).',
  {'agentic_keys_with_two_or_more_frameworks': 117, 'spread_pp_incl_warmup': {'median': 2.6, 'p90': 24.2, 'max': 65.1}, 'spread_pp_error_only': {'median': 0.05, 'p90': 8.31, 'max': 36.0}, 'import_summary_success_rates_examples': {'H200 sglang agentic-coding': '38.55% (13248/34368)', 'H200 vllm agentic-coding': '78.42%', 'MI300X sglang agentic-coding': '76.33%', 'MI300X vllm agentic-coding': '84.16%', 'B200 vllm agentic-coding': '71.84%', 'B300 vllm agentic-coding': '93.14%'}},
  ev('main/hot-aisle/campaign/backfill/IMPORT-SUMMARY.md', 'sessions/public-tail-20260929/lanes/inferencex-history/imported-main/inferencex-2026-09-29.jsonl'),
  'imported', 'IMPORT-SUMMARY states that agentic totals include warmup drops and are not an error rate. Fixed-sequence rows report success only as counts in some files (many "unknown"). Error-only figures come from request_accounting.records_error_dropped.', 'Do not read a published agentic success rate as reliability: separate warmup drops from errors before comparing stacks.', 'medium', 'Per-request logs for the compared runs.', 'as M01')
pt = J('price_trim_result.json'); pdj = J('price_dispersion_result.json')
def pdisp(g): return {'providers_incl_together': pdj['gpus'][g]['all_shapes']['n_providers'], 'median_of_provider_medians': rd(pdj['gpus'][g]['all_shapes']['provider_median_of_medians'], 3),
                      'excl_together': {k: (rd(v, 3) if isinstance(v, float) else v) for k, v in pt[g + '/all_shapes'].items()}, 'gpu_count_1_excl_together': {k: (rd(v, 3) if isinstance(v, float) else v) for k, v in pt[g + '/gpu_count_1'].items()}}
F('M05', 'market', 'derived', 'Same-SKU on-demand price dispersion across providers in July 2026 (per-provider medians, USD per GPU-hour, together excluded as a unit artefact): p90/p10 ratio 3.2x for H100 (41 providers, $1.50 to $12.84), 3.6x for H200 (32, $2.25 to $14.88), 3.0x for B200 (22, $3.74 to $42.20), 3.0x for MI300X (7, $1.99 to $7.86). Including Together AI rows ($100 and $200 per GPU-hour) the max/min ratios reach 66.7x (H100), 88.9x (H200) and 53.5x (B200).',
  {g: pdisp(g) for g in ('H100', 'H200', 'B200', 'MI300X')},
  ev('sessions/public-tail-20260929/lanes/opencomputeprices/rows/prices.jsonl', 'main/hot-aisle/campaign/market/MARKET.md', 'main/hot-aisle/campaign/market/market-stats.json'),
  'imported', 'On-demand rows with snapshot_ts in 2026-07 (last snapshot 07-29), 93,534 rows for the four SKUs; provider median over all its rows in the month, all shapes. Aggregator feeds (getdeploying, skypilot, shadeform and provider own feeds), not provider quotes. Hyperscalers dominate the top end. Median of provider medians reproduces MARKET.md (H100 2.99, H200 4.29, B200 6.49, MI300X 3.04).', 'The same silicon is sold at a 3x inter-decile spread; the cheapest quartile is not a niche. A shop that does not price-shop pays the median or worse, and a shop that compares prices without unit checks compares errors.', 'medium-high for the shape, low for any single provider figure', 'Provider price pages on a single date for a sample of providers.', '2026-07-01 to 2026-07-29')
F('M06', 'market', 'derived', 'Aggregators disagree on the same provider and SKU: DigitalOcean H100 x1 is $3.39 (getdeploying) vs $6.74 (skypilot), 1.99x, while our as-run list was $4.41; MassedCompute H100 $2.73 (shadeform) vs $10.92 (own feed) 4.0x; RunPod MI300X $1.34 (own feed) vs $2.19 (skypilot, getdeploying); Together AI H100 $3.99 (getdeploying) vs $100.00 (own feed) 25x. Of 26 provider-SKU pairs with two or more sources, 8 differ by 1.5x or more and 3 (all Together AI) by more than 24x.',
  {'top': [{'gpu': t['gpu'], 'provider': t['provider'], 'ratio': rd(t['ratio'], 2), 'source_medians_usd': {s: rd(v['median'], 2) for s, v in t['sources'].items()}, 'rows': {s: v['n'] for s, v in t['sources'].items()}} for t in pdj['aggregator_disagreement_1gpu'][:12]], 'pairs_with_two_or_more_sources': len(pdj['aggregator_disagreement_1gpu']), 'digitalocean_h100_prices_seen_usd': {'getdeploying': 3.39, 'skypilot': 6.74, 'as_run_pricing_page': 4.41}, 'digitalocean_mi300x_prices_seen_usd': {'getdeploying_series': 1.99, 'staged_in_DISCLOSURES': 2.59}},
  ev('sessions/public-tail-20260929/lanes/opencomputeprices/rows/prices.jsonl', 'main/hot-aisle/campaign/market/RUN3-ECONOMICS-BY-DATE.jsonl', 'main/hot-aisle/campaign/DISCLOSURES.md'),
  'imported', '1-GPU rows, July 2026 medians per (SKU, provider, source). skypilot may list a different shape (e.g. a larger instance divided by count); we did not resolve shapes.', 'Never price a comparison from one aggregator: retain every source value (the by-date file does) and compare within a source, then confirm on the provider page.', 'medium', 'Provider price pages for DigitalOcean, MassedCompute, RunPod on one date.', '2026-07')
F('M07', 'market', 'derived', 'Row-weighted medians mislead against provider medians: July 2026 H100 row median $8.99 vs provider-median $2.99 (3.0x), H200 $8.39 vs $4.29 (2.0x), B200 $8.06 vs $6.49 (1.2x); for MI300X the row median $2.19 is below the provider median $3.04 (RunPod contributes 378 of 922 rows).',
  {g: {'row_median': rd(pdj['gpus'][g]['all_shapes']['row_median'], 3), 'provider_median_of_medians': rd(pdj['gpus'][g]['all_shapes']['provider_median_of_medians'], 3), 'ratio': rd(pdj['gpus'][g]['all_shapes']['row_median']/pdj['gpus'][g]['all_shapes']['provider_median_of_medians'], 2), 'rows': pdj['gpus'][g]['all_shapes']['rows']} for g in ('H100', 'H200', 'B200', 'MI300X')},
  ev('sessions/public-tail-20260929/lanes/opencomputeprices/rows/prices.jsonl', 'sessions/public-tail-20260929/lanes/opencomputeprices/REPORT.md'),
  'imported', 'Undeduped snapshots (about 4/day from April); AWS, Azure and GCP multi-shape listings dominate row counts.', 'Any single "market price" figure hides which weighting produced it; pick the weighting that matches the buyer (one provider, one seat).', 'high', 'n/a', '2026-07')
ic = J('issues_classes_result.json')
def cls_row(c): return next(x for x in ic['classes'] if x['cls'] == c)
F('M08', 'market', 'derived', 'Error classes that recur in all four engines (vLLM 15,175 issues, llama.cpp 10,217, SGLang 7,640, TensorRT-LLM 4,043; 37,075 total): every class in the lane taxonomy appears in all four. First-match counts vLLM/llama.cpp/SGLang/TRT-LLM: build 1,842/1,934/1,623/711; crash 732/1,607/356/306; accuracy 833/642/712/226; performance regression 815/713/303/158; OOM 587/292/302/125; timeout 486/412/608/125; illegal memory access 312/80/191/40; CUDA error 578/318/206/156; install 743/411/329/234; NCCL 4,103/32/668/217 (vLLM inflated by environment dumps).',
  {'engines': {e: v['issues'] for e, v in ic['engines'].items()}, 'first_match_counts': {x['cls']: x['counts'] for x in ic['classes']}, 'any_match_counts': ic['any_match']},
  ev('sessions/public-tail-20260929/lanes/github-issues-deep/rows/issues.jsonl', 'sessions/public-tail-20260929/lanes/github-issues-deep/REPORT.md'),
  'imported', 'Issues only (search API), created 2024-07-12 to 2026-09-29 for vLLM (older missing; capped at 15,000+), repo creation onward for the others. Classes are regex on title+body by the lane; the rows retain the title, so we cannot re-run body regexes. "other" is the largest class in every engine (4,144 vLLM).', 'A shop running any of these engines will re-hit OOM, illegal-memory-access, timeout and accuracy problems that four communities are separately triaging; a shared, versioned failure register would be re-used by all of them.', 'medium (regex classification)', 'Hand-label a 200-issue sample per engine.', '2023-03 to 2026-09-29')
cl = ic['clusters']
F('M09', 'market', 'derived', 'Speculative-decoding issues by title match: 1,608 across the four engines (vLLM 783, SGLang 435, llama.cpp 255, TRT-LLM 135; 440 still open) and median 57.1 days to close; prefix-cache issues: 397 (vLLM 231, SGLang 149, TRT-LLM 12, llama.cpp 5; 125 open), median 60.5 days to close. Both are named as cross-engine failure clusters in the shallow lane report.',
  {'speculative_decoding': cl['speculative_decoding'], 'prefix_cache': cl['prefix_cache'], 'overall_median_days_close': rd(ic['overall_median_days_close'], 2), 'regex': {'spec': 'specul|mtp|draft model|eagle|medusa|ngram|spec decode|lookahead', 'prefix': 'prefix cach|prefix reuse|apc|radix|cache hit'}, 'shallow_lane_examples': ['vllm #53142 illegal memory access on prefix-cache resume (fix #55507)', 'vllm #53912 prefix caching + MTP corrupts output on hybrid Mamba/GDN', 'llama.cpp #27282 native MTP separate CUDA arena OOM (fix #27489)', 'llama.cpp #26558 draft-mtp crash (fix #27368)', 'vllm #56443 spec decode device-side assert (fix #56448)']},
  ev('sessions/public-tail-20260929/lanes/github-issues-deep/rows/issues.jsonl', 'sessions/public-tail-20260929/lanes/github-issues/REPORT.md'),
  'imported', 'Title-only regex is a lower bound and may include false positives ("draft" words); median days uses created_at to closed_at over closed issues and includes not_planned closures.', 'Speculative decoding and prefix caching are the features most shops turn on for cost, and they are the ones with the longest, most repeated failure history; turn them on only behind a correctness canary.', 'medium', 'Body-level classification of a sample.', '2023-03 to 2026-09-29')
co = ic['completed_only']
F('M10', 'market', 'derived', 'Open-to-close medians by class: 45.3 days over all 32,123 closed issues, but 18.8 days for issues closed as completed (23,907) against 121.8 days for not_planned (7,980); vLLM closed 5,881 of 12,625 (46.6%) as not_planned. By first-match class (completed-only median days): NCCL 6.4, build 15.3, install 16.2, crash 12.8, CUDA error 13.4, OOM 13.7, performance regression 20.7, accuracy 22.9, illegal memory access 25.0, timeout 28.4, other 32.8.',
  {'completed_only_by_class': co, 'all_closed_median_days_by_class': {x['cls']: rd(x['median_days_close_all'], 1) for x in ic['classes']}, 'overall_median_days_close': rd(ic['overall_median_days_close'], 2), 'state_reason_counts_closed': {'completed': 23907, 'not_planned': 7980, 'duplicate': 236}, 'vllm_closed': {'completed': 6646, 'not_planned': 5881, 'duplicate': 98}, 'median_days_by_state_reason': {'completed': 18.8, 'not_planned': 121.8, 'duplicate': 0.2}},
  ev('sessions/public-tail-20260929/lanes/github-issues-deep/rows/issues.jsonl'),
  'imported', 'A closed issue is not a verified fix: fix references exist for only 217 issues (lane report). Open issues are not in the medians.', 'A quarter of engine issues (not_planned) close without a fix after four months; a shop cannot wait for upstream on accuracy, timeout and illegal-memory faults, which take 3 to 4 weeks even when completed.', 'medium', 'Link issues to fix PRs via timeline API.', '2023-03 to 2026-09-29')
cr = J('cloudreview_shortfalls_result.json')
F('M11', 'market', 'derived', 'ClusterMAX cloud-review negative claims repeat across providers: of 72 providers with at least one negative claim (85 with any claim; 483 negative of 1,273), Slurm setup or scheduler gaps appear for 34, monitoring/observability for 32, networking/InfiniBand/NCCL for 32, node health checks/auto-drain for 31, Kubernetes for 28, reliability for 25, security/compliance attestation for 23, onboarding/UX for 21, storage for 20, ssh/root/login-node limits for 18.',
  {'providers_with_claims': cr['providers_with_claims'], 'providers_with_negative': cr['providers_with_negative'], 'claims': cr['claims'], 'negative_claims': cr['negative'], 'themes': [{'theme': t['theme'], 'providers': t['providers'], 'quotes': t['quotes'], 'example_ids': t['example_ids']} for t in cr['themes']]},
  ev('sessions/clustermax-cloudreview-20260929/claims.all.jsonl', 'sessions/clustermax-cloudreview-20260929/README.md'),
  'imported', 'Review text is ClusterMAX 2.0 (84 of 85 pages published 2025-11-06); stance -1 is the extractor label; themes are our keyword matches on the quote and can match a mention rather than a shortfall. SemiAnalysis legal notice restricts financial use of ratings; used here as text statistics only.', 'Every neocloud is independently rediscovering Slurm setup, monitoring, health checks and networking; a floor that specifies those once removes about a third of providers from the "repeat offender" list per item.', 'medium (keyword themes)', 'Manual coding of a 100-quote sample.', 'reviews published 2025-11-06; captured 2026-09-29')
ip = J('incident_patterns_result.json')
F('M12', 'market', 'derived', 'Public status-page incidents (25 files, 21 providers with at least one incident, 2,941 incidents, 1,859 non-maintenance) repeat by title pattern across providers: network/connectivity/DNS in 18 providers (311 non-maintenance incidents, median 2.35 h), generic outage/unavailable in 18 (368, 3.28 h), control plane/API/provisioning in 16 (304, 2.26 h), degraded performance in 16 (266, 3.78 h), storage in 14 (151, 4.95 h), console/dashboard in 12 (120, 1.66 h), GPU/node/host hardware in 10 (249, 4.08 h), Kubernetes/Slurm in 6 (59, 4.95 h).',
  {'files': len(ip['files']), 'incidents': ip['incidents'], 'non_maintenance': ip['nonmaintenance'], 'classes': [{k: v for k, v in c.items() if k != 'provider_names'} for c in ip['classes']]},
  ev('main/clustermax-challenge/retrospective/incidents/scaleway.json', 'main/clustermax-challenge/retrospective/incidents/crusoe-r2.json', 'main/clustermax-challenge/retrospective/incidents/digitalocean.json', 'main/clustermax-challenge/retrospective/incidents/gcore.json', 'main/clustermax-challenge/retrospective/incidents/SCHEMA.md'),
  'imported', 'Coverage windows differ (2025-01-01 to 2026-09-23/29, or 2026-01-01 onward, or null start); Scaleway alone contributes 1,066 incidents, so counts are not rates and providers-with-incident is the recurrence measure. Multi-label keyword classes on titles; CoreWeave and OVHcloud expose ten items via RSS only. Only the four files named in evidence are hashed individually; all 25 hashes are in the script output (files field).', 'Network, control-plane and storage incidents recur at the majority of providers with public history; a floor that requires a public incident feed with severity and durations lets buyers compare them.', 'medium', 'Uniform collection over one common window.', '2025-01-01 to 2026-09-29')
F('M13', 'market', 'derived', 'Demand versus public efficiency anchors on MI300X (OpenRouter weekly top-10, 97.09T tokens): 20.80T (21.4% of all, 31.2% of the 66.75T identified open-weight volume) sits on a model with an InferenceX MI300X row (DeepSeek V4.1 Flash, one framework, agentic only); 24.16T is adjacent-version only (GLM 5.3 Flash vs GLM-5.2, DeepSeek V4 Flash vs V4.1/V4-Pro); 21.79T has no row on any hardware (Hy4 preview 8.97T, MiMo-V2.6-Flash 6.93T, Nemotron 3 Ultra 5.89T); 18.20T is a stealth model; 12.14T is closed.',
  J('demand_anchor_result.json')['openrouter_by_level'] | {'week_total_tokens': J('demand_anchor_result.json')['openrouter_week_total'], 'ix_mi300x_models': J('demand_anchor_result.json')['ix_mi300x_models'], 'mlperf_mi300x_models': J('demand_anchor_result.json')['mlperf_mi300x_models']},
  ev('sessions/public-tail-20260929/lanes/demand-signals/rows/openrouter_rankings.jsonl', 'sessions/public-tail-20260929/lanes/mlperf/rows/mlperf.jsonl', 'sessions/public-tail-20260929/lanes/inferencex-history/imported-main/inferencex-2026-09-29.jsonl'),
  'imported', 'Name-level judgement (demand_anchor.py holds the map); OpenRouter exposes only 10 weekly ranked models in page HTML; token volumes are one week as of 2026-09-29.', 'For most of the open-weight volume people actually buy, a shop on MI300X has no public throughput reference at all; its own measurement is the only anchor.', 'medium', 'Confirm model identities with the OpenRouter model cards.', 'week to 2026-09-29')
F('M14', 'market', 'derived', 'Ollama library top-20 non-embedding models by cumulative pulls (667.7M): 58.0% (387.4M) have no InferenceX or MLPerf row on MI300X at all (llama3.2 84.6M, qwen2.5 41.3M, gemma3 40.8M, gemma2 33.7M, mistral 33.7M, gemma4 26.0M, llama3 25.4M, qwen2.5-coder 21.9M, phi3, llava, gpt-oss, qwen3-coder 9.6M, ...), 42.0% (280.3M) only at another size or version (llama3.1 120M: MLPerf 70B/405B only; deepseek-r1 93.3M: 671B only; qwen3 38.3M: 0.6B only), none exact. Qwen3-Coder-30B-A3B, our workload, has no public row on any hardware.',
  J('demand_anchor_result.json')['ollama_by_level'] | {'top20_total_pulls': J('demand_anchor_result.json')['ollama_top20_total'], 'rows': J('demand_anchor_result.json')['ollama_rows']},
  ev('sessions/public-tail-20260929/lanes/demand-signals/rows/ollama_models.jsonl', 'sessions/public-tail-20260929/lanes/mlperf/rows/mlperf.jsonl', 'sessions/public-tail-20260929/lanes/inferencex-history/imported-main/inferencex-2026-09-29.jsonl'),
  'imported', 'Pulls are cumulative, rounded, from 200 of 240 listed models; the default Ollama tag size is used to judge "other size"; embeddings excluded. Judgement map in demand_anchor.py.', 'Small and mid-size dense models (the bulk of local demand) have no MI300X reference; a floor kit that measures them adds the missing anchors.', 'medium', 'Add the top 10 by pulls to the shop-eval workload set.', 'to 2026-09-29')
with open(os.path.join(HERE, 'findings.jsonl'), 'w', encoding='utf-8') as f:
    for r in rows: f.write(json.dumps(r, ensure_ascii=False) + '\n')
print(len(rows), 'findings written')
