'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const ROOT=path.resolve(__dirname,'..'),OUT=path.resolve(process.env.SHELF_QA_DIR||'shelf-browser-qa');fs.mkdirSync(OUT,{recursive:true});
const cards=fs.readFileSync(path.join(ROOT,'data/cards.jsonl'),'utf8').trim().split('\n').map(JSON.parse),checks=[],errors=[],external=[];
let browser,server;function check(name,value){assert.ok(value,name);checks.push({name,pass:true});}
(async()=>{server=http.createServer((req,res)=>{let name=new URL(req.url,'http://localhost').pathname;let b;
 if(name==='/data/hubs.json')b=Buffer.from(JSON.stringify({hubs:[{name:'original',cards:'data/cards.jsonl'},{name:'independent-copy',cards:'data/second.json'}]}));
 else if(name==='/data/second.json')b=Buffer.from(JSON.stringify(cards[0]));
 else{if(name==='/')name='/index.html';const file=path.resolve(ROOT,'.'+decodeURIComponent(name));if(!file.startsWith(ROOT+path.sep)||!fs.existsSync(file)){res.writeHead(404);res.end();return;}b=fs.readFileSync(file);}
 res.setHeader('Content-Type',name.endsWith('.html')?'text/html; charset=utf-8':name.endsWith('.json')?'application/json':'text/plain; charset=utf-8');res.end(b);});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const origin='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({headless:true});const ctx=await browser.newContext({viewport:{width:1280,height:900}});await ctx.route('**/*',r=>{if(r.request().url().startsWith(origin+'/'))return r.continue();external.push(r.request().url());return r.abort();});const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.goto(origin+'/',{waitUntil:'networkidle'});await page.waitForSelector('#which-out .result.ok');check('same slug remains usable in each separate hub',await page.locator('#which-out .result.ok').count()===2);
 check('query output carries both hub identities',(await page.locator('#which-out').innerText()).includes('original: run3-at0')&&(await page.locator('#which-out').innerText()).includes('independent-copy: run3-at0'));
 const first=page.locator('#which-out .result.ok').first();await first.locator('summary').click();const text=await first.innerText();check('accounting distinction survives displayed result',text.includes('not inspected here'));check('recomputation scope survives displayed result',text.includes('No fresh EvalPlus execution'));check('independence flag stays visible',text.includes('independent validation: false'));
 await page.fill('#c-text','null');await page.locator('#check-form button[type=submit]').click();check('invalid filing is refused visibly',(await page.locator('#check-out').innerText()).includes('card must be an object'));
 for(const width of [768,390,320]){await page.setViewportSize({width,height:900});check('scope details fit '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
 await page.screenshot({path:path.join(OUT,'scope-phone.png'),fullPage:false});check('no JavaScript errors',errors.length===0);check('no external requests',external.length===0);
})().catch(e=>{checks.push({name:'browser interruption',pass:false,error:e.message});process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(server){server.closeAllConnections();await new Promise(r=>server.close(r));}const r={checks,errors,external,passed:checks.filter(x=>x.pass).length,failed:checks.filter(x=>!x.pass).length,scope:'Real local HTTP, two attributed hubs containing the same retained card; no independent performance observation inferred.'};fs.writeFileSync(path.join(OUT,'results.json'),JSON.stringify(r,null,2)+'\n');console.log(JSON.stringify(r));});
