'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto'),path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const src=html.match(/<script id="report-engine">([\s\S]*?)<\/script>/)[1];
const sandbox={module:{exports:{}},TextEncoder,Uint8Array,Uint32Array,DataView};vm.runInNewContext(src,sandbox);const H=sandbox.module.exports;
const sample=JSON.parse(html.match(/<script id="sample-data" type="application\/json">([\s\S]*?)<\/script>/)[1]);
const copy=x=>JSON.parse(JSON.stringify(x));let tests=0;
const test=(name,f)=>{try{f();tests++;console.log('PASS '+name);}catch(e){console.error('FAIL '+name,e);process.exitCode=1;}};
const sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const run=(raw=sample.a,i=0)=>H.normalize(raw,{sha256:sha(JSON.stringify(raw)),record_index:i,bytes:Buffer.byteLength(JSON.stringify(raw))});
const price=(p={})=>({provider:'Hot Aisle',gpus:1,rate:2.99,extra:0,source:'dated test price',period:'2026-09-22',...p});
const approx=(x,y)=>assert.ok(Math.abs(x-y)<1e-9,`${x} != ${y}`);
const agg=(raw=sample.a,set={})=>H.aggregate([run(raw)],set);
const bad=(patch,regex)=>assert.throws(()=>run({...sample.a,...patch}),regex);

test('vLLM summary and detailed objects',()=>{assert.equal(run().completed,4);assert.equal(run().attempted,5);assert.equal(run().rows.length,5);});
test('JSON document, array, BOM, NDJSON and appended objects',()=>{const s=JSON.stringify(sample.a);for(const value of [s,'\uFEFF'+s])assert.equal(H.parseDocuments(value).length,1);for(const value of ['['+s+','+s+']',s+'\n'+s,s+'\n\n'+s])assert.equal(H.parseDocuments(value).length,2);});
test('console with ANSI and optional attempted count',()=>{const r=H.normalize(H.parseDocuments('\u001b[32mINFO\u001b[0m\n=== Serving Benchmark Result ===\nSuccessful requests: 4\nFailed requests: 1\nBenchmark duration (s): 10.00\nP95 TTFT (ms): 385.00\nMedian E2EL (ms): 2500.00')[0],run().source);assert.equal(r.attempted,5);assert.equal(r.metrics.ttft.percentiles.p95,385);});
test('console without failed count keeps denominator unknown',()=>{const r=H.normalize(H.parseConsole('Successful requests: 4\nBenchmark duration (s): 10'),run().source);assert.equal(r.attempted,null);assert.equal(H.aggregate([r]).failureRate,null);});
test('duplicate console blocks rejected',()=>assert.throws(()=>H.parseConsole('Successful requests: 4\nBenchmark duration (s): 10\nSuccessful requests: 4'),/one console/));
test('blank rejected',()=>assert.throws(()=>H.parseDocuments('   '),/empty/));
test('truncated JSON rejected',()=>assert.throws(()=>H.parseDocuments('{"duration":1'),/incomplete/));
test('trailing garbage rejected',()=>assert.throws(()=>H.parseDocuments('{} blah'),/Expected/));
test('arbitrary JSON rejected',()=>assert.throws(()=>run({answer:42}),/duration/));
test('nonfinite JSON is rejected, never executed',()=>assert.throws(()=>H.parseDocuments('{"duration":Infinity}'),/Invalid/));
test('primitive document is not a run',()=>assert.throws(()=>H.normalize(42,{}),/object/));
test('zero duration rejected',()=>bad({duration:0},/duration/));
test('negative duration rejected',()=>bad({duration:-1},/duration/));
test('NaN rejected',()=>bad({duration:NaN},/duration/));
test('infinite duration rejected',()=>bad({duration:Infinity},/duration/));
test('fractional completed count rejected',()=>bad({completed:3.5},/integer/));
test('inconsistent attempts rejected',()=>bad({num_prompts:4},/differs/));
test('completed exceeds attempts rejected',()=>bad({completed:6,failed:undefined},/exceed/));
test('negative request timing rejected',()=>bad({ttfts:[-1,.2,.3,.4,0]},/ttfts/));
test('detail-array length mismatch rejected',()=>bad({latencies:[1,2]},/length/));
test('error-mask count mismatch rejected',()=>bad({errors:['','','','','']},/disagrees/));
test('untyped error outcomes rejected',()=>bad({errors:['','','','',{}]},/strings/));
test('completion before first token rejected',()=>bad({latencies:[.01,2,3,4,0]},/smaller/));
test('output-token disagreement rejected',()=>bad({total_output_tokens:99},/disagrees/));
test('legacy colon-bearing goodput is supported as observation',()=>{const r=run({...sample.a,'request_goodput:':.3});assert.equal(r.reportedGoodput,.3);assert.equal(H.aggregate([r]).unit,'completed requests');});
test('impossible goodput rejected',()=>bad({request_goodput:42},/exceeds/));
test('reported throughput disagreement is visible',()=>{const r=run({...sample.a,request_throughput:100});assert.equal(r.warnings.length,1);approx(H.aggregate([r]).rate,.4);});
test('failed zero latencies do not improve percentiles',()=>{const a=agg();approx(a.metrics.ttft.p50,250);approx(a.metrics.ttft.p95,385);assert.equal(a.metrics.ttft.n,4);});
test('failure ratio uses attempted, not completed denominator',()=>approx(agg().failureRate,.2));
test('repeated trials use counts and total duration',()=>{const b={...sample.a,duration:30,request_throughput:4/30};const a=H.aggregate([run(),run(b)]);approx(a.rate,8/40);assert.notEqual(a.rate,(.4+4/30)/2);assert.equal(a.runs,2);});
test('duplicate trials rejected',()=>assert.throws(()=>H.aggregate([run(),run()]),/Duplicate/));
test('distinct appended record indexes retain trials',()=>assert.equal(H.aggregate([run(sample.a,0),run(sample.a,1)]).runs,2));
test('heterogeneous models held',()=>assert.throws(()=>H.aggregate([run(),run({...sample.a,model_id:'another'})]),/Mixed model/));
test('conflicting manual identity held',()=>assert.throws(()=>H.aggregate([run()],{identity:{model:'another'}}),/conflicts/));
test('missing identity can be explicitly supplied',()=>{const r=run({...sample.a,model_id:undefined});assert.equal(H.aggregate([r],{identity:{model:'declared'}}).identity.model,'declared');});
test('summary percentile kept, not averaged',()=>{function summary(p,i){return run({model_id:'same',duration:10,completed:5,num_prompts:5,p95_ttft_ms:p},i);}const a=H.aggregate([summary(10,0),summary(20,1)]);assert.equal(a.metrics.ttft.p95,null);assert.deepEqual([...a.metrics.ttft.ranges.p95],[10,20]);});
test('missing percentile never zero-filled',()=>{const a=H.aggregate([run({duration:10,completed:5})]);assert.equal(a.metrics.e2e.p95,null);});
test('joint latency gate uses request intersection',()=>{const a=agg(sample.a,{ttft:300,e2e:2500});assert.equal(a.accepted,2);approx(a.rate,.2);assert.equal(a.unit,'latency-qualified requests');});
test('gate threshold equality is inclusive',()=>assert.equal(agg(sample.a,{ttft:300,e2e:3000}).accepted,3));
test('client queue included in optional gates',()=>assert.equal(agg(sample.a,{ttft:300,e2e:3000,queue:true}).accepted,2));
test('missing queue is held rather than treated as zero',()=>{const r=copy(sample.a);delete r.queue_times;const a=agg(r,{ttft:500,queue:true});assert.equal(a.accepted,null);assert.ok(a.holds[0].includes('queue'));});
test('summary-only gating held',()=>{const a=agg({duration:10,completed:5,num_prompts:5,p95_ttft_ms:300},{ttft:500});assert.equal(a.accepted,null);});
test('latency cannot be reconstructed from ITL sums',()=>{const raw=copy(sample.a);delete raw.latencies;raw.itls=[[.1],[.2],[.3],[.4],[]];const a=agg(raw,{e2e:3000});assert.equal(a.accepted,null);assert.equal(a.metrics.e2e.p95,null);});
test('absent evaluation holds quality metric',()=>assert.equal(agg(sample.a,{quality:true}).accepted,null));
function evaluation(r,passed=[true,false,true,false,false]){return {schema:'hot-aisle/request-evaluation@1',source_sha256:r.source.sha256,record_index:r.source.record_index,passed,evaluator:'exact-result-fixture-v1',criterion_id:'fixture-answer-v1'};}
test('hash-bound evaluation joins original request order',()=>{const r=run(),q=H.attachQuality(r,evaluation(r));assert.equal(H.aggregate([q],{quality:true}).accepted,2);});
test('quality + latency intersection, not product of rates',()=>{const r=run(),q=H.attachQuality(r,evaluation(r));assert.equal(H.aggregate([q],{quality:true,e2e:2500}).accepted,1);});
test('evaluation source mismatch refused',()=>{const r=run(),q=evaluation(r);q.source_sha256='a'.repeat(64);assert.throws(()=>H.attachQuality(r,q),/exact source/);});
test('evaluation record mismatch refused',()=>{const r=run(),q=evaluation(r);q.record_index=1;assert.throws(()=>H.attachQuality(r,q),/exact source/);});
test('evaluation failed transport cannot pass',()=>{const r=run();assert.throws(()=>H.attachQuality(r,evaluation(r,[true,true,true,true,true])),/failed request/);});
test('evaluation boolean strings rejected',()=>{const r=run();assert.throws(()=>H.attachQuality(r,evaluation(r,['true',false,true,false,false])),/boolean/);});
test('all-failed test retains cost but no finite cost per outcome',()=>{const r={...sample.a,completed:0,failed:5,errors:['x','x','x','x','x'],total_output_tokens:0,request_throughput:0};const a=agg(r),c=H.costing(a,price());assert.equal(a.accepted,0);assert.equal(c.costPer1000,null);assert.equal(a.metrics.ttft.p95,null);assert.ok(c.total>0);});
test('billable count and hourly extras included',()=>{const c=H.costing(agg(),price({gpus:4,extra:2}));approx(c.hourly,13.96);approx(c.total,13.96*10/3600);});
test('whole-bill override retains cost denominator',()=>approx(H.costing(agg(),price({total:100})).costPer1000,25000));
test('blank total does not become a zero bill',()=>assert.ok(H.costing(agg(),price({total:''})).total>0));
test('explicit zero supplied bill is retained',()=>assert.equal(H.costing(agg(),price({total:0})).costPer1000,0));
test('negative costs rejected',()=>assert.throws(()=>H.costing(agg(),price({rate:-1})),/price/));
test('fractional GPUs rejected',()=>assert.throws(()=>H.costing(agg(),price({gpus:1.5})),/integer/));
test('overflow rejected',()=>assert.throws(()=>H.costing(agg(),price({gpus:8,rate:Number.MAX_VALUE})),/overflow/));
test('comparator required throughput direction is correct',()=>{approx(H.threshold(1,2.99,3.85),3.85/2.99);assert.ok(H.threshold(1,2.99,3.85)>1);approx(H.threshold(1,2.99,1.80),1.80/2.99);});
test('zero Hot Aisle cost cannot produce a finite price threshold',()=>assert.throws(()=>H.threshold(1,0,3.85),/allocation/));
function pair(raw=sample.b,set={}){const a=agg(),b=agg(raw,set);return [a,H.costing(a,price()),b,H.costing(b,price({provider:'B',rate:3.85}))];}
test('matched supplied evidence yields bounded cost comparison',()=>{const c=H.compare(...pair());assert.equal(c.status,'COMPARISON_OF_SUPPLIED_EVIDENCE');assert.equal(c.winner,'A');assert.equal(c.synthetic,true);});
test('missing workload holds savings',()=>{const r=copy(sample.b);delete r.metadata.workload_id;const c=H.compare(...pair(r));assert.equal(c.saving,null);assert.ok(c.issues.some(x=>x.includes('workload')));});
test('different precision holds savings',()=>{const r=copy(sample.b);r.metadata.precision='Q4';assert.equal(H.compare(...pair(r)).winner,null);});
test('different request gates hold savings',()=>assert.equal(H.compare(...pair(sample.b,{ttft:500})).winner,null));
test('same raw source on both sides holds savings',()=>assert.ok(H.compare(...pair(sample.a)).issues.some(x=>x.includes('same source'))));
test('competitor is allowed to win',()=>{const x=pair();x[3]=H.costing(x[2],price({rate:.1}));assert.equal(H.compare(...x).winner,'B');});
test('billing bases must match',()=>{const x=pair();x[3]=H.costing(x[2],price({total:1}));assert.equal(H.compare(...x).saving,null);});
test('identical cost is a tie',()=>{const x=pair();x[3]=H.costing(x[2],price({rate:2.99*10/12}));approx(x[1].costPer1000,x[3].costPer1000);});
test('sha256 portable fallback matches native for boundary lengths',()=>{for(const n of [0,1,55,56,63,64,65,1000,1024*1024]){const b=Buffer.alloc(n,97);assert.equal(H.sha256(b),sha(b));}});
test('sha256 handles binary and UTF-8',()=>{for(const b of [Buffer.from('hello ☃'),Buffer.from([...Array(256).keys()])])assert.equal(H.sha256(b),sha(b));});
test('unknown metadata and raw text excluded from normalized output',()=>{const raw=copy(sample.a);raw.generated_texts=['SECRET_PROMPT_1'];raw.api_key='SECRET_KEY_2';const r=run(raw);const s=JSON.stringify(r);assert.ok(!s.includes('SECRET_PROMPT_1'));assert.ok(!s.includes('SECRET_KEY_2'));assert.ok(!s.includes('synthetic failure'));});
function packet(){let sides=['a','b'].map((id,i)=>{const r=run(sample[id]),a=H.aggregate([r]),p=price({rate:i?3.85:2.99});return {id,label:id,settings:{},price:p,normalized:[r],aggregate:a,cost:H.costing(a,p)};});return {schema:'hot-aisle/workload-report@2',version:H.VERSION,generated_at:'2026-09-22T00:00:00Z',title:'SYNTHETIC',synthetic:true,sides,comparison:H.compare(sides[0].aggregate,sides[0].cost,sides[1].aggregate,sides[1].cost)};}
function envelope(p){return {schema:'hot-aisle/sealed-report@1',sha256:sha(H.canonical(p)),payload:p};}
test('exported report recomputes in a fresh invocation',()=>assert.equal(H.recompute(envelope(packet())).comparison.winner,'A'));
test('changed checksum is rejected',()=>{const e=envelope(packet());e.payload.sides[0].price.rate=99;assert.throws(()=>H.recompute(e),/checksum/);});
test('changed headline with a new checksum still fails recomputation',()=>{const p=packet();p.sides[0].cost.costPer1000=.01;assert.throws(()=>H.recompute(envelope(p)),/Derived/);});
test('synthetic marker cannot silently disappear',()=>{const p=packet();p.synthetic=false;assert.throws(()=>H.recompute(envelope(p)),/Synthetic/);});
test('report HTML escapes model and quote markup',()=>{const p=packet();p.sides[0].aggregate.identity.model='<img src=x onerror=alert(1)>';p.sides[0].cost.quote='<script>bad()</script>';const h=H.receiptHTML(p);assert.ok(!h.includes('<img'));assert.ok(!h.includes('<script>'));assert.ok(h.includes('&lt;img'));assert.ok(h.includes('SYNTHETIC DEMONSTRATION'));});
test('canonical serialization ignores object key order',()=>assert.equal(H.canonical({b:1,a:2}),H.canonical({a:2,b:1})));
test('nonmonotonic percentile summary rejected',()=>bad({p50_ttft_ms:500,p95_ttft_ms:100},/monotonic/));
test('raw arbitrary format field is not exported',()=>assert.equal(run({...sample.a,format:'SECRET_BODY'}).format,'vllm-serve-json'));
test('overflowing derived throughput is rejected',()=>assert.throws(()=>agg({...sample.a,duration:Number.MIN_VALUE,request_throughput:undefined}),/overflow/));
console.log(JSON.stringify({tests,failed:process.exitCode?true:false,scope:'Software qualification with synthetic fixtures; no GPU performance measurement.'}));
