/* Browser interaction layer. All computations use Compute; all imports use the retained HA engine. */
'use strict';
const $=id=>document.getElementById(id), C=Compute, H=HA, Q=WorkloadQualification, esc=H.escape;
const catalog=C.validateCatalog(JSON.parse($('catalog-data').textContent));
const samples=JSON.parse($('sample-data').textContent);
const providerName=id=>catalog.providers.find(p=>p.id===id)?.name||id;
const money=(v,d=2)=>v===null||v===undefined?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:d,maximumFractionDigits:d}).format(v);
const nfmt=(v,d=1)=>v===null||v===undefined?'—':new Intl.NumberFormat('en-US',{maximumFractionDigits:d}).format(v);
const val=id=>{const s=$(id).value.trim();if(!s)throw Error('Complete '+($(id).labels?.[0]?.textContent||id)+'.');const v=Number(s);if(!Number.isFinite(v))throw Error('Enter a finite number.');return v;};
const url=s=>/^https:\/\//.test(s)?s:'#';
const digest=s=>H.sha256(new TextEncoder().encode(s));
const state={tab:'market',shortlist:[],rows:[],saved:[],runs:[],publications:[],instrumentStatus:'NOT_CONFIGURED',catalogMatch:null,hardware:null,connected:false,key:null,token:null,routeClasses:[],marketResult:null,ownResult:null,reuseResult:null};
let toastTimer;
function toast(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4800);}
function modal(title,body){$('modal-title').textContent=title;$('modal-body').innerHTML=body;if(!$('modal').open)$('modal').showModal();}
$('modal-close').onclick=()=>$('modal').close();
$('modal').addEventListener('click',e=>{if(e.target===$('modal')){const r=$('modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('modal').close();}});
function download(name,body,type='application/json'){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([body],{type}));a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);}
async function copy(s){try{await navigator.clipboard.writeText(s);toast('Copied.');}catch{download('compute-instructions.txt',s,'text/plain');toast('Clipboard unavailable; saved as text.');}}
function switchTab(name){if(!['market','own','reuse','work'].includes(name))return;state.tab=name;for(const b of document.querySelectorAll('[data-tab]')){const selected=b.dataset.tab===name;b.setAttribute('aria-selected',String(selected));b.tabIndex=selected?0:-1;$('view-'+b.dataset.tab).hidden=!selected;}if(name==='own')renderOwn();if(name==='reuse')renderReuse();if(name==='work')renderWork();}
for(const b of document.querySelectorAll('[data-tab]')){b.onclick=()=>switchTab(b.dataset.tab);b.onkeydown=e=>{const keys=['ArrowLeft','ArrowRight','Home','End'];if(!keys.includes(e.key))return;e.preventDefault();const tabs=[...document.querySelectorAll('[data-tab]')],i=tabs.indexOf(b),j=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;switchTab(tabs[j].dataset.tab);tabs[j].focus();};}
$('theme').onclick=()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='light'?'dark':'light';};
try{if(matchMedia('(prefers-color-scheme: light)').matches)document.documentElement.dataset.theme='light';}catch{}
function sourceView(){const f=C.freshness(catalog,new Date().toISOString().slice(0,10));modal('Sources, dates & price scope',`<p>Each price is a dated provider observation. The priceboard makes no availability or performance assertion.</p><div class="modelnotice" style="margin-top:17px"><b>${esc(f.status.replaceAll('_',' '))}</b> · reviewed ${esc(f.reviewedOn)} · ${f.ageDays} days old. Review interval: ${f.staleAfterDays} days.</div>${Object.values(catalog.sources).map(s=>`<div class="sourceentry"><h3><a href="${esc(url(s.url))}" target="_blank" rel="noopener">${esc(s.title)} ↗</a></h3><p>${esc(s.note)}</p><p class="mono">${esc(s.reviewedOn)} · ${esc(s.kind)}</p></div>`).join('')}<div class="showhelp">DigitalOcean's current on-demand price is $2.59 for MI300X and $4.41 for H100 in this review. Earlier $1.99 / $3.39 comparisons are historical. Its official pages also disagree on the minimum charge interval. This desk preserves that conflict rather than guessing.</div>`);}
for(const id of ['snapshot-button','source-note','footer-sources'])$(id).onclick=sourceView;
function methodView(){modal('The method, in plain language',`<div class="stack"><div><h3>Start with the allocation you pay for.</h3><p>Hourly GPU price × every reserved GPU × billed hours, plus entered extras. A monthly minimum remains in the calculation even when you use only part of the month. Short-session billing granularity requires a confirmed quote.</p></div><div><h3>Qualify the work before calling it cheaper.</h3><p>A memory filter creates a shortlist, not native model-fit proof. Same-model hardware comparisons and different-model outcome comparisons have different acceptance contracts. No provider inherits a speed or quality score here.</p></div><div><h3>Count all the attempts.</h3><p>The reuse model counts the first attempt, per-request validation, fallback work and the initial qualification cost. Requests moved and premium GPU time saved are reported separately. Releasing physical capacity requires a further placement and residency check.</p></div><div><h3>Use the same engine everywhere.</h3><p>The browser, local workspace helper, CLI and MCP tools share the calculation engine. Existing vLLM results are normalized by the retained workload-report engine. Files and supplied evaluator assertions remain producer evidence.</p></div><div><h3>Save decisions explicitly.</h3><p>Public browsing uses no account or application telemetry. Saving creates a local browser record. A connected session reads only its configured evidence directory, Aperture receipt and optional model endpoint. No model call, provisioning, benchmark, payment or production change runs from this desk.</p></div><div><h3>Keep the evidence independent.</h3><p>Exports contain the selected prices, inputs, derived results and a checksum. Recompute in the offline kit. Checksums bind a calculation, not the truth of source assertions or the operator's identity.</p></div></div>`);}
for(const id of ['method-top','footer-method'])$(id).onclick=methodView;
function marketParams(){return {asOf:$('as-of').value,hours:val('hours'),minMemoryGB:val('memory'),gpus:val('allocation'),provider:$('provider').value,vendor:$('vendor').value,query:$('search').value,extraPerHour:val('extras'),fixedCost:val('fixed')};}
function footprint(){try{const r=C.footprint({parametersB:val('parameters'),bits:val('bits'),kvGB:val('kv'),runtimeGB:3,overheadPct:15});$('footprint').textContent=nfmt(r.estimatedGB,1)+' GB planning budget: weights + 15% representation allowance + 3 GB runtime + your KV budget. Not native fit.';return r.estimatedGB;}catch(e){$('footprint').textContent=e.message;return null;}}
$('apply-memory').onclick=()=>{const needed=footprint();if(!needed)return;const options=[...$('memory').options].map(o=>Number(o.value)).filter(v=>v>=needed);if(!options.length){toast('Budget exceeds the listed screening options. Use an exact native-fit assessment.');return;}$('memory').value=Math.min(...options);renderMarket();};
for(const id of ['parameters','bits','kv'])$(id).oninput=footprint;
function renderMarket(){
 state.marketResult=null;try{const p=marketParams(),rows=C.market(catalog,p);state.rows=rows;$('market-error').textContent='';$('hours-label').textContent=p.hours+' h';for(const b of document.querySelectorAll('[data-hours]'))b.setAttribute('aria-pressed',String(Number(b.dataset.hours)===p.hours));$('result-count').textContent='· '+rows.length;
 if(rows.length){const r=rows[0];$('lowest').innerHTML=money(r.allocationHourly)+'<sup>/h</sup>';$('lowest-caption').textContent=(r.gpus>1?r.gpus+' × ':'')+r.gpu+' · '+providerName(r.provider);$('period-cost').textContent=money(r.total);$('period-caption').textContent=r.billedHours+' billed hours'+(r.minimumApplied?' · minimum applied':' · selected price schedule');}
 else{$('lowest').textContent='—';$('lowest-caption').textContent='No listed configuration matches';$('period-cost').textContent='—';$('period-caption').textContent='Change a filter to broaden the shortlist.';}
 const max=rows.length?Math.max(...rows.map(r=>r.total)):1;
 $('price-rows').innerHTML=rows.length?rows.map(r=>`<tr class="${state.shortlist.includes(r.id)?'selected':''}" data-row="${r.id}"><td><input type="checkbox" aria-label="Shortlist ${esc(providerName(r.provider)+' '+r.gpu+' '+r.gpus+' GPU')}" data-select="${r.id}" ${state.shortlist.includes(r.id)?'checked':''}></td><td><button class="gpu gpu-open" data-offer="${r.id}">${esc(r.gpu)}</button><span class="mobile-provider">${esc(providerName(r.provider))} · ${nfmt(r.memoryGB,0)} GB / GPU</span><span class="gpu-detail">${r.gpus} GPU${r.gpus>1?'s':''} · ${r.kind==='monthly'?'monthly minimum':r.kind==='public-pods'?'public Pods':'on demand'}</span></td><td><span class="provider p-${r.provider}"><i class="pdot"></i>${esc(providerName(r.provider))}</span></td><td class="num">${nfmt(r.memoryGB,0)}</td><td class="num">${money(r.allocationHourly)}</td><td class="num costcell"><strong>${money(r.total)}</strong><i class="bar" style="--bar:${Math.max(4,r.total/max*75)}%"></i></td><td><span class="badge">${r.allocation==='normalized'?'Normalized':r.kind==='public-pods'?'Advertised':'List price'}</span></td><td><button class="iconlink" data-offer="${r.id}" aria-label="Inspect ${esc(providerName(r.provider)+' '+r.gpu)}">↗</button></td></tr>`).join(''):'<tr><td colspan="8" class="empty">No results under these filters. Reset or lower the memory floor.</td></tr>';
 for(const e of document.querySelectorAll('[data-select]'))e.onchange=()=>selectOffer(e.dataset.select,e.checked);
 for(const e of document.querySelectorAll('[data-offer]'))e.onclick=()=>offerView(e.dataset.offer);
 renderPlot(rows);renderTray();state.marketResult={params:p,rows};
 }catch(e){$('market-error').textContent=e.message;$('price-rows').innerHTML='<tr><td colspan="8" class="empty">Calculation held. Correct the highlighted input.</td></tr>';$('lowest').textContent='—';$('period-cost').textContent='—';state.rows=[];}
}
function renderPlot(rows){const w=390,h=134,l=30,t=9,r=9,b=23,iw=w-l-r,ih=h-t-b;const maxM=Math.max(192,...rows.map(x=>x.memoryGB)),maxP=Math.max(4,...rows.map(x=>x.allocationHourly));const x=m=>l+m/maxM*iw,y=p=>h-b-p/maxP*ih;
 let s=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Allocation price versus advertised memory per GPU. Exact values are in the priceboard.">`;
 for(let i=0;i<3;i++){const v=i*maxP/2;s+=`<line class="grid" x1="${l}" x2="${w-r}" y1="${y(v)}" y2="${y(v)}"/><text class="axis" x="${l-5}" y="${y(v)+3}" text-anchor="end">$${nfmt(v,1)}</text>`;}
 for(let i=0;i<3;i++){const v=i*maxM/2;s+=`<text class="axis" x="${x(v)}" y="${h-5}" text-anchor="middle">${nfmt(v,0)} GB</text>`;}
 for(const row of rows)s+=`<circle class="p-${row.provider}" cx="${x(row.memoryGB)}" cy="${y(row.allocationHourly)}" r="${state.shortlist.includes(row.id)?5:3.6}" tabindex="0" data-dot="${row.id}" aria-label="${esc(row.gpu+' '+providerName(row.provider)+' '+money(row.allocationHourly)+' per allocation hour')}"><title>${esc(providerName(row.provider)+' · '+row.gpu+' · '+money(row.allocationHourly)+'/h')}</title></circle>`;
 $('market-plot').innerHTML=s+'</svg>';for(const e of document.querySelectorAll('[data-dot]')){e.onclick=()=>offerView(e.dataset.dot);e.onkeydown=ev=>{if(ev.key==='Enter'||ev.key===' ')offerView(e.dataset.dot);};}
}
function selectOffer(id,selected){if(selected&&!state.shortlist.includes(id)){if(state.shortlist.length===4){toast('Compare up to four configurations at a time.');renderMarket();return;}state.shortlist.push(id);}else if(!selected)state.shortlist=state.shortlist.filter(x=>x!==id);renderMarket();}
function renderTray(){$('shortlist-tray').hidden=!state.shortlist.length;$('shortlist-title').textContent=state.shortlist.length+' configuration'+(state.shortlist.length===1?'':'s')+' selected';$('shortlist-desc').textContent=state.shortlist.map(id=>catalog.offers.find(o=>o.id===id).gpu).join(' · ');}
function offerView(id){const o=catalog.offers.find(x=>x.id===id),q=C.quote(o,marketParams()),s=catalog.sources[o.source];modal(providerName(o.provider)+' · '+o.gpu,`<div class="row between"><span class="badge amber">${o.gpus} GPU${o.gpus>1?'s':''} · ${esc(o.kind)}</span><span class="badge">Price model</span></div><div class="offer-value">${money(q.allocationHourly)}<span class="small muted"> / allocation-hour</span></div><p>${money(q.total)} for ${nfmt(q.billedHours,0)} billed hours under your inputs.</p><dl><dt>Memory per GPU</dt><dd>${o.memoryGB} advertised GB</dd><dt>Effective price date</dt><dd>${esc(q.effectiveOn)}</dd><dt>GPU-hour rate</dt><dd>${money(q.ratePerGPU)}</dd><dt>Allocation basis</dt><dd>${esc(o.allocation)}</dd><dt>Native fit / workload performance</dt><dd>Qualification required</dd><dt>Stock / deployment availability</dt><dd>Check provider</dd></dl><p>${esc(o.terms)}</p><p style="margin-top:12px"><a href="${esc(s.url)}" target="_blank" rel="noopener">Inspect provider pricing ↗</a></p><div class="dialogactions"><button class="primary" id="detail-select">${state.shortlist.includes(id)?'Remove from':'Add to'} shortlist</button><button id="detail-own">Compare with owning</button><button id="detail-reuse">Use as premium baseline</button></div>`);$('detail-select').onclick=()=>{selectOffer(id,!state.shortlist.includes(id));$('modal').close();};$('detail-own').onclick=()=>{$('rental-offer').value=id;$('modal').close();switchTab('own');};$('detail-reuse').onclick=()=>{$('premium-offer').value=id;$('modal').close();switchTab('reuse');};}
$('compare-shortlist').onclick=()=>{const p=marketParams(),rs=state.shortlist.map(id=>C.quote(catalog.offers.find(o=>o.id===id),p));modal('Your compute shortlist',`<div class="matrix">${rs.map(r=>`<div class="comparison-card"><div class="eyebrow">${esc(providerName(r.provider))}</div><h3>${r.gpus} × ${esc(r.gpu)}</h3><div class="bigstat">${money(r.total)}</div><p>${r.billedHours} billed hours · ${r.memoryGB} GB per GPU</p><p>${esc(r.terms)}</p></div>`).join('')}</div><div class="showhelp">To tie the first option on cost per result, each alternative needs ${rs.map(r=>nfmt(r.allocationHourly/rs[0].allocationHourly*100,1)+'%').join(' / ')} of its accepted-work rate, respectively, when minimum commitments and other costs are equal. This is a price threshold, not a measured speed comparison.</div><div class="dialogactions"><button class="primary" id="compare-save">Save this decision</button></div>`);$('compare-save').onclick=()=>{saveDecision('market');$('modal').close();};};
$('clear-shortlist').onclick=()=>{state.shortlist=[];renderMarket();};
$('plan-shortlist').onclick=()=>saveDecision('market');
for(const e of document.querySelectorAll('[data-hours]'))e.onclick=()=>{$('hours').value=e.dataset.hours;renderMarket();};
for(const id of ['memory','allocation','hours','vendor','provider','as-of','search','extras','fixed'])$(id).addEventListener('input',renderMarket);
$('reset-market').onclick=()=>{$('memory').value='24';$('allocation').value='1';$('hours').value=160;$('vendor').value='all';$('provider').value='all';$('search').value='';$('extras').value=0;$('fixed').value=0;renderMarket();};
function linePlot(id,points,xLabel,yLabel,labels){const w=700,h=205,l=50,r=16,t=15,b=30,iw=w-l-r,ih=h-t-b,xMax=Math.max(1,...points.map(p=>p.x)),yMax=Math.max(1,...points.flatMap(p=>[p.a,p.b]));let s=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(labels)}"><title>${esc(labels)}</title>`;const x=v=>l+v/xMax*iw,y=v=>h-b-v/yMax*ih;
 for(let i=0;i<=3;i++){const v=yMax*i/3;s+=`<line class="chart-grid" x1="${l}" x2="${w-r}" y1="${y(v)}" y2="${y(v)}"/><text x="${l-8}" y="${y(v)+3}" text-anchor="end">$${nfmt(v,0)}</text>`;}
 for(let i=0;i<=4;i++){const v=xMax*i/4;s+=`<text x="${x(v)}" y="${h-10}" text-anchor="middle">${nfmt(v,0)}</text>`;}
 s+=`<text x="${w-r}" y="${h+3}" text-anchor="end">${esc(xLabel)}</text>`;
 for(const [key,cls] of [['a','curve-a'],['b','curve-b']])s+=`<path class="${cls}" d="${points.map((p,i)=>(i?'L':'M')+x(p.x).toFixed(2)+','+y(p[key]).toFixed(2)).join(' ')}"/>`;
 $(id).innerHTML=s+'</svg>';
}
function ownParams(){const o=catalog.offers.find(o=>o.id===$('rental-offer').value),q=C.quote(o,{asOf:$('as-of').value,hours:val('own-hours')});const p={hours:val('own-hours'),capex:val('capex'),residual:val('residual'),months:val('horizon'),loadWatts:val('load-watts'),idleWatts:val('idle-watts'),kwhPrice:val('kwh'),opsMonthly:val('ops'),powerFactor:1,cloudHourly:q.allocationHourly,cloudMinimumHours:o.minimumHours};const l=$('local-rate').value.trim(),r=$('cloud-rate').value.trim();if(!!l!==!!r)throw Error('Supply both local and cloud accepted-work rates, or leave both empty.');if(l&&r){p.localRate=Number(l);p.cloudRate=Number(r);}return p;}
function renderOwn(){state.ownResult=null;try{const p=ownParams(),r=C.ownership(p);state.ownResult={params:p,result:r};$('own-error').textContent='';$('own-hours-label').textContent=p.hours+' h';$('own-cost').textContent=money(r.ownershipMonthly);$('rent-cost').textContent=money(r.rentalMonthly);$('cash-months').textContent=r.cashBreakevenMonths===null?'No crossing':nfmt(r.cashBreakevenMonths,1)+' mo';$('rent-hours-label').textContent=nfmt(r.cloudBillableHours,1)+' comparator allocation-hours';$('own-basis').innerHTML=`<b>${r.basis==='USER_DECLARED_EQUAL_WORK_RATES'?'Same work, supplied rates.':'Equal reserved hours.'}</b> ${r.basis==='USER_DECLARED_EQUAL_WORK_RATES'?'Output equivalence remains your declaration; qualification is separate.':'This compares ownership cost with rental time, not GPU performance.'}${r.capacityWarning?' Required cloud time exceeds one allocation-month; parallelism or a longer window needs qualification.':''}`;$('own-breakdown').innerHTML=`<span>Energy ${money(r.energyMonthly)}</span><span>Amortization ${money(r.amortizationMonthly)}</span><span>Other ${money(r.opsMonthly)}</span><span>${p.months}-month ownership cost <b>${money(r.ownershipHorizonCost)}</b></span>`;linePlot('own-chart',Array.from({length:37},(_,i)=>{const x=i*20,r=C.ownership({...p,hours:x});return {x,a:r.ownershipMonthly,b:r.rentalMonthly};}),'active hours per 30 days','USD','Ownership and rental monthly costs by active hours. Orange is ownership; blue is rental.');}catch(e){$('own-error').textContent=e.message;for(const id of ['own-cost','rent-cost','cash-months'])$(id).textContent='—';$('own-chart').replaceChildren();$('own-breakdown').replaceChildren();}}
for(const id of ['capex','residual','horizon','load-watts','idle-watts','kwh','ops','own-hours','local-rate','cloud-rate','rental-offer'])$(id).oninput=renderOwn;
const routeDefaults=()=>[{name:'Reusable operations',share:60,baselineSeconds:1,targetSeconds:.05,targetHourly:.08,fallbackPercent:0,premium:false},{name:'Smaller-model work',share:20,baselineSeconds:1,targetSeconds:1.5,targetHourly:.49,fallbackPercent:5,premium:false},{name:'Fresh judgment',share:20,baselineSeconds:20,targetSeconds:20,targetHourly:2.99,fallbackPercent:0,premium:true}];
function routeFields(){state.routeClasses=routeDefaults();$('route-classes').innerHTML=state.routeClasses.map((c,i)=>`<div class="routeclass"><div class="classname"><h3>${esc(c.name)}</h3><span class="type">${c.premium?'PREMIUM PATH':'CANDIDATE PATH'}</span></div>${[['share','Share, %'],['baselineSeconds','Baseline sec / req'],['targetSeconds','Target sec / req'],['targetHourly','Target $ / hour'],['fallbackPercent','Fallback, %']].map(([k,label])=>`<div><label for="r-${i}-${k}">${label}</label><input type="number" id="r-${i}-${k}" min="0" step="any" value="${c[k]}" ${c.premium&&(k==='targetHourly'||k==='fallbackPercent')?'readonly':''}></div>`).join('')}</div>`).join('');for(const e of $('route-classes').querySelectorAll('input'))e.oninput=renderReuse;}
function reuseParams(){const offer=catalog.offers.find(o=>o.id===$('premium-offer').value),q=C.quote(offer,{asOf:$('as-of').value,hours:1});const classes=state.routeClasses.map((c,i)=>({...c,...Object.fromEntries(['share','baselineSeconds','targetSeconds','targetHourly','fallbackPercent'].map(k=>[k,val('r-'+i+'-'+k)]))}));classes[2].targetHourly=q.allocationHourly;$('r-2-targetHourly').value=q.allocationHourly;return {requests:val('volume'),premiumHourly:q.allocationHourly,qualificationCost:val('qual-cost'),validationCostPerRequest:val('validation-cost'),repeats:val('repeat-batches'),classes};}
function renderReuse(){state.reuseResult=null;try{const p=reuseParams(),r=C.route(p);state.reuseResult={params:p,result:r};$('reuse-error').textContent='';$('moved-pct').textContent=nfmt(r.requestsMovedPct,1)+'%';$('time-pct').textContent=nfmt(r.premiumTimeReductionPct,1)+'%';$('moved-bar').style.width=Math.max(0,Math.min(100,r.requestsMovedPct))+'%';$('time-bar').style.width=Math.max(0,Math.min(100,r.premiumTimeReductionPct??0))+'%';$('baseline-batch').textContent=money(r.baselinePerBatch);$('proposed-batch').textContent=money(r.recurringPerBatch);$('break-even-batch').textContent=r.breakEvenBatches??'Never';$('reuse-total').innerHTML=`At ${r.repeats} repeats: <b>${money(r.proposedTotal)}</b> proposed vs ${money(r.baselineTotal)} baseline.<br><span class="muted">${money(Math.abs(r.savingsTotal))} ${r.savingsTotal>=0?'modeled savings':'additional cost'}, including setup.</span>`;const max=Math.max(12,Math.min(500,r.repeats));linePlot('reuse-chart',Array.from({length:31},(_,i)=>{const x=i*max/30;return {x,a:r.qualificationCost+r.recurringPerBatch*x,b:r.baselinePerBatch*x};}),'repeat batches','USD','Scenario cumulative cost. Orange includes initial qualification and recurring optimized work. Blue repeats the baseline.');}catch(e){$('reuse-error').textContent=e.message;for(const id of ['moved-pct','time-pct','baseline-batch','proposed-batch','break-even-batch'])$(id).textContent='—';$('reuse-chart').replaceChildren();$('reuse-total').textContent='Correct the scenario to recompute.';$('moved-bar').style.width='0%';$('time-bar').style.width='0%';}}
for(const id of ['premium-offer','volume','qual-cost','validation-cost','repeat-batches'])$(id).oninput=renderReuse;
$('reset-reuse').onclick=()=>{routeFields();renderReuse();};
function seal(payload){return {schema:'second-run/sealed-compute-decision@1',sha256:digest(C.canonical(payload)),payload};}
function computeSaved(p){if(p.schema!=='second-run/compute-decision@1'||p.version!==C.VERSION)throw Error('Unsupported decision version.');if(p.kind==='market')return C.plan(p.catalog,p.inputs);if(p.kind==='own')return C.ownership(p.inputs);if(p.kind==='reuse')return C.route(p.inputs);throw Error('Unsupported decision kind.');}
function verifySaved(e){if(e?.schema==='second-run/qualified-decision@1')return Q.verifyDecision(e);if(e?.schema!=='second-run/sealed-compute-decision@1'||!e.payload||e.sha256!==digest(C.canonical(e.payload)))throw Error('Decision checksum mismatch.');const r=computeSaved(e.payload);if(C.canonical(r)!==C.canonical(e.payload.result))throw Error('Saved result differs from recomputation.');return e;}
function saveDecision(kind){try{let p,result,title;if(kind==='market'){if(!state.shortlist.length)throw Error('Select at least one configuration.');p={...marketParams(),offerIds:[...state.shortlist],workload:'Compute shortlist',acceptance:'To be qualified before execution'};result=C.plan(catalog,p);title=p.minMemoryGB+' GB+ · '+p.hours+' h shortlist';}else if(kind==='own'){p=ownParams();result=C.ownership(p);title=$('own-name').value.slice(0,100)+' · own vs rent';}else{p=reuseParams();result=C.route(p);title='Route proposal · '+p.requests+' requests × '+p.repeats;}
 const payload={schema:'second-run/compute-decision@1',version:C.VERSION,createdAt:new Date().toISOString(),title,kind,inputs:p,catalog,result,authority:'PLANNING_ONLY'};const e=seal(payload);state.saved.unshift(e);state.saved=state.saved.slice(0,12);const persisted=persistSaved();renderWork();toast(persisted?'Saved locally with inputs, sources and a recomputable result.':'Saved in this session. Browser storage is unavailable; export the decision to retain it.');}catch(e){toast(e.message);}}
function persistSaved(){let persisted=true;try{localStorage.setItem('second-run-compute-decisions-v1',JSON.stringify(state.saved));}catch{persisted=false;toast('Browser storage unavailable. Export the decision to retain it.');}$('saved-count').textContent=state.saved.length;return persisted;}
try{const s=JSON.parse(localStorage.getItem('second-run-compute-decisions-v1')||'[]');if(Array.isArray(s))state.saved=s.slice(0,12).map(verifySaved);}catch{state.saved=[];}
$('saved-count').textContent=state.saved.length;
$('saved-top').onclick=()=>{switchTab('work');$('saved-list').scrollIntoView({block:'center'});};
$('save-own').onclick=()=>saveDecision('own');$('save-reuse').onclick=()=>saveDecision('reuse');
$('delete-saved').onclick=()=>{if(state.saved.length&&confirm('Remove the saved decisions from this browser? Exported files remain unchanged.')){state.saved=[];persistSaved();renderWork();}};
function showDecision(e){if(e?.schema==='second-run/qualified-decision@1')return showQualified(e);const p=verifySaved(e).payload;const table=p.kind==='market'?`<table><thead><tr><th>Configuration</th><th class="num">Period cost</th></tr></thead><tbody>${p.result.options.map(o=>`<tr><td>${esc(providerName(o.provider))} · ${o.gpus} × ${esc(o.gpu)}</td><td class="num">${money(o.total)}</td></tr>`).join('')}</tbody></table>`:p.kind==='own'?`<div class="statgrid"><div><div class="eyebrow">Own / month</div><div class="v">${money(p.result.ownershipMonthly)}</div></div><div><div class="eyebrow">Rent / month</div><div class="v">${money(p.result.rentalMonthly)}</div></div></div>`:`<div class="statgrid"><div><div class="eyebrow">Baseline total</div><div class="v">${money(p.result.baselineTotal)}</div></div><div><div class="eyebrow">Proposed total</div><div class="v">${money(p.result.proposedTotal)}</div></div></div>`;
 modal(p.title,`<div class="row between"><span class="badge amber">Recomputed scenario</span><span class="small muted">${esc(p.createdAt.slice(0,16).replace('T',' '))} UTC</span></div><div style="margin-top:20px">${table}</div><p class="footnote" style="margin-top:15px">${esc(p.result.basis||p.result.status||'PROPOSAL')}. This saved object authorizes no execution or purchase.</p><details><summary>Inputs and source record</summary><pre>${esc(JSON.stringify(p.inputs,null,2))}</pre><p class="mono">SHA-256 ${e.sha256}</p></details><div class="dialogactions"><button class="primary" id="export-decision">Export decision</button><button id="export-summary">Printable summary</button><button id="reprice">Recompute with this price schedule</button></div>`);
 $('export-decision').onclick=()=>download('compute-decision.json',JSON.stringify(e,null,2)+'\n');$('export-summary').onclick=()=>download('compute-decision.html',`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(p.title)}</title><style>body{font:15px/1.6 system-ui;max-width:850px;margin:40px auto;padding:20px;color:#182024}h1{font-size:30px}table{width:100%;border-collapse:collapse}td,th{padding:10px;border-bottom:1px solid #bbb;text-align:left}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:12px/1.6 monospace}.eyebrow{font-size:12px}.v{font-size:25px}.statgrid{display:flex;gap:50px}</style><h1>${esc(p.title)}</h1><p>Second Run Compute · ${esc(p.createdAt)} · Planning scenario</p>${table}<h2>Inputs</h2><pre>${esc(JSON.stringify(p.inputs,null,2))}</pre><p>Price snapshot: ${esc(p.catalog.reviewedOn)}. No hardware performance or availability claim. Sources are retained in the companion decision JSON.</p><p>Payload SHA-256: ${e.sha256}</p></html>`,'text/html');
 $('reprice').onclick=()=>{if(p.kind!=='market'){toast('Ownership and route scenarios preserve their entered rates. Create a new scenario after selecting a current allocation.');return;}const inputs={...p.inputs,asOf:$('as-of').value};const result=C.plan(catalog,inputs),payload={...p,createdAt:new Date().toISOString(),inputs,catalog,result,previous:e.sha256};state.saved.unshift(seal(payload));state.saved=state.saved.slice(0,12);persistSaved();renderWork();showDecision(state.saved[0]);};
}
function connectDialog(){modal('Connect the qualification instrument',`<p>The instrument owns evaluations and publishes immutable records. This decision desk reads and recomputes those records without creating another execution queue.</p><h3>Start the instrument</h3><pre>node hot-aisle/runner/bin/workload.cjs serve --port 8787</pre><h3>Connect the desk</h3><pre>node compute/scripts/connect.cjs --port 8765 --runner http://127.0.0.1:8787</pre><p>Open the private localhost link printed by the desk. Publish a record in the instrument, then refresh this workspace.</p><details><summary>Existing evidence and hardware inputs</summary><p>Optional: <code>--results /approved/results</code>, <code>--aperture /path/to/aperture-support.json</code>, <code>--endpoint http://127.0.0.1:8000</code>. These are read-only fallbacks, not an evaluation runner.</p></details><h3>MCP</h3><pre>node compute/scripts/connect.cjs --mcp --runner http://127.0.0.1:8787</pre><div class="dialogactions"><a href="compute-kit.zip" download>Desk offline + MCP kit</a><button id="copy-local">Copy desk command</button></div><p class="hint">The combined integration kit includes both components. Cloud credentials stay with the instrument. No public website receives them.</p>`);$('copy-local').onclick=()=>copy('node compute/scripts/connect.cjs --port 8765 --runner http://127.0.0.1:8787');}
$('connect-top').onclick=connectDialog;$('connect-work').onclick=connectDialog;
$('copy-mcp').onclick=()=>copy(JSON.stringify({mcpServers:{'second-run-compute':{command:'node',args:['/absolute/path/compute/scripts/connect.cjs','--mcp','--runner','http://127.0.0.1:8787']}}},null,2));
function renderWork(){
 renderPublications();
 $('saved-count').textContent=state.saved.length;$('saved-list').innerHTML=state.saved.length?state.saved.map((e,i)=>`<div class="workrow"><div><h3>${esc(e.payload.title)}</h3><p>${esc(e.payload.createdAt.slice(0,16).replace('T',' '))} UTC · ${esc(e.payload.kind)} · ${e.sha256.slice(0,12)}</p></div><div class="row"><span class="badge">${e.payload.kind==='qualified-record'?'Instrument decision':'Saved scenario'}</span><button data-saved="${i}">Open decision ↗</button></div></div>`).join(''):'<p class="empty">Save a shortlist, ownership comparison or route proposal. Your assumptions travel with it.</p>';
 for(const b of document.querySelectorAll('[data-saved]'))b.onclick=()=>showDecision(state.saved[Number(b.dataset.saved)]);
 $('run-list').innerHTML=state.runs.length?state.runs.map((r,i)=>`<div class="workrow"><div><h3>${esc(r.title||r.model||'Benchmark result')}</h3><p>${r.synthetic?'Synthetic fixture':'Supplied benchmark'} · ${r.trials} trial${r.trials===1?'':'s'} · ${nfmt(r.completed,0)} completed · ${nfmt(r.duration,1)} seconds</p></div><button data-run="${i}">Inspect result ↗</button></div>`).join(''):'<p class="empty">No observed runs yet. Connect a directory or explore the sample.</p>';
 for(const b of document.querySelectorAll('[data-run]'))b.onclick=()=>inspectRun(state.runs[Number(b.dataset.run)]);
 const hw=state.hardware;$('runtime-summary').innerHTML=hw?`<div class="showhelp"><b>Aperture hardware receipt</b><p>${esc(hw.cpu)} · ${hw.graphics.map(g=>esc(g.name)+(g.totalBytes?' · '+nfmt(g.totalBytes/1024**3,1)+' GiB':'')).join('<br>')}</p><p class="hint">${esc(hw.qualification)}</p></div>`:'';
 if(state.runtime&&state.runtime.status!=='NOT_CONFIGURED'){$('runtime-summary').innerHTML+=`<div class="showhelp"><b>${state.runtime.status==='OBSERVED'?'Connected runtime':'Runtime observation unavailable'}</b><p>${state.runtime.models?.map(esc).join(' · ')||esc(state.runtime.message||'')}</p><p class="hint">GET /v1/models and selected metrics only. Endpoint reachability is not a benchmark.</p></div>`;}
}
/* Instrument records are recomputed by generated instrument code, never by Compute. */
function renderPublications(){
 const rows=state.publications||[];
 $('publication-list').innerHTML=rows.length?rows.map((p,i)=>`<div class="workrow"><div><h3>${esc(p.model)}</h3><p>${p.synthetic?'Synthetic integration run':'Producer-run record'} · ${p.completed_trials}/${p.expected_trials} planned trials · ${p.qualified?'primary cell meets requirements':'requirements not met'}${p.complete?'':' · partial campaign'}</p><p class="mono small">${esc(p.record_sha256.slice(0,16))}</p></div><button data-publication="${i}">Review qualified record ↗</button></div>`).join(''):'<p class="empty">Publish a completed or partial record in the connected instrument. It appears here automatically when you refresh. Raw benchmark files remain an import fallback.</p>';
 $('publication-state').textContent=state.instrumentStatus==='CONNECTED'?'Connected instrument · '+(state.catalogMatch||'catalogue not observed'):state.instrumentStatus==='UNAVAILABLE'?'Instrument unavailable · retained observations shown':'Connect the qualification instrument';
 for(const b of document.querySelectorAll('[data-publication]'))b.onclick=async()=>{try{const p=rows[Number(b.dataset.publication)],bundle=p.bundle||await api('/api/publications/'+p.publication_id);Q.publication.verify(bundle);p.bundle=bundle;showQualified(Q.decision(bundle));}catch(e){toast('Record held: '+e.message);}};
}
function showQualified(envelope){
 const p=Q.verifyDecision(envelope).payload,rec=p.bundle.record,view=Q.publication.projection(p.bundle),primary=view.cell;
 const a=primary?.aggregate,c=primary?.cost;
 const scenario=p.change?p.result.scenario:null;
 modal(p.title,`<div class="row between"><span class="badge ${rec.synthetic?'amber':''}">${rec.synthetic?'Synthetic integration record':'Producer evidence · recomputed'}</span><span class="mini">${view.completed_trials}/${view.expected_trials} planned trials</span></div>
 <div class="statgrid"><div><div class="eyebrow">Recorded cost / 1,000</div><div class="v accent">${money(c?.costPer1000,4)}</div><p>${esc(a?.unit||'unit unavailable')}</p></div><div><div class="eyebrow">p95 first token</div><div class="v">${nfmt(a?.metrics.ttft.p95,1)} ms</div></div><div><div class="eyebrow">Primary concurrency</div><div class="v">${view.primary_concurrency??'—'}</div></div></div>
 <p class="small">${esc(rec.disposition.reasons.join(' '))} ${view.complete?'All planned trials are retained.':'Partial campaign. Qualification of a measured cell does not complete the plan.'}</p>
 <div class="modelnotice"><b>${rec.synthetic?'Software demonstration.':'Scoped producer record.'}</b> ${rec.synthetic?'Fixture measurements exercise the complete integration; they are not a GPU comparison.':'The verified object preserves observed trials and supplied identity, price and acceptance rules.'} A comparator price threshold is not a measured competitor result.</div>
 <table><thead><tr><th>Concurrency</th><th class="num">Trials</th><th class="num">Cost / 1,000</th><th>Requirements</th></tr></thead><tbody>${rec.derived.cells.map(x=>`<tr><td>${x.concurrency}</td><td class="num">${x.runs}</td><td class="num">${money(x.cost?.costPer1000,4)}</td><td>${x.meets?'Meets':'Held'}</td></tr>`).join('')}</tbody></table>
 <details ${p.change?'open':''}><summary>Reprice this same measured allocation</summary><p class="hint">A new price creates a linked scenario from the retained trials. It runs no benchmark and transfers no performance to different hardware.</p><div class="row"><div class="field"><label for="qualified-rate">Price / GPU-hour, USD</label><input type="number" id="qualified-rate" min="0" step="any" value="${esc(String(p.change?.price?.rate??rec.declared.price.rate))}"></div><button id="qualified-reprice">Recompute price only</button></div>${scenario?`<div id="qualified-scenario" class="showhelp"><b>Repriced scenario · no GPU execution</b><p>${scenario.cells.map(x=>'c'+x.concurrency+': '+money(x.cost_per_1000,4)+' / 1,000').join(' · ')}</p></div>`:''}</details>
 <details><summary>Retained identity and verification</summary><p class="mono">Record SHA-256: ${esc(rec.sha256)}</p><p class="mono">Evidence SHA-256: ${esc(p.bundle.evidence.sha256)}</p><p class="mono">Decision SHA-256: ${esc(envelope.sha256)}</p>${p.previous?`<p class="mono">Previous decision: ${esc(p.previous)}</p>`:''}<p class="small">Engine ${esc(Q.authority.engine.version)}. Source identity and raw producer authenticity are separate from calculation verification.</p><pre>${esc(JSON.stringify({allocation:rec.scenario.allocation,requirements:rec.rule.requirements,price:rec.declared.price},null,2))}</pre></details>
 <div class="dialogactions"><button class="primary" id="qualified-save">Save this decision locally</button><button id="qualified-export">Export decision</button><button id="qualified-report">Instrument report</button></div>`);
 $('qualified-save').onclick=()=>{if(!state.saved.some(e=>e.sha256===envelope.sha256))state.saved.unshift(envelope);state.saved=state.saved.slice(0,12);persistSaved();renderWork();toast('Retained locally with its qualified record and sealed evidence.');};
 $('qualified-export').onclick=()=>download('qualified-decision.json',JSON.stringify(envelope,null,2)+'\n');
 $('qualified-report').onclick=()=>download('instrument-report.html',Q.record.receipt(rec),'text/html');
 $('qualified-reprice').onclick=()=>{try{const rate=val('qualified-rate');if(rate<0)throw Error('Price must be nonnegative.');const e=Q.decision(p.bundle,{price:{rate}},new Date().toISOString(),envelope.sha256);showQualified(e);}catch(e){toast(e.message);}};
}

function normalizeImported(bytes){const source=H.sha256(bytes),docs=H.parseDocuments(new TextDecoder('utf-8',{fatal:true}).decode(bytes));const rows=docs.map((d,i)=>H.normalize(d,{sha256:source,bytes:bytes.byteLength,record_index:i}));const aggregate=H.aggregate(rows,{identity:{}});return {id:source,title:aggregate.identity.model||'Unnamed workload',model:aggregate.identity.model,trials:rows.length,completed:aggregate.completed,duration:aggregate.duration,synthetic:aggregate.synthetic,aggregate,normalized:rows,sha256:source};}
async function inspectRun(run){try{if(!run.aggregate&&state.connected){run=await api('/api/runs/'+run.id);}const a=run.aggregate;if(!a)throw Error('No normalized evidence available.');modal(run.title||'Observed workload',`<div class="row between"><span class="badge ${a.synthetic?'amber':''}">${a.synthetic?'Synthetic fixture':'Producer evidence'}</span><span class="mini">${run.sha256?.slice(0,16)||''}</span></div><div class="statgrid"><div><div class="eyebrow">Completed / second</div><div class="v">${nfmt(a.rate,3)}</div></div><div><div class="eyebrow">Completed</div><div class="v">${nfmt(a.completed,0)}</div></div><div><div class="eyebrow">Measured seconds</div><div class="v">${nfmt(a.duration,2)}</div></div></div><p class="small">${esc(a.unit)}. Cost is a separate declaration of which allocation was billed.</p><div class="field"><label for="run-offer">Attach a price scenario</label><select id="run-offer">${catalog.offers.map(o=>`<option value="${o.id}">${esc(providerName(o.provider)+' · '+o.gpus+' × '+o.gpu)}</option>`).join('')}</select></div><div id="run-economics" class="showhelp"></div><details><summary>Workload identity and latency basis</summary><pre>${esc(JSON.stringify({identity:a.identity,metrics:a.metrics,holds:a.holds},null,2))}</pre></details><div class="dialogactions"><button id="run-export">Export normalized observation</button></div>`);
 function draw(){const o=catalog.offers.find(o=>o.id===$('run-offer').value),q=C.quote(o,{asOf:$('as-of').value,hours:a.duration/3600});$('run-economics').innerHTML=`<b>${a.completed?money(q.total/a.completed*1000,4):'No finite cost'} / 1,000 completed responses</b><p>Modeling the supplied result on ${esc(providerName(o.provider)+' '+o.gpu)} pricing. This does not establish where the benchmark ran or transfer its speed to another GPU. ${q.minimumApplied?'Minimum commitment applied.':''}</p>`;}$('run-offer').value='ha-mi300x-1';$('run-offer').onchange=draw;draw();$('run-export').onclick=()=>download('normalized-workload.json',JSON.stringify(run,null,2)+'\n');
 }catch(e){toast(e.message);}}
$('sample-work').onclick=()=>{try{state.runs=['a','b'].map(s=>normalizeImported(new TextEncoder().encode(JSON.stringify(samples[s]))));renderWork();toast('Loaded synthetic examples, clearly labeled.');}catch(e){toast(e.message);}};
$('import-files').onchange=async e=>{try{const files=[...e.target.files];if(files.length>20||files.reduce((n,f)=>n+f.size,0)>50*1024*1024)throw Error('Import at most 20 files / 50 MiB.');let next=[...state.runs],hardware=state.hardware,saved=[...state.saved],publications=[...state.publications];for(const f of files){if(f.size>25*1024*1024)throw Error('Each file must be at most 25 MiB.');const bytes=new Uint8Array(await f.arrayBuffer());let raw;try{raw=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes));}catch{}
 if(raw?.schema==='hot-aisle/publication@1'){Q.publication.verify(raw);publications.unshift({...Q.publication.projection(raw),bundle:raw});}else if(raw?.schema==='second-run/qualified-decision@1'){saved.unshift(Q.verifyDecision(raw));}else if(raw?.schema==='aperture-support/1'){hardware=C.aperture(raw);}else if(raw?.schema==='second-run/sealed-compute-decision@1'){const q=verifySaved(raw);saved.unshift(q);}else{const run=normalizeImported(bytes);if(next.some(r=>r.id===run.id))throw Error('Duplicate source file. Existing evidence retained.');next.push(run);}}
 state.runs=next;state.hardware=hardware;state.publications=publications;state.saved=saved.slice(0,12);if(saved.length)persistSaved();$('import-error').textContent='';renderWork();toast('Imported and normalized locally.');}catch(err){$('import-error').textContent=err.message;}finally{e.target.value='';}};
$('verify-decision').onclick=()=>$('verify-input').click();$('verify-input').onchange=async e=>{try{const f=e.target.files[0];if(!f||f.size>5*1024*1024)throw Error('Select a decision file smaller than 5 MiB.');const envelope=verifySaved(JSON.parse(await f.text()));showDecision(envelope);toast('Checksum and recomputed result match.');}catch(err){toast(err.message);}finally{e.target.value='';}};
async function api(path){if(!state.token)throw Error('No local connection.');const r=await fetch(path,{headers:{Authorization:'Bearer '+state.token},cache:'no-store',redirect:'error'});if(!r.ok)throw Error('Local helper returned '+r.status+'.');return r.json();}
async function refreshWorkspace(){$('connection-status').textContent='CONNECTING';try{const s=await api('/api/status'),r=await api('/api/runs');state.connected=true;state.runs=r.runs;state.hardware=s.hardware;state.runtime=s.runtime;let notice=r.holds?.length?r.holds.length+' raw input(s) held. ':'';
 try{const publications=await api('/api/publications');state.instrumentStatus=publications.status;state.catalogMatch=publications.catalog?.state||null;if(publications.status==='CONNECTED'){state.publications=publications.publications;if(publications.holds.length)notice+=publications.holds.length+' publication(s) held. ';}}catch(e){state.instrumentStatus='UNAVAILABLE';notice+='Instrument unavailable; previously observed records retained. ';}
 $('connection-status').textContent='CONNECTED · '+state.publications.length+' PUBLISHED RECORDS';$('connection-error').textContent=notice;$('connect-top').textContent='Workspace connected';$('refresh-work').disabled=false;renderWork();}catch(e){state.connected=false;state.instrumentStatus='UNAVAILABLE';state.runtime=null;$('connection-status').textContent='DISCONNECTED';$('connection-error').textContent=e.message+' Existing observations remain available.';$('connect-top').textContent='Reconnect workspace';renderWork();}}
$('refresh-work').onclick=refreshWorkspace;
for(const p of catalog.providers){const o=document.createElement('option');o.value=p.id;o.textContent=p.name;$('provider').append(o);}
for(const id of ['rental-offer','premium-offer']){for(const o of catalog.offers){const el=document.createElement('option');el.value=o.id;el.textContent=providerName(o.provider)+' · '+o.gpus+' × '+o.gpu;$(id).append(el);}}
$('rental-offer').value='rp-3090';$('premium-offer').value='ha-mi300x-1';
$('legend').innerHTML=catalog.providers.map(p=>`<span class="p-${p.id}"><i></i>${p.letter}</span>`).join('');$('provider-count').textContent=catalog.providers.length;$('offer-count').textContent=catalog.offers.length;
const freshness=C.freshness(catalog,new Date().toISOString().slice(0,10));if(freshness.status==='STALE'||freshness.status==='FUTURE_SNAPSHOT'){$('stale-banner').hidden=false;$('stale-banner').textContent=freshness.status==='STALE'?'Price review is '+freshness.ageDays+' days old. Historical comparisons remain available; verify current quotes before purchasing.':'This price snapshot is dated in the future relative to your clock.';}
if(new Date().toISOString().slice(0,10)>='2026-10-01')$('as-of').value='2026-10-01';
routeFields();footprint();renderMarket();renderOwn();renderReuse();renderWork();
function resumeLocalConnection(){try{if(['127.0.0.1','localhost'].includes(location.hostname)){const hash=new URLSearchParams(location.hash.slice(1));const token=hash.get('connection')||sessionStorage.getItem('compute-local-session');if(token&&/^[a-f0-9]{64}$/.test(token)){state.token=token;sessionStorage.setItem('compute-local-session',token);history.replaceState(null,'',location.pathname);switchTab('work');refreshWorkspace();}}}catch{}}
// Private links can arrive after the public desk is already open: a fragment-only
// navigation does not rerun page initialization. Consume and remove it here too.
window.addEventListener('hashchange',resumeLocalConnection);
resumeLocalConnection();
