'use strict';
const assert=require('node:assert/strict');
const test=require('node:test');
const D=require('./foundation.js'),C=D.core;
test('exact native owner computes the baseline',async()=>{const w=await D.create(),v=await D.view(w);assert.equal(v.calc.data.winner,'configuration-b');assert.deepEqual(v.calc.data.results.map(x=>x.accepted),[12,20]);assert.equal(v.reports.length,1);assert.equal(v.policy.data.cost_basis,'quote');});
test('format correction preserves the original and selects a successor',async()=>{let w=await D.create();const frozen=C.canonical(C.state(w).reports[0]);const raw=C.canonical(C.latest(C.state(w),'run-a').data.tasks);w=await D.change(w,{grader:'extract_json'});assert.equal((await D.view(w)).current.current,false);await D.recompute(w);const v=await D.view(w);assert.equal(v.calc.data.winner,'configuration-a');assert.deepEqual(v.calc.data.results.map(x=>x.accepted),[22,20]);assert.equal(v.review.ready,false);assert.equal(C.canonical(v.reports[0]),frozen);assert.equal(C.canonical(C.latest(C.state(w),'run-a').data.tasks),raw);});
test('stale reviews and unreviewed editions refuse',async()=>{let w=await D.create();w=await D.change(w,{grader:'extract_json'});await assert.rejects(()=>D.reviewed(w,'Tester','Long enough rationale for changed state.'));await D.recompute(w);await assert.rejects(()=>D.sealed(w,'Tester'));});
test('explicit review retains successor without altering earlier delivery',async()=>{let w=await D.create();const old=C.canonical(C.state(w).reports[0]);w=await D.change(w,{grader:'extract_json'});await D.recompute(w);w=await D.reviewed(w,'Tester','Reviewed the explicit output contract and complete cost.');w=await D.sealed(w,'Tester');const v=await D.view(w);assert.equal(v.reports.length,2);assert.equal(C.canonical(v.reports[0]),old);await assert.rejects(()=>D.sealed(w,'Tester'));});
test('invalid edits preserve the input workspace',async()=>{const w=await D.create(),before=C.canonical(w);await assert.rejects(()=>D.change(w,{costA:-1}));await assert.rejects(()=>D.change(w,{costA:NaN}));await assert.rejects(()=>D.change(w,{grader:'invented'}));assert.equal(C.canonical(w),before);});
test('quote change keeps performance but changes economics',async()=>{let w=await D.create();const old=(await D.view(w)).calc.data.results;w=await D.change(w,{costA:1.2});await D.recompute(w);const next=(await D.view(w)).calc.data.results;assert.deepEqual(next.map(x=>x.accepted),old.map(x=>x.accepted));assert.equal(next[0].cost_per_success,old[0].cost_per_success/2);});
test('packet roundtrip and tamper refusal use the native journal',async()=>{const w=await D.create(),p=await D.pack(w);assert.deepEqual(await D.restore(p),w);p.workspace.label='Changed';await assert.rejects(()=>D.restore(p));});
test('withdrawn source holds recomputation',async()=>{let w=await D.create();w=await D.correctSource(w);assert.equal((await D.view(w)).current.current,false);await assert.rejects(()=>D.recompute(w));});
test('one JSON object is the actual acceptance contract',()=>{assert.equal(C.grade('prefix {"a":1} suffix',{a:1},'extract_json'),true);assert.equal(C.grade('{"a":1} {"a":1}',{a:1},'extract_json'),false);assert.equal(C.grade('{"a":0}',{a:1},'extract_json'),false);});
test('compatible IDs alone do not establish the workflow kinds',async()=>{const w=C.empty('Invalid compatible names');await C.put(w,{id:'source',kind:'claim',title:'Wrong kind',summary:'Synthetic incompatible packet',tier:'synthetic',disposition:'draft',data:{id:D.meta.id},deps:[]},'Test');const p=await C.pack(w);await assert.rejects(()=>D.restore(p));});

// ---- Hardware decision class (1.0.2 candidate). SYNTHETIC fixture: 2 arms x 50 authored requests, not Run 3 data. ----
const at='2026-09-29T00:00:00Z';
function hwArm(letter){const A=letter==='a',tasks=[];for(let i=0;i<50;i++){
 const correct=A?i%5!==0:i%4!==0,first_token_ms=A?(i%7===0?1500:200):(i%11===0?2500:100),elapsed_ms=A?(i===13?70000:5000):3000;
 tasks.push({id:'req-'+i,scheduled_at_ms:i*1000,attempts:[{status:'ok',first_token_ms,elapsed_ms,correct}]});}
 return {schema:'second-run/task-run@1',run_id:'arm-'+letter,label:'Synthetic arm '+letter.toUpperCase(),evidence:'synthetic',
  pins:{taskset:'synthetic-50',contract:'recorded-correct',load:'synthetic-1rps',boundary:'scheduled-arrival-to-release',model:'synthetic-model',revision:'r1',precision:'fp8',tokenizer:'t1',runtime:'synthetic-runtime 1.0',cache:'none'},
  identity:{vendor:A?'Vendor A':'Vendor B',hardware:A?'1x GPU-A':'1x GPU-B',arm:A?'A/S0':'B/S0',runtime:'synthetic-runtime 1.0',window_minutes:60,window_basis:A?'own_seat_equivalent':'closed_ledger'},
  tasks,billing:{rate_usd_per_hour:A?2.99:4.41,cost_basis:'list',currency:'USD',scope:'SYNTHETIC list rate for a 60-minute authored window.'}};}
const hwPolicy={grader:'recorded',deadline_ms:60000,first_token_ms:1000,quality_floor:.5,min_tasks:50,cost_basis:'list',comparison_mode:'hardware'};
async function hwCreate(){const ws=C.empty('SYNTHETIC hardware decision fixture'),rec=(id,kind,data,deps=[])=>({id,kind,title:id,summary:'SYNTHETIC authored fixture, not a measurement.',tier:'synthetic',disposition:kind==='source'?'observed':'draft',data,deps}),ref=r=>({id:r.id,revision:r.revision});
 const src=await C.put(ws,rec('source-synthetic','source',{synthetic:true}),'Test',at),pol=await C.put(ws,rec('policy','policy',hwPolicy,[ref(src)]),'Test',at);
 const runs=[];for(const l of ['a','b'])runs.push(await C.put(ws,rec('run-'+l,'run',hwArm(l),[ref(src)]),'Test',at));
 const cmp=C.compare(runs.map(r=>r.data),pol.data);const calc=await C.put(ws,rec('calculation','calculation',{...cmp,selectedRecordIds:runs.map(r=>r.id),recipe:'task-cost@1'},[ref(pol),...runs.map(ref)]),'Test',at);
 await C.put(ws,rec('decision','conclusion',{winner:cmp.winner},[ref(calc),ref(src)]),'Test',at);await C.review(ws,'decision','accept','Synthetic hardware fixture review; label only.','Test reviewer',at);await C.freeze(ws,'decision','Test reviewer',at);return ws;}
test('decision class is declared by the policy',async()=>{assert.equal(D.decisionClass(await D.create()),'task');assert.equal(D.decisionClass(await hwCreate()),'hardware');assert.equal((await D.view(await D.create())).decisionClass,'task');});
test('recorded grader joins correctness, first token and completion deadline',async()=>{const w=await hwCreate(),v=await D.view(w),[a,b]=v.calc.data.results;
 assert.deepEqual([a.accepted,b.accepted],[33,34]);assert.deepEqual([a.quality,b.quality],[40,37]);assert.equal(a.strip.length,50);assert.equal(a.strip[7],'f');assert.equal(a.strip[13],'l');assert.equal(a.strip[5],'x');assert.equal(a.strip[1],'a');
 assert.deepEqual([a.first_token_late,a.completion_late,a.incorrect,a.not_completed],[6,1,10,0]);assert.equal(a.total_usd,2.99*60/60);assert.equal(a.cost_per_success,2.99/33);assert.equal(v.calc.data.winner,'arm-a');assert.match(v.flip,/^A\/S0 \(1x GPU-A, Vendor A\) is the lowest-cost eligible arm per 1,000 accepted: \$90\.61 at \$2\.99\/h against B\/S0 \$129\.71\.$/);});
test('rate scenario flips the winner by arithmetic and keeps Edition 01',async()=>{let w=await hwCreate();const frozen=C.canonical(C.state(w).reports[0]),raw=C.canonical(C.latest(C.state(w),'run-b').data.tasks);
 w=await D.change(w,{rates:{'arm-b':2.49}});assert.equal((await D.view(w)).current.current,false);await D.recompute(w);const v=await D.view(w);
 assert.equal(v.calc.data.winner,'arm-b');assert.deepEqual(v.calc.data.results.map(x=>x.accepted),[33,34]);assert.equal(v.calc.data.results[1].cost_per_success,2.49/34);assert.match(v.decision.summary,/no new model run/);assert.equal(C.canonical(C.latest(C.state(w),'run-b').data.tasks),raw);
 w=await D.reviewed(w,'Test reviewer','Rate scenario reviewed as arithmetic over retained records.');w=await D.sealed(w,'Test reviewer');assert.equal(C.state(w).reports.length,2);assert.equal(C.canonical(C.state(w).reports[0]),frozen);assert.deepEqual(await D.restore(await D.pack(w)),w);});
test('first-token limit is an assumption edit in the acceptance rule',async()=>{let w=await hwCreate();w=await D.change(w,{first_token_ms:3000});await D.recompute(w);assert.deepEqual((await D.view(w)).calc.data.results.map(x=>x.accepted),[39,37]);w=await D.change(w,{deadline_ms:4000});await D.recompute(w);assert.deepEqual((await D.view(w)).calc.data.results.map(x=>x.accepted),[0,37]);});
test('hardware changes refuse task fields and invalid values; task class refuses rates',async()=>{const w=await hwCreate(),before=C.canonical(w);
 for(const bad of [{grader:'extract_json'},{costA:1},{rates:{'arm-b':-1}},{rates:{'arm-b':NaN}},{rates:{nope:1}},{first_token_ms:0},{rates:{'arm-b':4.41}},{}])await assert.rejects(()=>D.change(w,bad));assert.equal(C.canonical(w),before);
 const t=await D.create();await assert.rejects(()=>D.change(t,{rates:{'run-b':1}}));await assert.rejects(()=>D.change(t,{first_token_ms:500}));});
test('tampered arm rate with a rebuilt journal fails the recompute rule',async()=>{const p=await D.pack(await hwCreate());
 const e=p.workspace.events.find(x=>x.type==='record'&&x.payload.id==='run-b');e.payload.data.billing.rate_usd_per_hour=1.0;
 let prev='0'.repeat(64);for(const ev of p.workspace.events){ev.prev=prev;const {hash,...body}=ev;ev.hash=await C.hash(body);prev=ev.hash;}p.sha256=await C.hash(p.workspace);
 await assert.rejects(()=>D.restore(p),/Derived calculation does not recompute from its pinned inputs/);});
test('hardware policy terms travel together',()=>{for(const bad of [{...hwPolicy,comparison_mode:'task'},{...hwPolicy,cost_basis:'quote'},{...hwPolicy,grader:'strict_json'},{...hwPolicy,first_token_ms:undefined}])assert.throws(()=>C.validatePolicy(bad));C.validatePolicy(hwPolicy);
 assert.throws(()=>C.evaluate(hwArm('a'),{...hwPolicy,grader:'strict_json',cost_basis:'quote'}),/arm records require recorded grading/);});
