/* GENERATED by integration/build.py from the instrument sources. */
(function(root,factory){const H=typeof module==='object'&&module.exports?require('./workload-engine.cjs'):root.HA;const api=factory(H);if(typeof module==='object'&&module.exports)module.exports=api;root.WorkloadQualification=api;})(typeof globalThis!=='undefined'?globalThis:this,function(HA){
'use strict';
const authority={"engine": {"engine_sha256": "78600d009f43ca37a81fa15231dfb5be307d8b0a01cfcfe42d94ed8015061593", "version": "2.0.0"}, "sources": {"publication": "ca7b940782c8a10166525b59073ef5181d690b278651236d7fbec91f6e6e2cd0", "record": "00c4bdd43fe2edff1b7681a10417023701be0fc83fbe2a0484e94e50708c8960", "revalidate": "41827343a9223c7764d52c9e16ec40d6fe61a044996f0fa286f04ca10dca2cf5"}};
const engine={load:()=>HA,identity:()=>authority.engine,sha256:x=>HA.sha256(typeof x==='string'?new TextEncoder().encode(x):x)};
const record=(()=>{
'use strict';
/* The qualified record: one durable object that separates what was observed, what the
   operator declared, which acceptance rule applied and which economic scenario was
   priced. Every visible number (headline, report, agent summary, evidence packet) is
   a projection computed from it through the page's engine. Nothing is typed twice. */


function cells(job) {
  const HA = engine.load();
  const plan = job.plan;
  const byConcurrency = new Map();
  for (const t of job.trials) if (t.status === 'completed') { if (!byConcurrency.has(t.cell.concurrency)) byConcurrency.set(t.cell.concurrency, []); byConcurrency.get(t.cell.concurrency).push(t); }
  const out = [];
  for (const [concurrency, trials] of [...byConcurrency.entries()].sort((a, b) => a[0] - b[0])) {
    const runs = trials.map(t => HA.restoreRun(t.normalized));
    const settings = { identity: declaredIdentity(plan), ttft: plan.gates.ttft, e2e: plan.gates.e2e, queue: plan.gates.queue, quality: plan.gates.quality };
    let aggregate, cost, error = null;
    try { aggregate = HA.aggregate(runs, settings); cost = HA.costing(aggregate, plan.price); } catch (e) { error = e.message; }
    const check = aggregate ? requirements(aggregate, plan.requirements) : { meets: false, reasons: [error] };
    out.push({ concurrency, trials: trials.map(t => ({ cell: t.cell, source: t.source, normalized: t.normalized })), settings, aggregate: aggregate || null, cost: cost || null, meets: check.meets, reasons: check.reasons, error });
  }
  return out;
}

function declaredIdentity(plan) {
  const map = { model_revision: 'revision', precision: 'precision', tokenizer_revision: 'tokenizer', cache_policy: 'cache', runtime_digest: 'runtime', workload_id: 'workload' };
  const out = {};
  for (const [k, id] of Object.entries(map)) if (plan.identity[k]) out[id] = plan.identity[k];
  return out;
}

function requirements(a, req) {
  const reasons = [];
  if (a.holds.length) reasons.push(...a.holds);
  if (req.max_p95_ttft_ms !== null && req.max_p95_ttft_ms !== undefined) { const v = a.metrics.ttft.p95; if (v === null) reasons.push('p95 TTFT unavailable.'); else if (v > req.max_p95_ttft_ms) reasons.push('p95 TTFT ' + v.toFixed(0) + ' ms exceeds ' + req.max_p95_ttft_ms + ' ms.'); }
  if (req.max_p95_e2e_ms !== null && req.max_p95_e2e_ms !== undefined) { const v = a.metrics.e2e.p95; if (v === null) reasons.push('p95 E2E unavailable.'); else if (v > req.max_p95_e2e_ms) reasons.push('p95 E2E ' + v.toFixed(0) + ' ms exceeds ' + req.max_p95_e2e_ms + ' ms.'); }
  if (req.min_accepted_per_s !== null && req.min_accepted_per_s !== undefined) { if (a.rate === null) reasons.push('Accepted rate unavailable.'); else if (a.rate < req.min_accepted_per_s) reasons.push('Accepted rate ' + a.rate.toFixed(3) + '/s below ' + req.min_accepted_per_s + '/s.'); }
  if (req.max_failure_rate !== null && req.max_failure_rate !== undefined) { if (a.failureRate === null) reasons.push('Failure rate unavailable.'); else if (a.failureRate > req.max_failure_rate) reasons.push('Failure rate ' + (a.failureRate * 100).toFixed(1) + '% exceeds ' + (req.max_failure_rate * 100) + '%.'); }
  return { meets: !reasons.length, reasons };
}

function derive(rec) {
  const HA = engine.load();
  const job = { plan: rec.declared.plan, trials: rec.observed.trials.map(t => ({ status: 'completed', cell: t.cell, source: t.source, normalized: t.normalized })) };
  const cs = cells(job);
  const primary = pickPrimary(cs, rec.declared.plan.primary_concurrency);
  let comparison = null;
  if (rec.declared.comparator && primary && primary.cost) {
    const pc = rec.declared.comparator;
    comparison = { kind: 'price_threshold', provider: pc.provider, allocation_hour_usd: pc.gpus * pc.rate + (pc.extra || 0), required_rate_to_tie: primary.aggregate.rate !== null && primary.cost.hourly > 0 ? HA.threshold(primary.aggregate.rate, primary.cost.hourly, pc.gpus * pc.rate + (pc.extra || 0)) : null, note: 'Price ratio only. The comparator has no measured evidence in this record.' };
  }
  const qualified = !!(primary && primary.meets && primary.aggregate && !primary.aggregate.holds.length);
  const reasons = primary ? (primary.meets ? ['Primary cell (concurrency ' + primary.concurrency + ') meets every stated requirement.'] : primary.reasons) : ['No completed cell.'];
  return {
    cells: cs.map(c => ({ concurrency: c.concurrency, runs: c.trials.length, aggregate: c.aggregate, cost: c.cost, meets: c.meets, reasons: c.reasons, error: c.error })),
    primary_concurrency: primary ? primary.concurrency : null,
    comparison,
    disposition: { qualified, reasons, cells_meeting: cs.filter(c => c.meets).map(c => c.concurrency) },
    engine: (({ version, engine_sha256 }) => ({ version, engine_sha256 }))(engine.identity()),
  };
}

function pickPrimary(cs, wanted) {
  if (!cs.length) return null;
  if (wanted !== null && wanted !== undefined) return cs.find(c => c.concurrency === wanted) || null;
  const meeting = cs.filter(c => c.meets && c.cost && c.cost.costPer1000 !== null);
  if (meeting.length) return meeting.reduce((best, c) => c.cost.costPer1000 < best.cost.costPer1000 ? c : best);
  return cs[cs.length - 1];
}

function build(job) {
  const HA = engine.load();
  const rec = {
    schema: 'hot-aisle/qualified-record@1',
    id: job.id.replace(/^job-/, 'rec-'),
    created: new Date().toISOString(),
    job_id: job.id,
    synthetic: job.plan.target.adapter === 'local' || job.trials.some(t => t.normalized && t.normalized.synthetic),
    observed: { trials: job.trials.filter(t => t.status === 'completed').map(t => ({ cell: t.cell, source: t.source, normalized: t.normalized, started: t.started, ended: t.ended })), failed_trials: job.trials.filter(t => t.status === 'failed').map(t => ({ cell: t.cell, error: t.error })), disposition: job.disposition },
    declared: { plan: job.plan, identity: job.plan.identity, price: job.plan.price, comparator: job.plan.comparator, approval: job.approval },
    rule: { gates: job.plan.gates, requirements: job.plan.requirements },
    scenario: { allocation: { label: job.plan.target.allocation_label || (job.plan.price.gpus + '× ' + (job.plan.target.gpu_model || 'GPU')), gpus: job.plan.price.gpus, gpu_model: job.plan.target.gpu_model || null, adapter: job.plan.target.adapter, deployment_id: job.plan.target.deployment_id || null } },
  };
  rec.derived = derive(rec);
  rec.disposition = rec.derived.disposition;
  rec.sha256 = engine.sha256(HA.canonical(withoutSha(rec)));
  return rec;
}

function withoutSha(rec) { const { sha256, ...rest } = rec; return rest; }

/* Recomputes the derived section from observed + declared + rule and compares it to
   the stored one. Mirrors the engine's own recompute discipline: a record whose stored
   conclusions do not follow from its evidence is not verified. */
function verify(rec) {
  const HA = engine.load();
  const problems = [];
  if (rec.schema !== 'hot-aisle/qualified-record@1') problems.push('Unsupported record schema.');
  if (engine.sha256(HA.canonical(withoutSha(rec))) !== rec.sha256) problems.push('Record checksum mismatch.');
  const {sha256:planSha,commands,...planBody}=rec.declared.plan;
  if(engine.sha256(HA.canonical(planBody))!==planSha)problems.push('Plan body does not match its identity.');
  const fresh = derive(rec);
  const strip = d => ({ ...d, engine: undefined });
  if (HA.canonical(strip(fresh)) !== HA.canonical(strip(rec.derived))) problems.push('Derived conclusions do not follow from the retained evidence.');
  if (rec.synthetic !== (rec.declared.plan.target.adapter === 'local' || rec.observed.trials.some(t => t.normalized.synthetic))) problems.push('Synthetic status mismatch.');
  if (HA.canonical(rec.disposition) !== HA.canonical(rec.derived.disposition)) problems.push('Top-level disposition differs from the derived verdict.');
  for (const key of ['price','identity','comparator'])
    if (HA.canonical(rec.declared[key]) !== HA.canonical(rec.declared.plan[key])) problems.push('Declared '+key+' differs from the approved plan.');
  for (const key of ['gates','requirements'])
    if (HA.canonical(rec.rule[key]) !== HA.canonical(rec.declared.plan[key])) problems.push('Rule '+key+' differs from the approved plan.');
  if (rec.declared.approval && rec.declared.approval.plan_sha256 !== rec.declared.plan.sha256) problems.push('Approval is bound to a different plan.');

  return { verified: !problems.length, problems, engine: fresh.engine };
}

/* Projections. */
function primaryCell(rec) { return rec.derived.cells.find(c => c.concurrency === rec.derived.primary_concurrency) || null; }

function packet(rec, concurrency = rec.derived.primary_concurrency) {
  const HA = engine.load();
  const cell = rec.derived.cells.find(c => c.concurrency === concurrency);
  if (!cell || !cell.aggregate) throw new Error('No aggregable cell at concurrency ' + concurrency + '.');
  const trials = rec.observed.trials.filter(t => t.cell.concurrency === concurrency);
  const settings = { identity: declaredIdentity(rec.declared.plan), ttft: rec.rule.gates.ttft, e2e: rec.rule.gates.e2e, queue: rec.rule.gates.queue, quality: rec.rule.gates.quality };
  const side = { id: 'a', label: rec.declared.price.provider, settings, price: rec.declared.price, normalized: trials.map(t => t.normalized), aggregate: cell.aggregate, cost: cell.cost };
  const p = { schema: 'hot-aisle/workload-report@2', version: HA.VERSION, generated_at: rec.created, title: cell.aggregate.identity.model || 'Workload cost report', synthetic: !!cell.aggregate.synthetic, sides: [side], comparison: null };
  return { schema: 'hot-aisle/sealed-report@1', sha256: engine.sha256(HA.canonical(p)), payload: p };
}

function receipt(rec, concurrency) {
  const HA = engine.load();
  const env = packet(rec, concurrency);
  return HA.receiptHTML(env.payload).replace('</footer>', '<p class="hash">Evidence JSON payload SHA-256: ' + env.sha256 + '</p><p class="hash">Qualified record ' + HA.escape(rec.id) + ' · ' + rec.sha256 + '</p></footer>');
}

function headline(rec, { evidence_url = null, report_url = null, published_on = null } = {}) {
  const cell = primaryCell(rec);
  const a = cell && cell.aggregate, c = cell && cell.cost;
  const plan = rec.declared.plan;
  const side = { label: rec.declared.price.provider, allocation: rec.scenario.allocation.label, rate: '$' + rec.declared.price.rate.toFixed(2) + ' / GPU-hr', cost_per_1000: c ? c.costPer1000 : null, p95_ttft_ms: a ? a.metrics.ttft.p95 : null, p95_e2e_ms: a ? a.metrics.e2e.p95 : null, runs: a ? a.runs : 0, accepted_per_s: a ? a.rate : null, unit: a ? a.unit : null };
  const comp = rec.declared.comparator ? { label: rec.declared.comparator.provider, allocation: rec.declared.comparator.gpus + '× ' + rec.declared.comparator.provider.replace(/^Nebius /, ''), rate: '$' + rec.declared.comparator.rate.toFixed(2) + ' / GPU-hr', cost_per_1000: null, p95_ttft_ms: null, p95_e2e_ms: null, runs: 0, price_only: true, required_rate_to_tie: rec.derived.comparison ? rec.derived.comparison.required_rate_to_tie : null } : null;
  return {
    schema: 'hot-aisle/headline@2', status: rec.synthetic ? 'demonstration' : 'published', record_id: rec.id, record_sha256: rec.sha256, generated: true,
    unit: a ? a.unit : 'accepted requests',
    workload: plan.workload.model + ' · ' + plan.workload.input_len.toLocaleString('en-US') + ' in / ' + plan.workload.output_len + ' out · concurrency ' + plan.concurrency.join(', '),
    primary_concurrency: rec.derived.primary_concurrency,
    qualified: rec.disposition.qualified, reasons: rec.disposition.reasons,
    sides: comp ? [side, comp] : [side],
    saving: null,
    published_on, evidence_url, report_url,
  };
}

function summary(rec) {
  const h = headline(rec);
  const s = h.sides[0];
  const lines = [(rec.synthetic ? 'DEMONSTRATION (synthetic) — ' : '') + 'Qualified record ' + rec.id + ': ' + (rec.disposition.qualified ? 'QUALIFIED' : 'NOT QUALIFIED')];
  lines.push(h.workload);
  lines.push(s.label + ' · ' + s.allocation + ' · ' + s.rate + ': ' + (s.cost_per_1000 === null ? 'no finite cost' : '$' + s.cost_per_1000.toFixed(s.cost_per_1000 < 1 ? 4 : 2)) + ' per 1,000 ' + h.unit + ' at concurrency ' + h.primary_concurrency + '; p95 TTFT ' + fmt(s.p95_ttft_ms) + ' ms; p95 E2E ' + fmt(s.p95_e2e_ms) + ' ms; ' + s.runs + ' trial(s).');
  for (const c of rec.derived.cells) lines.push('  concurrency ' + c.concurrency + ': ' + (c.meets ? 'meets requirements' : 'does not meet: ' + c.reasons.join(' ')) + (c.cost && c.cost.costPer1000 !== null ? ' · $' + c.cost.costPer1000.toFixed(4) + '/1,000' : ''));
  if (h.sides[1]) lines.push(h.sides[1].label + ' at ' + h.sides[1].rate + ' would need ' + fmt(h.sides[1].required_rate_to_tie, 3) + ' ' + h.unit + '/s to tie on rental cost (price ratio, not a measurement).');
  lines.push('Reasons: ' + rec.disposition.reasons.join(' '));
  return lines.join('\n');
}

function fmt(v, d = 0) { return v === null || v === undefined ? '—' : Number(v).toLocaleString('en-US', { maximumFractionDigits: d }); }

return { build, verify, derive, packet, receipt, headline, summary, primaryCell, requirements, declaredIdentity };

})();
const revalidate=(()=>{
'use strict';
/* Selective revalidation. Given a qualified record and a change, decide which
   conclusions still stand, which can be recomputed from retained evidence with no
   GPU time, which require new measurement, and the smallest plan that restores
   confidence. The dependency model is explicit so the answer is inspectable. */



const RUNTIME_KEYS = ['model_revision', 'precision', 'tokenizer_revision', 'runtime_digest', 'cache_policy'];
const WORKLOAD_KEYS = ['model', 'dataset', 'input_len', 'output_len', 'num_prompts', 'request_rate', 'backend'];

function revalidate(rec, change) {
  const verified=record.verify(rec);if(!verified.verified)throw Error('Revalidation requires a verified record: '+verified.problems.join(' '));
  if(change?.price?.gpus!==undefined&&change.price.gpus!==rec.declared.plan.price.gpus)throw Error('A different GPU allocation requires new performance qualification; change only its price here.');
  if (!change || typeof change !== 'object') throw new Error('change must be an object.');
  const kinds = Object.keys(change).filter(k => change[k] !== undefined && change[k] !== null);
  if (!kinds.length) throw new Error('Nothing changed.');
  const plan = rec.declared.plan;
  const conclusions = [];
  let candidate = null, scenario = null, requiredCells = new Set(), reevaluate = false;

  /* Economics depend only on price inputs and retained aggregates. */
  if (change.price) {
    const price = { ...plan.price, ...change.price };
    scenario = priceScenario(rec, price);
    conclusions.push(c('economics', 'recomputed', 'Cost per 1,000 recomputed from retained trials at ' + price.gpus + ' × $' + price.rate + ' + $' + (price.extra || 0) + '/h. No GPU time.'));
    conclusions.push(c('performance', 'stands', 'Throughput and latency do not depend on price.'));
  }

  /* Gates change the accepted denominator; recomputable only when request rows exist. */
  if (change.gates) {
    const rows = rec.observed.trials.every(t => t.normalized.rows);
    if (rows && !(change.gates.quality && !rec.observed.trials.every(t => t.normalized.quality))) {
      scenario = gateScenario(rec, { ...plan.gates, ...change.gates }, scenario);
      conclusions.push(c('acceptance', 'recomputed', 'Accepted counts recomputed from retained per-request samples under the new gates.'));
    } else {
      for (const cell of rec.derived.cells) requiredCells.add(cell.concurrency);
      conclusions.push(c('acceptance', 'requires_measurement', rows ? 'Evaluator-passed gating needs a sidecar for every trial; none retained.' : 'Retained trials have no per-request samples; gating needs a detailed rerun.'));
    }
  }

  /* Requirements are thresholds over existing aggregates: always recomputable. */
  if (change.requirements) {
    scenario = requirementScenario(rec, { ...plan.requirements, ...change.requirements }, scenario);
    conclusions.push(c('qualification', 'recomputed', 'Requirement thresholds re-applied to retained aggregates.'));
  }

  /* Traffic: cells already measured under identical workload stand; new cells need
     measurement; a changed request shape is a different workload identity. */
  if (change.traffic) {
    const t = change.traffic;
    const shapeChanged = WORKLOAD_KEYS.some(k => t[k] !== undefined && t[k] !== plan.workload[k]);
    const wanted = t.concurrency ? [...new Set(t.concurrency.map(Number))].sort((a, b) => a - b) : plan.concurrency;
    if (shapeChanged) {
      for (const cc of wanted) requiredCells.add(cc);
      conclusions.push(c('capacity', 'requires_measurement', 'Request shape changed (' + WORKLOAD_KEYS.filter(k => t[k] !== undefined && t[k] !== plan.workload[k]).join(', ') + '); every cell needs new evidence under the new workload identity.'));
    } else {
      const have = new Set(rec.derived.cells.map(x => x.concurrency));
      const missing = wanted.filter(x => !have.has(x)), kept = wanted.filter(x => have.has(x));
      for (const cc of missing) requiredCells.add(cc);
      if (kept.length) conclusions.push(c('capacity', 'stands', 'Cells at concurrency ' + kept.join(', ') + ' were measured under this workload and stand.'));
      if (missing.length) conclusions.push(c('capacity', 'requires_measurement', 'Concurrency ' + missing.join(', ') + ' has no evidence; ' + plan.repeats + ' trial(s) each.'));
      const dropped = [...have].filter(x => !wanted.includes(x));
      if (dropped.length) conclusions.push(c('capacity', 'stands', 'Concurrency ' + dropped.join(', ') + ' no longer requested; evidence retained.'));
    }
  }

  /* Runtime or model identity: the record is superseded; a new candidate is planned. */
  if (change.runtime) {
    const changed = RUNTIME_KEYS.filter(k => change.runtime[k] !== undefined && change.runtime[k] !== plan.identity[k]);
    if (changed.length) {
      candidate = { ...cloneInput(plan), identity: { ...plan.identity, ...pick(change.runtime, RUNTIME_KEYS) } };
      for (const cc of plan.concurrency) requiredCells.add(cc);
      conclusions.push(c('qualification', 'superseded', 'Runtime identity changed (' + changed.join(', ') + '). This record stays as history; a new candidate qualification covers all cells.'));
      conclusions.push(c('economics', 'stands', 'Price inputs are unchanged, but they will be applied to the candidate\'s new measurements.'));
    } else conclusions.push(c('qualification', 'stands', 'Declared runtime identity is unchanged.'));
  }

  /* Evaluator correction: only evaluator-gated conclusions are affected, and they need
     re-adjudication of retained requests, not new GPU time. */
  if (change.evaluator) {
    if (plan.gates.quality) { reevaluate = true; conclusions.push(c('acceptance', 'requires_reevaluation', 'Acceptance counted evaluator-passed outcomes. Re-run the corrected evaluator over the retained request set and attach new sidecars; no benchmark rerun.')); }
    else conclusions.push(c('acceptance', 'stands', 'Acceptance did not depend on an evaluator.'));
  }

  const required = [...requiredCells].sort((a, b) => a - b);
  let minimal = null;
  if (required.length) {
    const base = candidate || cloneInput(plan);
    if (change.traffic) base.workload = { ...base.workload, ...pick(change.traffic, WORKLOAD_KEYS) };
    minimal = { ...base, concurrency: required, note: (required.length === plan.concurrency.length && !change.traffic ? 'Full candidate qualification.' : 'Only the cells without valid evidence.') + ' Prior trials are retained in ' + rec.id + '.' };
  }
  const summary = { stands: conclusions.filter(x => x.status === 'stands').length, recomputed: conclusions.filter(x => x.status === 'recomputed').length, requires_measurement: required.length ? required.length * plan.repeats : 0, superseded: conclusions.some(x => x.status === 'superseded') };
  return { schema: 'hot-aisle/revalidation@1', record_id: rec.id, change, conclusions, scenario, minimal_plan: minimal, reevaluate, summary };
}

function c(subject, status, detail) { return { subject, status, detail }; }
function pick(o, keys) { const out = {}; for (const k of keys) if (o[k] !== undefined) out[k] = o[k]; return out; }
function cloneInput(plan) {
  return { target: { ...plan.target }, workload: { ...plan.workload }, concurrency: [...plan.concurrency], repeats: plan.repeats, identity: { ...plan.identity }, price: { ...plan.price }, comparator: plan.comparator ? { ...plan.comparator } : null, limits: { ...plan.limits }, gates: { ...plan.gates }, requirements: { ...plan.requirements }, primary_concurrency: plan.primary_concurrency };
}

/* Scenario projections reuse the record's own machinery with substituted inputs; the
   observed section is untouched. */
function rederive(rec, planPatch) {
  const clone = JSON.parse(JSON.stringify(rec));
  Object.assign(clone.declared.plan, planPatch);
  if (planPatch.price) clone.declared.price = planPatch.price;
  if (planPatch.gates) clone.rule.gates = planPatch.gates;
  if (planPatch.requirements) clone.rule.requirements = planPatch.requirements;
  const derived = record.derive(clone);
  return { cells: derived.cells.map(x => ({ concurrency: x.concurrency, cost_per_1000: x.cost ? x.cost.costPer1000 : null, accepted_per_s: x.aggregate ? x.aggregate.rate : null, unit: x.aggregate ? x.aggregate.unit : null, meets: x.meets, reasons: x.reasons })), primary_concurrency: derived.primary_concurrency, qualified: derived.disposition.qualified, reasons: derived.disposition.reasons };
}
function priceScenario(rec, price) { return { kind: 'price', price, ...rederive(rec, { price }) }; }
function gateScenario(rec, gates, prev) { const s = rederive(rec, { gates, ...(prev && prev.price ? { price: prev.price } : {}) }); return { kind: prev ? prev.kind + '+gates' : 'gates', gates, ...(prev && prev.price ? { price: prev.price } : {}), ...s }; }
function requirementScenario(rec, requirements, prev) { const s = rederive(rec, { requirements, ...(prev && prev.price ? { price: prev.price } : {}), ...(prev && prev.gates ? { gates: prev.gates } : {}) }); return { ...(prev || {}), kind: prev ? prev.kind + '+requirements' : 'requirements', requirements, ...s }; }

return { revalidate, RUNTIME_KEYS, WORKLOAD_KEYS };

})();
const publication=(()=>{
'use strict';
/* The runner owns the qualified record and its publication contract.
   A desk consumes this pair; it never interprets raw vLLM rows again. */



function verifyRecord(rec) {
  if (!rec || typeof rec !== 'object') throw Error('Qualified record required.');
  const v = record.verify(rec);
  if (!v.verified) throw Error('Qualified record rejected: ' + v.problems.join(' '));
  if (rec.derived.engine.engine_sha256 !== engine.identity().engine_sha256)
    throw Error('Report-engine identity differs; requalify the verifier for this record.');
  return rec;
}
function bundle(rec) {
  verifyRecord(rec);
  const evidence = record.packet(rec);
  engine.load().recompute(evidence);
  return {schema:'hot-aisle/publication@1', record:rec, evidence};
}
function verify(input) {
  if (!input || input.schema !== 'hot-aisle/publication@1') throw Error('Unsupported publication contract.');
  const rec = verifyRecord(input.record), HA=engine.load();
  HA.recompute(input.evidence);
  if (HA.canonical(input.evidence) !== HA.canonical(record.packet(rec)))
    throw Error('Evidence packet does not belong to this qualified record and primary cell.');
  return input;
}
function identity(input) {
  verify(input);
  return engine.sha256(engine.load().canonical(input));
}
function projection(input) {
  verify(input);
  const rec=input.record, cell=record.primaryCell(rec);
  const expected=rec.declared.plan.concurrency.length*rec.declared.plan.repeats;
  return {publication_id:rec.id+'-'+rec.sha256.slice(0,16), record_id:rec.id,
    record_sha256:rec.sha256, publication_sha256:identity(input),
    model:rec.declared.plan.workload.model, created:rec.created,
    synthetic:rec.synthetic, qualified:rec.disposition.qualified,
    completed_trials:rec.observed.trials.length, expected_trials:expected,
    complete:rec.observed.trials.length===expected && rec.observed.failed_trials.length===0,
    primary_concurrency:rec.derived.primary_concurrency,
    headline:record.headline(rec), cell};
}
return {bundle,verify,identity,projection};

})();

function decision(bundle,change=null,createdAt=new Date().toISOString(),previous=null){
 if(previous!==null&&!/^[a-f0-9]{64}$/.test(previous))throw Error("Invalid previous decision identity.");
 publication.verify(bundle);
 const result=change?revalidate.revalidate(bundle.record,change):publication.projection(bundle);
 const payload={kind:'qualified-record',createdAt,title:bundle.record.declared.plan.workload.model,bundle,change,result,...(previous?{previous}:{})};
 return {schema:'second-run/qualified-decision@1',sha256:engine.sha256(HA.canonical(payload)),payload};
}
function verifyDecision(envelope){
 if(envelope?.schema!=='second-run/qualified-decision@1'||envelope.sha256!==engine.sha256(HA.canonical(envelope.payload)))throw Error('Qualified decision checksum mismatch.');
 const fresh=decision(envelope.payload.bundle,envelope.payload.change,envelope.payload.createdAt,envelope.payload.previous||null);
 if(HA.canonical(fresh)!==HA.canonical(envelope))throw Error('Qualified decision does not recompute from its instrument record.');
 return envelope;
}
return {authority,record,revalidate:revalidate.revalidate,publication,decision,verifyDecision};
});
