#!/usr/bin/env python3
"""Generate copies from their owning sources; check mode never mutates files.
The desk owns public catalogue scenarios. The instrument owns measurement arithmetic,
qualification, revalidation and publication. Runtime deployments remain self-contained.
"""
from pathlib import Path
import json,re,hashlib,sys
ROOT=Path(__file__).resolve().parent.parent

def sha(b):return hashlib.sha256(b).hexdigest()
def render():
    cpath=ROOT/'compute/data/catalog.json';cb=cpath.read_bytes();c=json.loads(cb)
    page=(ROOT/'hot-aisle/index.html').read_text(encoding='utf-8')
    m=re.search(r'<script id="report-engine">([\s\S]*?)</script>',page)
    if not m:raise ValueError('Instrument report engine missing')
    h=m.group(1);identity={'version':'2.0.0','engine_sha256':sha(h.encode())}
    output={'hot-aisle/data/catalog.json':cb}
    sources={}
    modules=[]
    for name in ['record','revalidate','publication']:
        p=ROOT/f'hot-aisle/runner/lib/{name}.cjs';raw=p.read_text(encoding='utf-8');sources[name]=sha(p.read_bytes())
        raw=raw.replace("const engine = require('./engine.cjs');",'').replace("const record = require('./record.cjs');",'')
        raw=raw.replace('module.exports = ','return ').replace('module.exports=','return ')
        modules.append(f'const {name}=(()=>{{\n{raw}\n}})();\n')
    generated='''/* GENERATED by integration/build.py from the instrument sources. */
(function(root,factory){const H=typeof module==='object'&&module.exports?require('./workload-engine.cjs'):root.HA;const api=factory(H);if(typeof module==='object'&&module.exports)module.exports=api;root.WorkloadQualification=api;})(typeof globalThis!=='undefined'?globalThis:this,function(HA){
'use strict';
'''+f"const authority={json.dumps({'engine':identity,'sources':sources},sort_keys=True)};\n"+'''const engine={load:()=>HA,identity:()=>authority.engine,sha256:x=>HA.sha256(typeof x==='string'?new TextEncoder().encode(x):x)};
'''+''.join(modules)+'''
function decision(bundle,change=null,createdAt=new Date().toISOString(),previous=null){
 if(previous!==null&&!/^[a-f0-9]{64}$/.test(previous))throw Error("Invalid previous decision identity.");
 publication.verify(bundle);
 const result=change?revalidate.revalidate(bundle.record,change):publication.projection(bundle);
 const payload={kind:'qualified-record',createdAt,title:bundle.record.declared.plan.workload.model,bundle,change,result,...(previous?{previous}:{})};
 return {schema:'second-run/qualified-decision@1',sha256:engine.sha256(HA.canonical(payload)),payload};
}
function verifyDecision(envelope){
 if(envelope?.schema!=='second-run/qualified-decision@1'||envelope.sha256!==engine.sha256(HA.canonical(envelope.payload)))throw Error('Qualified decision checksum mismatch.');
 const fresh=decision(envelope.payload.bundle,envelope.payload.change,envelope.payload.createdAt,envelope.payload.previous||null);
 if(HA.canonical(fresh)!==HA.canonical(envelope))throw Error('Qualified decision does not recompute from its instrument record.');
 return envelope;
}
return {authority,record,revalidate:revalidate.revalidate,publication,decision,verifyDecision};
});
'''
    output['compute/adapters/workload-engine.cjs']=h.encode()
    output['compute/adapters/qualified-engine.cjs']=generated.encode()
    def rate(o,when):
        v=o['rate']
        for s in sorted(o.get('schedules',[]),key=lambda x:x['effectiveOn']):
            if s['effectiveOn']<=when:v=s['rate']
        return v
    ha=[o for o in c['offers'] if o['provider']=='hotaisle'];nb=[o for o in c['offers'] if o['provider']=='nebius']
    prices={'schema':'second-run/price-snapshot@1','reviewed_on':c['reviewedOn'],'currency':c['currency'],
      'generated_from':{'path':'compute/data/catalog.json','sha256':sha(cb)},
      'hot_aisle':{'vm_gpu_hour':ha[0]['rate'],'vm_gpu_counts':[o['gpus'] for o in ha if o['kind']=='on-demand'],'bare_metal_gpu_hour':next(o['rate'] for o in ha if o['kind']=='monthly'),'bare_metal_gpu_count':8,'source':c['sources']['hotaisle']['url']},
      'nebius_ai_cloud':{'effective_new_prices':'2026-10-01','source':c['sources']['nebius']['url'],'products':[{'gpu':o['gpu'],'current_gpu_hour':rate(o,c['reviewedOn']),'october_gpu_hour':rate(o,'2026-10-01')} for o in nb]}}
    output['hot-aisle/data/prices.json']=(json.dumps(prices,indent=2)+'\n').encode()
    for ident,body in [('prices-data',json.dumps(prices,indent=2)),('catalog-data',cb.decode())]:
        block=f'<script id="{ident}" type="application/json">'+body.replace('</script','<\\/script')+'</script>'
        pattern=f'<script id="{ident}" type="application/json">[\\s\\S]*?</script>'
        if re.search(pattern,page):page=re.sub(pattern,lambda m:block,page,count=1)
        else:page=page.replace('<script id="report-engine">',block+'\n<script id="report-engine">',1)
    qblock='<script id="qualified-engine">'+generated.replace('</script','<\\/script')+'</script>'
    if re.search(r'<script id="qualified-engine">[\s\S]*?</script>',page):page=re.sub(r'<script id="qualified-engine">[\s\S]*?</script>',lambda m:qblock,page,count=1)
    else:
        m=re.search(r'<script id="report-engine">[\s\S]*?</script>',page)
        page=page[:m.end()]+'\n'+qblock+page[m.end():]
    output['hot-aisle/index.html']=page.encode()
    output['integration/AUTHORITIES.json']=(json.dumps({'schema':'second-run/integration-authorities@1','catalogue':{'source':'compute/data/catalog.json','sha256':sha(cb),'reviewed_on':c['reviewedOn']},'instrument':identity,'derived_source_hashes':sources,'rule':'Copies are generated for self-contained deployment; these locations identify the editing authority.'},indent=2)+'\n').encode()
    return output

def main():
    updates=render();check='--check' in sys.argv;bad=[]
    for name,body in updates.items():
        p=ROOT/name
        if check:
            if not p.exists() or p.read_bytes()!=body:bad.append(name)
        else:p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(body)
    if bad:raise SystemExit('Generated authority copies differ: '+', '.join(bad))
    print(('Checked' if check else 'Generated')+f' {len(updates)} authority projections')
if __name__=='__main__':main()
