#!/usr/bin/env node
/* Read-only local workspace and stdio MCP adapter. Built-in Node modules only. */
'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto');
const C=require('../engine.cjs'),H=require('../adapters/workload-engine.cjs');
const Instrument=require('../adapters/instrument.cjs');
const Materials=require('./materials.cjs');
const ROOT=path.resolve(__dirname,'..');
const catalog=C.validateCatalog(JSON.parse(fs.readFileSync(path.join(ROOT,'data/catalog.json'),'utf8')));
const MAX=25*1024*1024;
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
function parseArgs(args){const o={mcp:false,results:null,aperture:null,endpoint:null,port:0,keyEnv:null,runner:null};for(let i=0;i<args.length;i++){const a=args[i];if(a==='--mcp')o.mcp=true;else if(a==='--help'){o.help=true;}else if(['--results','--aperture','--endpoint','--port','--api-key-env','--runner'].includes(a)){const v=args[++i];if(!v||v.startsWith('--'))throw Error('Missing value for '+a);o[{'--results':'results','--aperture':'aperture','--endpoint':'endpoint','--port':'port','--api-key-env':'keyEnv','--runner':'runner'}[a]]=v;}else throw Error('Unknown option '+a);}o.port=Number(o.port);if(!Number.isSafeInteger(o.port)||o.port<0||o.port>65535)throw Error('Invalid port');return o;}
function fixedPath(p,directory){if(!p)return null;const absolute=path.resolve(p),stat=fs.lstatSync(absolute);if(stat.isSymbolicLink()||!(directory?stat.isDirectory():stat.isFile()))throw Error('Configured path must be a real '+(directory?'directory':'file')+'.');return fs.realpathSync(absolute);}
function readLimited(p){const fd=fs.openSync(p,fs.constants.O_RDONLY|(fs.constants.O_NOFOLLOW||0));try{const s=fs.fstatSync(fd);if(!s.isFile()||s.size>MAX)throw Error('File outside read limit.');const b=fs.readFileSync(fd);if(b.length>MAX)throw Error('File outside read limit.');return b;}finally{fs.closeSync(fd);}}
function makeWorkspace(options){
 const instrument=Instrument.create(options.runner,fs.readFileSync(path.join(ROOT,'data/catalog.json')));
 const directory=fixedPath(options.results,true),hardwarePath=fixedPath(options.aperture,false);let endpoint=null;
 if(options.endpoint){endpoint=new URL(options.endpoint);if(endpoint.username||endpoint.password||endpoint.search||endpoint.hash)throw Error('Endpoint must exclude embedded credentials, query and fragment.');if(!['https:','http:'].includes(endpoint.protocol))throw Error('Use an HTTP(S) endpoint.');if(endpoint.protocol==='http:'&&!['127.0.0.1','localhost','[::1]'].includes(endpoint.hostname))throw Error('Plain HTTP is limited to loopback. Use HTTPS for a remote endpoint.');}
 if(options.keyEnv&&!/^[A-Za-z_][A-Za-z0-9_]*$/.test(options.keyEnv))throw Error('Invalid API-key environment variable.');
 let runs=new Map();
 function listRuns(){const next=new Map(),holds=[];let total=0,files=0;const discovered=[];
 function walk(dir,depth){for(const entry of fs.readdirSync(dir,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name))){if(files>=200)break;const p=path.join(dir,entry.name);if(entry.isSymbolicLink()){holds.push({reason:'Symlink skipped.'});continue;}if(entry.isDirectory()&&depth<1)walk(p,depth+1);else if(entry.isFile()&&/\.(json|jsonl|txt)$/i.test(entry.name)){files++;discovered.push(p);}}}
 if(directory)walk(directory,0);
 for(const p of discovered){try{const real=fs.realpathSync(p);if(!real.startsWith(directory+path.sep))throw Error('Path left approved directory.');const bytes=readLimited(real);total+=bytes.length;if(total>64*1024*1024){holds.push({reason:'Directory read budget reached (64 MiB).'});break;}const id=sha(bytes);if(next.has(id)){holds.push({reason:'Duplicate source bytes skipped.'});continue;}const docs=H.parseDocuments(new TextDecoder('utf-8',{fatal:true}).decode(bytes));if(docs.some(d=>d.schema==='aperture-support/1'||d.schema==='second-run/sealed-compute-decision@1'))continue;
 const normalized=docs.map((d,i)=>H.normalize(d,{sha256:id,bytes:bytes.length,record_index:i})),a=H.aggregate(normalized,{identity:{}});
 next.set(id,{id,sha256:id,capturedAt:new Date().toISOString(),title:a.identity.model||'Unnamed workload',trials:normalized.length,completed:a.completed,duration:a.duration,synthetic:a.synthetic,aggregate:a,normalized});
 }catch{holds.push({reason:'One input was unavailable, malformed, unrecognized, or internally inconsistent.'});}}
 runs=next;return {schema:'second-run/workspace-runs@1',observedAt:new Date().toISOString(),source:'CONFIGURED_LOCAL_DIRECTORY',runs:[...runs.values()].map(({id,title,trials,completed,duration,synthetic,capturedAt})=>({id,title,trials,completed,duration,synthetic,capturedAt})),holds};}
 function getRun(id){if(!/^[a-f0-9]{64}$/.test(id))throw Error('Use an observed run ID.');const r=runs.get(id);if(!r)throw Error('Run unavailable. Refresh the configured directory.');return r;}
 function hardware(){if(!hardwarePath)return null;return C.aperture(JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(readLimited(hardwarePath))));}
 async function getEndpoint(){if(!endpoint)return {status:'NOT_CONFIGURED',models:[]};
 async function request(route,json){const base=new URL(endpoint);base.pathname=base.pathname.replace(/\/$/,'').replace(/\/v1$/,'')+route;const headers={Accept:json?'application/json':'text/plain'};if(options.keyEnv){const key=process.env[options.keyEnv];if(!key)throw Error('Configured key variable is unavailable.');headers.Authorization='Bearer '+key;}
 const r=await fetch(base,{headers,redirect:'error',signal:AbortSignal.timeout(4000)});if(!r.ok)throw Error('Endpoint read failed.');const reader=r.body.getReader();let len=0,chunks=[];try{while(true){const v=await reader.read();if(v.done)break;len+=v.value.byteLength;if(len>2*1024*1024)throw Error('Endpoint response too large.');chunks.push(v.value);}}finally{await reader.cancel().catch(()=>{});}const s=Buffer.concat(chunks).toString('utf8');return json?JSON.parse(s):s;}
 try{const data=await request('/v1/models',true);if(!Array.isArray(data.data))throw Error('Unsupported model listing.');const models=data.data.slice(0,40).map(m=>C.text(m.id));let metrics={},metricState='UNAVAILABLE';try{const raw=await request('/metrics',false),allowed=['vllm:num_requests_running','vllm:num_requests_waiting','vllm:prompt_tokens_total','vllm:generation_tokens_total'];for(const line of raw.split('\n')){const m=line.match(/^([a-zA-Z_:][a-zA-Z0-9_:]*)(?:\{[^\n]*\})?\s+([-+0-9.eE]+)(?:\s|$)/);if(m&&allowed.includes(m[1])&&Number.isFinite(Number(m[2]))){metrics[m[1]]=(metrics[m[1]]||0)+Number(m[2]);}}metricState=Object.keys(metrics).length?'OBSERVED':'NO_RECOGNIZED_METRICS';}catch{}
 return {status:'OBSERVED',observedAt:new Date().toISOString(),models,metrics,metricState,basis:'Read-only model list and sum of configured endpoint metric series. Not task correctness, a hardware scan or a benchmark.'};
 }catch{return {status:'UNAVAILABLE',models:[],message:'Configured endpoint could not be read within its bounded request policy.'};}}
 return {listRuns,getRun,hardware,getEndpoint,listPublications:instrument.list,getPublication:instrument.read,instrumentOrigin:instrument.origin};
}
const objectSchema=properties=>({type:'object',properties,additionalProperties:false});
const num={type:'number',minimum:0},str={type:'string'};
const tools=[
 {name:'compute_materials',description:'Read the reviewed operating-input registry, captured source freshness, reusable components and bounded workload qualification recipes. No live inventory, quote verification, installation, dispatch or route promotion.',inputSchema:objectSchema({recipe:str,layer:str})},
 {name:'compute_list_publications',description:'Discover explicitly published immutable qualification records from the configured runner. Reads only; creates no plan or job and performs no benchmark.',inputSchema:objectSchema({})},
 {name:'compute_get_publication',description:'Read and independently recompute a published instrument record and its sealed evidence packet using generated copies of the instrument authority. Qualifying software fixtures stay synthetic.',inputSchema:{...objectSchema({id:str}),required:['id']}},
 {name:'compute_list_offers',description:'Compare dated GPU allocation prices under a per-GPU memory floor. Returns prices, not model-fit or throughput qualification.',inputSchema:objectSchema({hours:num,minMemoryGB:num,provider:str,vendor:str,asOf:str,gpus:{type:'integer',minimum:0},extraPerHour:num,fixedCost:num})},
 {name:'compute_ownership',description:'Compute owned-system energy, amortization and rental cost. Optional accepted-work rates scale rental hours. Inputs are scenarios, not measurements.',inputSchema:{type:'object',properties:Object.fromEntries(['hours','capex','residual','months','loadWatts','idleWatts','kwhPrice','opsMonthly','powerFactor','cloudHourly','cloudMinimumHours','localRate','cloudRate'].map(k=>[k,num])),required:['hours','capex','residual','months','loadWatts','idleWatts','kwhPrice','cloudHourly'],additionalProperties:false}},
 {name:'compute_route_scenario',description:'Price task-conditioned reuse, validation and fallback, retaining the difference between request movement and premium GPU time. Does not admit or execute a route.',inputSchema:{type:'object',properties:{requests:{type:'integer',minimum:1},premiumHourly:num,qualificationCost:num,validationCostPerRequest:num,repeats:{type:'integer',minimum:1},classes:{type:'array',maxItems:30,items:{type:'object',properties:{name:str,share:num,baselineSeconds:num,targetSeconds:num,targetHourly:num,fallbackPercent:num,premium:{type:'boolean'}},required:['name','share','baselineSeconds','targetSeconds','targetHourly','fallbackPercent','premium'],additionalProperties:false}}},required:['requests','premiumHourly','qualificationCost','classes'],additionalProperties:false}},
 {name:'compute_plan',description:'Prepare an evidence-aware compute shortlist with explicit required checks. This is a proposal, not execution, purchasing or deployment authority.',inputSchema:{...objectSchema({offerIds:{type:'array',maxItems:4,items:str},hours:num,asOf:str,minMemoryGB:num,workload:str,acceptance:str,extraPerHour:num,fixedCost:num}),required:['offerIds','hours']}},
 {name:'compute_list_runs',description:'Read supported existing benchmark files from the one operator-configured directory. Original filenames and generated content are excluded.',inputSchema:objectSchema({})},
 {name:'compute_get_run',description:'Read an already-observed normalized run by SHA-256 ID. Does not accept filesystem paths.',inputSchema:{...objectSchema({id:str}),required:['id']}},
 {name:'compute_hardware',description:'Read the operator-configured aperture-support/1 receipt. Does not scan or stress hardware.',inputSchema:objectSchema({})},
 {name:'compute_endpoint',description:'Read model names and selected counters from the one operator-configured OpenAI-compatible endpoint. No inference, requests to arbitrary URLs or endpoint changes.',inputSchema:objectSchema({})}
].map(t=>({...t,annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:t.name==='compute_endpoint'}}));
function validateValue(value,schema,label='arguments'){
 if(schema.type==='object'){if(value===null||typeof value!=='object'||Array.isArray(value))throw Error(label+' must be an object.');for(const k of Object.keys(value)){if(!Object.hasOwn(schema.properties||{},k)){if(schema.additionalProperties===false)throw Error('Unknown argument '+k);continue;}validateValue(value[k],schema.properties[k],label+'.'+k);}for(const k of schema.required||[])if(!Object.hasOwn(value,k))throw Error('Missing required argument '+k);}
 else if(schema.type==='array'){if(!Array.isArray(value)||value.length>(schema.maxItems??1000))throw Error(label+' is outside its array limit.');for(const v of value)validateValue(v,schema.items,label+'[]');}
 else if(schema.type==='number'||schema.type==='integer'){if(typeof value!=='number'||!Number.isFinite(value)||value<(schema.minimum??-Infinity)||value>(schema.maximum??Number.MAX_SAFE_INTEGER)||(schema.type==='integer'&&!Number.isSafeInteger(value)))throw Error(label+' is outside its numeric contract.');}
 else if(schema.type==='string'){if(typeof value!=='string'||value.length>4000)throw Error(label+' must be a bounded string.');}
 else if(schema.type==='boolean'&&typeof value!=='boolean')throw Error(label+' must be boolean.');
}
function validateArgs(tool,args){validateValue(args,tool.inputSchema);}
async function call(workspace,name,args){const t=tools.find(t=>t.name===name);if(!t)throw Error('Unknown tool.');validateArgs(t,args);const defaults={hours:160,asOf:new Date().toISOString().slice(0,10)};
 switch(name){case'compute_materials':return Materials.inspect(ROOT,args);case'compute_list_publications':return workspace.listPublications();case'compute_get_publication':return workspace.getPublication(args.id);case'compute_list_offers':return {freshness:C.freshness(catalog,defaults.asOf),offers:C.market(catalog,{...defaults,...args})};case'compute_ownership':return C.ownership(args);case'compute_route_scenario':return C.route(args);case'compute_plan':return C.plan(catalog,{...defaults,...args});case'compute_list_runs':return workspace.listRuns();case'compute_get_run':return workspace.getRun(args.id);case'compute_hardware':return workspace.hardware()||{status:'NOT_CONFIGURED'};case'compute_endpoint':return workspace.getEndpoint();}}
function startMcp(workspace,input=process.stdin,output=process.stdout){let initialized=false,buffer='';const send=o=>output.write(JSON.stringify(o)+'\n');const respond=async m=>{if(!m||m.jsonrpc!=='2.0'||typeof m.method!=='string'){send({jsonrpc:'2.0',id:m?.id??null,error:{code:-32600,message:'Invalid request'}});return;}if(m.id===undefined){if(m.method==='notifications/initialized')initialized=true;return;}try{let result;if(m.method==='initialize'){const supported=['2025-11-25','2025-06-18'];result={protocolVersion:supported.includes(m.params?.protocolVersion)?m.params.protocolVersion:'2025-11-25',capabilities:{tools:{listChanged:false}},serverInfo:{name:'second-run-compute',version:C.VERSION},instructions:'Read-only compute planning and configured evidence observation. No execution, provisioning, payment or public upload.'};}else if(m.method==='ping')result={};else if(!initialized)throw Error('Initialize the session first.');else if(m.method==='tools/list')result={tools};else if(m.method==='tools/call'){try{const data=await call(workspace,m.params?.name,m.params?.arguments||{});result={content:[{type:'text',text:JSON.stringify(data)}],structuredContent:data===null?{value:null}:data,isError:false};}catch(e){result={content:[{type:'text',text:e.message}],isError:true};}}else{send({jsonrpc:'2.0',id:m.id,error:{code:-32601,message:'Method not found'}});return;}send({jsonrpc:'2.0',id:m.id,result});}catch(e){send({jsonrpc:'2.0',id:m.id,error:{code:-32602,message:e.message}});}};
 let queue=Promise.resolve();input.setEncoding('utf8');input.on('data',s=>{buffer+=s;if(buffer.length>1024*1024){process.stderr.write('MCP input exceeds 1 MiB.\n');process.exitCode=2;input.destroy();return;}let ix;while((ix=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,ix);buffer=buffer.slice(ix+1);if(!line.trim())continue;let m;try{m=JSON.parse(line);}catch{send({jsonrpc:'2.0',id:null,error:{code:-32700,message:'Invalid JSON'}});continue;}queue=queue.then(()=>respond(m));}});return {done:()=>queue};}
function startHttp(workspace,port=0){const token=crypto.randomBytes(32).toString('hex');let origin;const staticFiles={'/':'index.html','/index.html':'index.html','/compute-kit.zip':'compute-kit.zip','/adapters/workload-report-v2.html':'adapters/workload-report-v2.html','/README.md':'README.md','/METHOD.md':'METHOD.md','/PROVENANCE.json':'PROVENANCE.json','/MANIFEST.json':'MANIFEST.json','/QUALIFICATION.json':'QUALIFICATION.json'};const server=http.createServer(async(req,res)=>{
 const headers={'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Content-Security-Policy':"default-src 'none'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; font-src 'none'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'"};
 function out(code,body,type='application/json'){res.writeHead(code,{...headers,'Content-Type':type});res.end(typeof body==='string'||Buffer.isBuffer(body)?body:JSON.stringify(body));}
 if(req.headers.host!==new URL(origin).host||req.headers.origin&&req.headers.origin!==origin)return out(403,{error:'Origin or host denied.'});if(req.method!=='GET')return out(405,{error:'Read-only server.'});const u=new URL(req.url,origin);
 if(Object.hasOwn(staticFiles,u.pathname)){try{const f=staticFiles[u.pathname],b=fs.readFileSync(path.join(ROOT,f));return out(200,b,f.endsWith('.zip')?'application/zip':f.endsWith('.html')?'text/html; charset=utf-8':f.endsWith('.json')?'application/json':'text/plain; charset=utf-8');}catch{return out(404,{error:'Static artifact not found; run the build.'});}}
 if(!u.pathname.startsWith('/api/'))return out(404,{error:'Not found.'});const auth=Buffer.from(req.headers.authorization||''),expected=Buffer.from('Bearer '+token);if(auth.length!==expected.length||!crypto.timingSafeEqual(auth,expected))return out(401,{error:'Local session authorization required.'});
 try{if(u.pathname==='/api/status')return out(200,{version:C.VERSION,readOnly:true,hardware:workspace.hardware(),runtime:await workspace.getEndpoint(),instrumentOrigin:workspace.instrumentOrigin});if(u.pathname==='/api/publications')return out(200,await workspace.listPublications());if(/^\/api\/publications\/rec-[A-Za-z0-9._-]+-[a-f0-9]{16}$/.test(u.pathname))return out(200,await workspace.getPublication(u.pathname.split('/').pop()));if(u.pathname==='/api/runs')return out(200,workspace.listRuns());if(/^\/api\/runs\/[a-f0-9]{64}$/.test(u.pathname))return out(200,workspace.getRun(u.pathname.split('/').pop()));return out(404,{error:'Unknown read-only resource.'});}catch{return out(422,{error:'Configured evidence could not be read or validated.'});}
 });return new Promise((resolve,reject)=>{server.once('error',reject);server.listen(port,'127.0.0.1',()=>{origin='http://127.0.0.1:'+server.address().port;resolve({server,origin,token,url:origin+'/#connection='+token});});});}
if(require.main===module){(async()=>{const opts=parseArgs(process.argv.slice(2));if(opts.help){console.log('node scripts/connect.cjs [--mcp] [--runner http://127.0.0.1:8787] [--results DIR] [--aperture RECEIPT] [--endpoint URL] [--api-key-env VAR] [--port N]\nRead-only. Does not scan hardware, call models, rent GPUs or execute jobs.');return;}const ws=makeWorkspace(opts);if(opts.mcp){startMcp(ws);}else{const service=await startHttp(ws,opts.port);console.log('Open your private local workspace:\n'+service.url+'\n\nRead-only. Stop with Ctrl+C.');for(const sig of ['SIGINT','SIGTERM'])process.on(sig,()=>service.server.close(()=>process.exit(0)));}})().catch(e=>{console.error('COMPUTE CONNECTION: '+e.message);process.exitCode=2;});}
module.exports={parseArgs,makeWorkspace,startMcp,startHttp,call,tools};
