'use strict';
// Independent qualification of the actual immutable owner, not a substitute engine.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const crypto = require('node:crypto');
const root = path.resolve(__dirname, '../../..');
const bytes = fs.readFileSync(path.join(root, 'research-desk/app.html'));
assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'), '5951f7f3d994ec980d2958ae18246edc6dbe5b57db8d38e90c1c18956b96e470');
vm.runInThisContext(bytes.toString().match(/<script id="research-core">([\s\S]*?)<\/script>/)[1]);
const C = globalThis.ResearchCore;
(async () => {
 const checks=[];
 const passed=name=>checks.push({name,status:'PASS'});
 const ws=C.empty('Independent qualification');
 const record=(id,kind,deps,data)=>({id,kind,title:id,summary:'Qualification fixture; no performance claim.',tier:'synthetic',disposition:'supported',deps,data});
 await C.put(ws,record('source','source',[],{rate:2,measured:8622}),'Test reviewer');
 await C.put(ws,record('economics','claim',[{id:'source',revision:1}],{scenario:true}),'Test reviewer');
 await C.put(ws,record('recommendation','conclusion',[{id:'economics',revision:1}],{}),'Test reviewer');
 await assert.rejects(()=>C.freeze(ws,'recommendation','Test reviewer'),/review/i);
 await assert.rejects(()=>C.review(ws,'recommendation','accept','short','Test reviewer'),/12 characters/i);
 await C.review(ws,'recommendation','accept','Independent test review of exact dependency closure.','Test reviewer');
 await C.freeze(ws,'recommendation','Test reviewer');
 const first=C.clone(C.state(ws).reports[0]);
 passed('native review and freeze gate');
 await C.put(ws,record('source','source',[],{rate:3,measured:8622}),'Test reviewer');
 assert.equal(C.dependencyState(C.state(ws),'recommendation').current,false);
 assert.deepEqual(C.impact(C.state(ws),'source'),['economics','recommendation']);
 assert.equal((await C.reviewState(C.state(ws),'recommendation')).ready,false);
 await assert.rejects(()=>C.freeze(ws,'recommendation','Test reviewer'),/review/i);
 await assert.rejects(()=>C.review(ws,'recommendation','accept','Cannot approve a stale conclusion.','Test reviewer'),/stale/i);
 passed('transitive staleness and stale acceptance refusal');
 await C.put(ws,record('economics','claim',[{id:'source',revision:2}],{scenario:true}),'Test reviewer');
 await C.put(ws,record('recommendation','conclusion',[{id:'economics',revision:2}],{}),'Test reviewer');
 await assert.rejects(()=>C.freeze(ws,'recommendation','Test reviewer'),/review/i);
 await C.review(ws,'recommendation','accept','Fresh review after changed input and successor.','Test reviewer');
 await C.freeze(ws,'recommendation','Test reviewer');
 assert.equal(C.state(ws).reports.length,2);
 assert.deepEqual(C.state(ws).reports[0],first);
 passed('successor requires renewed review and preserves first delivery');
 const packet=await C.pack(ws);
 assert.deepEqual(await C.verifyPacket(packet),ws);
 const changed=C.clone(packet); changed.workspace.events[0].payload.data.rate=100;
 await assert.rejects(()=>C.verifyPacket(changed),/checksum/i);
 // A recomputed envelope alone must not bypass journal integrity.
 changed.sha256=await C.hash(changed.workspace);
 await assert.rejects(()=>C.verifyPacket(changed),/hash/i);
 assert.deepEqual(await C.pack(ws),packet);
 passed('packet replay and two-layer mutation refusal');
 const sample=JSON.parse(fs.readFileSync(path.join(root,'research-desk/examples/task-run-a.json'),'utf8'));
 const policy=JSON.parse(fs.readFileSync(path.join(root,'research-desk/examples/task-policy.json'),'utf8'));
 const before=C.evaluate(sample,policy);
 const scenario=C.reprice(sample,1,8,2);
 assert.deepEqual(scenario.tasks,sample.tasks);
 assert.deepEqual(scenario.pins,sample.pins);
 assert.equal(scenario.billing.actual_total_usd,sample.billing.actual_total_usd);
 const after=C.evaluate(scenario,policy);
 for(const key of ['tasks','attempts','quality','accepted','success_rate','censored','completed_latency_p95_ms','actual_total_usd']) assert.deepEqual(after[key],before[key]);
 passed('native quote scenario preserves measurements and actual billing');
 console.log(JSON.stringify({status:'PASS',scope:'Native ResearchCore behavior on labeled synthetic fixtures; integrated-page qualification is separate.',checks},null,2));
})().catch(e=>{console.error(e);process.exitCode=1;});
